### ISSUE TITLE
Feature request: Table of content (TOC)

### ISSUE THREAD

**Issue by romspielplatz** [tomusborne/generateblocks#100]
### Description
I suggest to add a table of content block to Generateblocks. It shall be WPML/Polylang compatible, SEO friendly, possibility to define generic settings and to overwrite them in the single block, and create anchor links like sample.site/#My_First_H2_Title

I don't find a supported TOC plugin with WPML/Polylang compatibility and RankMath integration. RankMath actually suggests LuckyWP Table of content and it works well, but there is no more update since WP ver. 5.5.5. and checking other LuckyWP plugins, they are no more updated since a year and no more answers to support requests. I'm therefore worried that earlier or later it will stop working with ongoing Wordpress updates. There are some plugins offering TOC blocks, but not multilingual not with the possbility to configure the title level (h2,h3,...) to show for single post. 

![TOC](https://user-images.githubusercontent.com/45165719/129961389-78a54516-189b-4204-8534-c1fcdf078070.jpg)

**Comment by JeanPaiva** [comment]
@romspielplatz we are going to discuss this for the next version, any updates we will post here. Thank you.

**Comment by JeanPaiva** [comment]
At this given time we don't have plans for a table of contents block.
