### ISSUE TITLE
GenerateBlocks and Blocksy Theme blocks spacing issue

### ISSUE THREAD

**Issue by BeholdPL** [tomusborne/generateblocks#1005]
While using GenerateBlocks with Blocksy Theme, there is a conflict between theme and GB in margins values. In editor, blocks margins are no visually unified with front, and vice versa. I know that Blocksy Theme team wants to fix that problem, but they need your cooperation - is there any chance to get this done, for users? It's important for those who are using this theme with your plugin.

**Comment by diggeddy** [comment]
This would require theme specific integrations which is not something we are willing to do.
Closing this as no fix available. But we will review increasing CSS specificity using additional hooks that will resolve this and other similar issues for users.
