### ISSUE TITLE
Query Loop: Ability to edit paginated URL

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#1015]
Received a couple of requests to add the ability to edit paginated URLs for query loop blocks.

References:
https://generate.support/topic/query-string-in-url-of-paginated-pages/
https://wordpress.org/support/topic/strip-parameter-from-paginated-url-query-loop/

**Comment by diggeddy** [comment]
Closing as this would be covered here
https://github.com/tomusborne/generateblocks/issues/1002
