### ISSUE TITLE
QoL - At a glance block Setting summary / key

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1040]
### Description
Look at methods to provide `at a glance` summary of block settings.
Whether this be a summary of styles or icons/keys to identify specific block functions are active.

This is a placeholder for ideas

**Comment by JeanPaiva** [comment]
Do you mean, like an indication of the active attributes?

<img width="122" alt="Screenshot 2023-06-12 at 11 06 15" src="https://github.com/tomusborne/generateblocks/assets/7506830/123d6abd-fafa-4746-a11d-ce14407ff1e7">
 attributes?

**Comment by diggeddy** [comment]
Closing as GB 2.0 filter now allows you to hide empty styles .
