### ISSUE TITLE
Better Query Loop arg filtering

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#1048]
We need to implement a better way to implement our `` filter so that we can target specific Query Loops.

Right now we suggest that people add a custom class to the "Grid" block inside the Query Loop, and then check for that class when using the filter.

However, this is less than ideal as the Grid block won't always be there, and it requires you to add the same class to the pagination button blocks as well: https://generate.support/topic/query-loop-pagination-issues-page-numbers-do-not-update-with-custom-filtering/page/2/#post-20138

**Comment by diggeddy** [comment]
Closing as GB 2.0 now handles this at the new Query block level
