### ISSUE TITLE
Add to container - toolbar option disappears if a GB image block is one of the selected blocks to wrap 1.8.0-alpha-1

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#1054]
Testing out the new container wrap feature I've found if a GB image block is present when multiple GB blocks are selected to wrap the option disappears from the toolbar. If you select the image on its own the toolbar option is available, so it seems it is when multiple blocks are selected to wrap and one is a GB image it doesn't show.

**Comment by eastriverstudio** [comment]
Update - actually for me it seems to be anytime there's more than one type of GB block selected at once. Selecting mulitple headlines works fine but selecting a headline and a GB image or a headline and button doesn't show the add to container option. I totally appreciate there would have to be some limitations for other core or third party blocks not being supported, but I would have thought multi selecting any GB blocks should work?

**Comment by tomusborne** [comment]
Hey @eastriverstudio, this is unfortunately a limitation inside Gutenberg itself. It doesn't allow us to insert toolbar items if more than one type of block is selected at the same time.

**Comment by eastriverstudio** [comment]
@tomusborne OK thanks for letting me know. That's a shame the block editor has that limitation currently, but I see why given the amount of potential blocks to support. Hopefully it is something that will be supported in a future version.

**Comment by diggeddy** [comment]
Closing this, in favour of new duplicate:

https://github.com/tomusborne/generateblocks/issues/1120
