### ISSUE TITLE
Spacing - Tabbing through new field layout does not follow order of fields 1.8.0-alpha.1

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#1065]
When entering unlinked padding and margin values it is helpful to be able to tab through each field in order to enter values more quickly rather than have to click on each. This works in part, but with the new layout the left field is now the last field, so if you try to enter a left value first (which I often do out of habit) and try to tab to next it jumps to the panel below it which I wouldn't expect.

I personally feel the left field should be the second in tab order, not the last, so the spacing fields can always be tabbed through in the correct order.

Thanks

**Comment by tomusborne** [comment]
Right now they follow the CSS order (top, right, bottom, left). However, I think I agree that they should follow their visual order as you're describing.

Will take a look. Thanks!
