### ISSUE TITLE
Typography - Font sizing inconsistencies between editor and frontend using new units in 1.8.0-alpha.1

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#1069]
Not sure if this is GB or more of a GP issue as it relates mainly to using rem units and setting default sizes on the root element. 

I've noticed playing around with rem and clamp functions in the new 1.8.0 typography controls there's some inconsistencies between the editor and frontend font sizes. This looks to be caused and is more noticeable if I set a non standard size value for the root html element in GP's typography manager for say 20px, this doesn't seem to get added to the Editor like other typography styles set in GP, so the sizing looks smaller in the editor than it does on the frontend. 

With rem sizing and clamp values (which could use rem) now possible, ideally the root sizing needs to be consistent between theme and GB/editor so the typography sizing is accruate between the two.

Thanks

**Comment by tomusborne** [comment]
This has been fixed in GP 3.4.0 (getting ready for alpha): https://github.com/tomusborne/generatepress/pull/542

Thanks!

**Comment by eastriverstudio** [comment]
@tomusborne great news, glad to hear you guys are already on it :)
