### ISSUE TITLE
Image block - add aspect-ratio property

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#1072]
The aspect ratio css property is now well supported and I think it would be a helpful addition to the image block's settings to make sure images can stay in a desired proportion when the screen size is reduced or enlarged. 

Given there's quite a few different ratios that could be used I'm thinking maybe a few common ratios could be predefined for selection and then we could have the option to manually type in a less common one.

For reference: https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

Thanks

**Comment by diggeddy** [comment]
Included in project. Closed by:
#1140
