### ISSUE TITLE
Exclude Button block from GP's Underline Links - On hover option

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#1073]
Currently, the Button block is excluded when GP's Underline Links option is set to **Always**:
https://www.screencast.com/t/NNo2T4cYtBzk

However, the underline is not excluded when using the **On hover** option:
https://www.screencast.com/t/gCwP62bLHNjs

The Underline Links option should always exclude GB button block.

**Comment by diggeddy** [comment]
Closing as future update to include Text Decoration options in Typography setting.
