### ISSUE TITLE
Allow for keyboard up/down nudges when setting values

### ISSUE THREAD

**Issue by codysmith44** [tomusborne/generateblocks#1077]
### Description

I wasn't sure how else to label this, but I'd love to be able to "nudge" values. Core blocks allow this...just use the up/down key on the keyboard to increment values +/- 1, or shift-up/shift-down to increment in values of 10.

Bonus points to allow going into the "negative" for negative/overlapping margins, etc. (Default blocks don't allow negative nudges.)

Could this be implemented in GenerateBlocks?

**Comment by Calvin-Susan** [comment]
> ### Description
> I wasn't sure how else to label this, but I'd love to be able to "nudge" values. Core blocks allow this...just use the up/down key on the keyboard to increment values +/- 1, or shift-up/shift-down to increment in values of 10.
> 
> Bonus points to allow going into the "negative" for negative/overlapping margins, etc. (Default blocks don't allow negative nudges.)
> 
> Could this be implemented in GenerateBlocks?

+1. I'm constantly trying to bump up values with my arrows only to realize it doesn't work. In any number field, I think this should be implemented.

**Comment by diggeddy** [comment]
Closing for newer dupe here:
https://github.com/tomusborne/generateblocks/issues/1135
