### ISSUE TITLE
Create Product Long Description Patterns

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generateblocks#1079]
With the new update on Woocommerce 7.9 which is still a fresh feature, it looks that you can add generateblocks patterns.

I suggest that it would be cool and very helpfull the GenerateBlocks Patterns and Generatepress Site Library to include new layouts for product pages.

Mostly for Generateblocks to be a tab "Woocommerce" which includes this kind of patterns.

**Comment by diggeddy** [comment]
This has been added to pattern review issue in GB Pro. Closing here.
If there are any examples you want to share please do so below.
