### ISSUE TITLE
Keyboard shortcut not workinh for GB heading block

### ISSUE THREAD

**Issue by danstramer** [tomusborne/generateblocks#1091]
### Description
The core editor has a set of keyboard shotcuts. one of them is `Shift + Alt + 1-6` to convert a paragraph block into a heading of level 1-6.
This shortcut does not work when in the block preferences the core heading block is disabled, since we want to use only the GB heading block.

### Steps for testing
1. Add a paragraph
2. Disable the core heading block
3. Click the keyboard shortcut to convert into a heading block `Shift + Alt + 1-6` - nothing happens
4. Enable back the core heading block
5. Click the keyboard shortcut - the paragraph is converted

#### References:

![image](https://github.com/tomusborne/generateblocks/assets/1552408/325c50b8-2cda-425f-8c44-0faa932b0305)

-----

**Comment by diggeddy** [comment]
The shortcuts are tied to the core Paragraph and Heading blocks, and this behaviour cannot be changed.

Can't fix.

**Comment by danstramer** [comment]
Thanks for your reply
