### ISSUE TITLE
GP Dynamic Data Gaps

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1094]
### Description
Expand GenerateBlocks dynamic data options to include the options exclusively available to GP Dynamic Data options.
Successful completion will allow us to deprecate GP Dynamic Data options.

**Data Sources**

Add:

- [x] Next Post
- [x] Previous Post
- [x] In same term toggle

**Content Sources**

***Title***
The Title content source displays only the Single Post Content Title.
It should conditionally display:

- [x] Archive Title [ Headline, Button ] 
- [x] Search Results Title [ Headline, Button ] 
- [x] Blog Title* [ Headline, Button ] 

*The blog page title GP doesn't currently handle.
We should take the opportunity to fix thia
Consider: `get_the_title( get_option('page_for_posts', true) );`

***Add content sources for archives***
Blocks to be included  as noted, and conditions for front end display:

- [x] Term Description [ Headline ]  - Archive only
- [x] Term Meta [ Headline, Button, Image ] - Archives only
- [x] Author Description [ Headline ] 
- [x] Author Meta [ Headline, Button, Image ] 

**Link Sources**
Should be present on ALL blocks that have a link source.
Consider GB Pro Container Links

- [ ] Next Page of Posts
- [ ] Previous Page of Posts
- [ ] Next Post
- [ ] Previous Post
- [ ] Term Meta
- [ ] Author Meta

**General All Text Content Source**
Keep it simple and add text fields to add:

- [ ] Before and After content fields [ Headline, Button ]

**Comment by Calvin-Susan** [comment]
I put in a separate issue, but the author meta is not available on the image block — would love to include that as well (so we could pull in custom author photos via custom fields).

**Comment by diggeddy** [comment]
Closing as refactors completed in GB 2.0
