### ISSUE TITLE
Dynamic Image Source - Author Meta

### ISSUE THREAD

**Issue by Calvin-Susan** [tomusborne/generateblocks#1097]
### Description

I'm trying to pull in a dynamic image from the author meta, but it doesn't seem like that's an option with the image block (I'm editing an author archive Loop Template).

I see "Author Meta" as an option under the link source, but not under the image source.

Is there a reason for this? Or should I be doing this another way?

To understand what I'm trying to achieve, I just want to be able to pull in an image for my author that is NOT through Gravitar (and I don't want to install a separate plugin — just use a custom field)

**Comment by diggeddy** [comment]
Closing as covered here:
https://github.com/tomusborne/generateblocks/issues/1094
