### ISSUE TITLE
[GenerateBlocks query loop] Adjust number of posts for tablet and mobile

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#1116]
It would be great if we could set number of posts per responsive view. For example, we could show fewer posts on mobile view to save space.

**Reference**
https://generate.support/topic/generateblocks-query-loop-adjust-number-of-posts-for-tablet-and-mobile/

**Comment by diggeddy** [comment]
Posts could only. be hidden using CSS for responsive screen sizes.
And would require `nth-child` selectors which is not currently possible. If that becomes possible then this feature would be possible.
