### ISSUE TITLE
Transforming from core/paragraph to generateblocks/headline

### ISSUE THREAD

**Issue by tdrayson** [tomusborne/generateblocks#1117]
### Description
Currently, if I start writing with the core paragraph block and then transform it to the GB headline block, it sets the heading level to h2.

I saw there was a request added last year to retain the heading level from core/heading block.

It would be nice if you could do the same for the core/paragraph block

#### References:
[[https://github.com/tomusborne/generateblocks/issues/635]](https://github.com/tomusborne/generateblocks/issues/635)

-----

**Comment by Calvin-Susan** [comment]
Same! That would be a HUGE timesaver!

I tried getting rid of the default paragraph block, but then when you copy/paste text in, things go haywire 😅

**Comment by slomeli79** [comment]
Agree this would be helpful. It's currently a workflow speed bump.

**Comment by ifrountas** [comment]
Also me came here for the same thing 😊

**Comment by eastriverstudio** [comment]
Yes please, it is one of my main frustrations uisng the headline frequently for parapgraph copy which I personally like to do because it has more controls than the core block.
