### ISSUE TITLE
Block labels for all blocks

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#1118]
All GB blocks apart from the containers should have block labels as well, it would help with the labeling during the design process.

**Comment by diggeddy** [comment]
Headline Blocks display excerpt of text
Buttons blocks show buttons label
Image Blocks show Alt Tag or Title Tag or Filename based on availability of data

This is the intended behaviour. And today this won't be changed.
We will review once WP adds block labels in core.
