### ISSUE TITLE
Mixed Units for Padding

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#112]
Option to select different Units ( Px or % or .. ) for each individual padding field would help with managing responsive sizing of container blocks.

eg. Top and Bottom: 5%, Left and Right: 40px;

A good reference is the GP Header Element where those options are available.

**Comment by JeanPaiva** [comment]
It's doable in my opinion but would require a big UI refactoring for the spacing attributes. It the not an easy task at all, but might be really useful as you mentioned.

**Comment by JeanPaiva** [comment]
duplication from https://github.com/tomusborne/generateblocks/issues/153
