### ISSUE TITLE
Add to Container for multiple selected blocks

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#1120]
It would be nice to be able to add a container around multiple selected block instead of the selected one!

**Comment by diggeddy** [comment]
You can Add to Container multiple blocks of the same type eg. all  Buttons or Headlines.
Mixed block types is not possible due to a limitation in the block editor.

See comment [here](https://github.com/tomusborne/generateblocks/issues/1054#issuecomment-1602851124)
