### ISSUE TITLE
Add aspect-ratio property to inspector controls

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1140]
Add `aspect-ratio` to:

All Blocks > Sizing Panel.
Image Blocks > Block Settings panel.

The field should accept: `auto` `numbers` `\` and `decimals` and mixed content.

```
aspect-ratio: 1;
aspect-ratio: 1 / 1;
aspect-ratio: 0.5;
aspect-ratio: auto 3/4;
aspect-ratio: 9/6 auto;
```

Advice notice:
At least one of the box's sizes needs to be automatic in order for aspect-ratio to have any effect. If neither the width nor height is an automatic size, then the provided aspect ratio has no effect on the box's preferred sizes.

For reference:
https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

This closes: 
https://github.com/tomusborne/generateblocks/issues/1072

**Comment by masteradhoc** [comment]
@diggeddy this is available already in the native wordpress image block. Would be great to get this into the generateblocks one as well to combine with other GB Image Block Features. Any plans?

![image](https://github.com/user-attachments/assets/f60284bf-14d1-46ea-b1fc-61fa1aeff110)

**Comment by diggeddy** [comment]
Completed in 2.0
