### ISSUE TITLE
Insert from the new Pattern Library Preview hangs

### ISSUE THREAD

**Issue by daveit** [tomusborne/generateblocks#1199]
### Description
Inserting a pattern library from the thumbnail view works fine, but clicking Insert from the preview hangs

### Steps to reproduce
1. 
I tested 3 or 4 times with both free and pro patterns and the issue happened at all times
#### Expected behavior
Pattern Should be inserted

#### Actual behavior
Button animates, but never inserts the pattern

#### References: 
not required
-----

**Comment by tomusborne** [comment]
Hey @daveit - thanks for testing!

I'm not able to reproduce on my end. Are there any console errors if you right click + Inspect the page, and look in the "Console" tab?

**Comment by daveit** [comment]
I'm getting two errors:
Uncaught TypeError: gform.addFilter is not a function
    <anonymous> https://perthwp.com/dev/wp-content/plugins/gravityformssurvey/js/gsurvey.min.js?ver=4.0.0:1
And:
Uncaught (in promise) TypeError: can't access property "find", a is undefined
    onClick https://perthwp.com/dev/wp-content/plugins/generateblocks-pro/dist/blocks.js?ver=d637ebd591ddd099a657:3
    onClick https://perthwp.com/dev/wp-content/plugins/generateblocks-pro/dist/blocks.js?ver=d637ebd591ddd099a657:3
    r https://perthwp.com/dev/wp-includes/js/dist/components.min.js?ver=c3a06857b0e51f435ccb:41
    Xa https://perthwp.com/dev/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
Last line repeated.
I'll test on a fresh install of WP, as this one I am testing on has had lots of plugins installed, deactivated and removed - I'll report back...

Further info - I deactivated the Gravity survey plugin, that error went away but the second one persisted!

**Comment by tomusborne** [comment]
Tough one to debug as it's not happening in my tests.

Can you do the following for me?

- Open dev tools
- Open the Network tab
- Click on "XHR" to filter the result
- Open the Pattern Library
- Find the `get_style_data` entry and open the response

Does it have a list of data with it?


https://github.com/tomusborne/generateblocks/assets/20714883/c2106fe9-743d-4437-af41-bffd97e31485

**Comment by daveit** [comment]
Sorry for delay - holiday weekend here in Perth, Australia!
OK So I went back into my play site, noticed it was still on the two Alpha 1's - upgraded to Alpha 2's and blow me down, the problem has gone away - go figure.
I did forget to add in case it is relevant, my play site was on 6.5 beta 3
Dave
