### ISSUE TITLE
'var' values is incorrectly displayed in the block styles panel & global styles panel.

### ISSUE THREAD

**Issue by vburdyko** [tomusborne/generateblocks#1204]
### Description
'var' values is incorrectly displayed in the block styles panel & global styles panel. Everything works fine in both backend and frontend; the bug only concerns the display of values in the block style editor.

### Steps to reproduce
1. Add the value var(--text-xl) for font-size.

#### Expected behavior
2. Font-size: var(--text-xl) for tablet & mobile.

#### Actual behavior
3. var(--t instead of var(--text-xl)

I'm using Version 1.9.0-alpha.2. However, this also applies to 1.8.0 version. The same issue is present in the GeneratePress Typography Editor.

-----

https://github.com/tomusborne/generateblocks/assets/45384805/ac6e8008-5224-43d3-88e7-a58363f109fb

**Comment by tomusborne** [comment]
@vburdyko I've been trying to reproduce this but I'm unable it. Is it still happening for you?


https://github.com/tomusborne/generateblocks/assets/20714883/ce923cdf-fd1d-4065-b29f-f9782bf8b216

**Comment by vburdyko** [comment]
@tomusborne Hi Tom, it was fixed in one of the recent betas.Thanks.

**Comment by vburdyko** [comment]
@tomusborne Hi Tom, the issue has returned again.
GenerateBlocks 1.9.1
GenerateBlocks 1.7.0

https://github.com/tomusborne/generateblocks/assets/45384805/4490872c-9ae4-41a0-a619-167766bc17f1

The same issue is present in the GeneratePress Typography Editor as well.
https://github.com/tomusborne/generateblocks/assets/45384805/c2d11713-1198-4159-a73b-c46d9f39d375

**Comment by vburdyko** [comment]
@iansvo @tomusborne  The issue only arises when using the word 'text' in the variable (for example var(--text-m) becomes var(--t ), other words are displayed correctly.
