### ISSUE TITLE
Headline Block has  `margin: 0` in EDITOR only responsive views 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1205]
### Description
Only in the editor responsive views. This CSS is applied:

`
.gb-headline {
    margin: 0;
}
`
<img width="1128" alt="Screenshot 2024-03-04 at 15 52 16" src="https://github.com/tomusborne/generateblocks/assets/30641942/cad5f1ca-4648-4419-ad8a-227e6f417e67">

Which removes any inherited H2 margins

**Comment by Calvin-Susan** [comment]
I can confirm I'm experiencing this on my end too. Sent it to Tom in a video this morning 😅
