### ISSUE TITLE
Change HTML tag to OL, UL, and LI

### ISSUE THREAD

**Issue by Calvin-Susan** [tomusborne/generateblocks#1206]
It would be great to be able to edit the HTML tag to make any block a `<ol>`, `<ul>`, or `<li>` so we can produce more semantic HTML.

**Comment by tdrayson** [comment]
+1 for this!

**Comment by jakewoods-io** [comment]
This would be awesome. +1

**Comment by eastriverstudio** [comment]
@Calvin-Susan for reference there’s already a feature request open for this: https://github.com/tomusborne/generateblocks/issues/772

**Comment by diggeddy** [comment]
Closed as duplicate. And tags are now possible in GN 2.0
