### ISSUE TITLE
grid-row in layout settings of a Global Style

### ISSUE THREAD

**Issue by wpgaurav** [tomusborne/generateblocks#1210]
GenerateBlocks 1.9.0.alpha.2
### Description
Sorry if this was reported already, but don't you think that there should also be an option to add `grid-row` in the layout settings just as there is grid-column?

![Edit Page “Gaurav Tiwari” ‹ Gaurav Tiwari — WordPress 2024-03-004195](https://github.com/tomusborne/generateblocks/assets/3599257/1c1245aa-0c10-4ca2-a630-706e4878f647)

**Comment by tomusborne** [comment]
This has been added in the next GBP alpha.

Thanks!
