### ISSUE TITLE
Incorrect display of selected colors in the Style Editor for box-shadow

### ISSUE THREAD

**Issue by vburdyko** [tomusborne/generateblocks#1215]
Incorrect display of selected colors in the Style Editor for box-shadow. However, correct values are saved in the styles.

### Steps to reproduce
In the video, I use the same box-shadow colors for both the main and hover states of the element. After changing the color in the main state, the hover color also changes (00:17). However, the correct colors are displayed in the editor window.

https://github.com/tomusborne/generateblocks/assets/45384805/1aa4d409-91c0-46d2-87d9-6ce752d6cfad

**Comment by iansvo** [comment]
Fixed in: https://github.com/tomusborne/generateblocks-pro/pull/561
