### ISSUE TITLE
Beta Version Updates

### ISSUE THREAD

**Issue by wpgaurav** [tomusborne/generateblocks#1224]
For GenerateBlocks, only Pro versions' updates are shown in WordPress updates and not the core version.

![WordPress Updates ‹ Gaurav Tiwari — WordPress 2024-04-004329](https://github.com/tomusborne/generateblocks/assets/3599257/59b6a369-bfd5-424c-9bd0-5898a6ed6d06)

I mean, I can see GenerateBlocks Pro RC update but not GenerateBlocks RC update this time. I'll have to manually update it from my GenerateBlocks account.

Is this intentional?

**Comment by tomusborne** [comment]
Yes, this is intentional. WordPress.org (where the GB core version is hosted) doesn't support alpha/beta versions like this, unfortunately.
