### ISSUE TITLE
Feature Request: Expanded Variable Support in GenerateBlocks

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generateblocks#1230]
I've been using the latest version of your plugin and I'm thoroughly enjoying the extensive capabilities it offers with variables. The flexibility to work with variables has greatly enhanced my workflow, making customization more streamlined and efficient.

However, I've noticed that the application of variables is somewhat limited in several fields. For example, settings like font size and CSS effects (like shadow) do not currently support variable usage. This restriction limits the potential for full customization and dynamic styling based on variable inputs.

![image](https://github.com/tomusborne/generateblocks/assets/9355398/a67eda81-6dee-4992-bfbf-e3e1d2cab3b6)

![image](https://github.com/tomusborne/generateblocks/assets/9355398/3892c9cc-7a81-4506-9a7b-0a01a379173d)

The benefits of variable flexibility, I believe, are clear and need no further justification.

As a user, I would greatly appreciate the freedom to decide whether to use variables or rely on the standard editor options across all settings within GenerateBlocks. Extending variable support would not only cater to advanced users but also maintain simplicity for those who prefer the default settings.

Thank you for considering this enhancement.

**Comment by iansvo** [comment]
@SchneiderSam I'm pleased to report that you can _can_ in fact use CSS variables with each of those fields you've screenshotted! 

You'll need to click the three vertical dots and choose "Enter Custom Value", like so:


https://github.com/tomusborne/generateblocks/assets/11017412/69a1c74a-b2cf-4047-a3b7-70515dcfa7bb

Note: there's currently a bug with the box shadow values where it may error out if you try to do this. I have a PR in to fix them though so no worries we're on the case :)
