### ISSUE TITLE
Query Loop Orderby SLUG does not work on frontend

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1301]
### Description
Order by > Slug works in the editor but not on the front end.

To fix the user can add:

```
add_filter( 'generateblocks_query_loop_args', function( $query_args ) {
	if ( isset( $query_args['orderby'] ) && 'slug' === $query_args['orderby'] ) {
		$query_args['orderby'] = 'name';
	}

	return $query_args;
} );
```

So it seems our WP Query for the front end has the incorrect arg value

**Comment by diggeddy** [comment]
@iansvo this may have been fixed with your query args refactor right ?

**Comment by iansvo** [comment]
@diggeddy I see the problem, should be a very simple fix
