### ISSUE TITLE
GB 2.0 pre-alpha testing SVGs, Icons and Shapes

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1304]
### Shapes picker bug
You can only choose a shape when it is first added to a Container Block. In all other instances the picker shows the SVG Icons and not shapes.

### Shapes More Selector bug
Selecting the More selector option on a shape will break the block

https://github.com/user-attachments/assets/629f00fa-a998-41be-8aaa-d7b9169d9307

#### Shapes and Icon colors*
It's not intuitive to set the shape or icon color via the Typography panel. 
Future feature we should consider `fill` and `stroke` options too
Should we have a dedicated colors panel in these special instances ?

#### Shape position shortcut
Consider shortcut to set the shape position for  Top , Right, Bottom and Left of container

**Comment by tomusborne** [comment]
> You can only choose a shape when it is first added to a Container Block. In all other instances the picker shows the SVG Icons and not shapes.

Nice catch, and tricky to fix. Once the shape is added, it loses context as to what it is. Maybe the Icon Library needs to show all icons, categorized.

> Selecting the More selector option on a shape will break the block

Fixed.

> It's not intuitive to set the shape or icon color via the Typography panel.
> Future feature we should consider fill and stroke options too
> Should we have a dedicated colors panel in these special instances ?

We do have a color shortcut currently.

![shape-color](https://github.com/user-attachments/assets/8354a4ec-e2f5-40cf-8f50-419ea353478b)

Fill and stroke should probably happen. I wonder which section those should live in?

**Comment by diggeddy** [comment]
> Once the shape is added, it loses context as to what it is. Maybe the Icon Library needs to show all icons, categorized.

That would be simplest option. 

> We do have a color shortcut currently. 
Ah yes on the shape block, but theres no shortcut for a headline/button icon.

> Fill and stroke should probably happen. I wonder which section those should live in?
I think we may need a dedicated SVG panel in the long run ... something for deeper discussion.

**Comment by diggeddy** [comment]
Shapes have two separate size options.
In block settings you can set the `width` and `height` properties of the `svg` element
In styles settings you can set the `width` and `height` of the `span.gb-shape` wrapper element

Do we need to do this if we do not require legacy support ? Do we even need the wrapper ?

**Comment by diggeddy** [comment]
We could just style the wrapper for color and size.
It may mean keeping some hidden CSS for the svg size and currentColor 
Hmmm.... might be worth a play

**Comment by tomusborne** [comment]
Pretty simple to just do this:

https://github.com/user-attachments/assets/59b9c76b-6e2d-45a6-b284-6e7b0fafc16e

One step fewer the user has to take, but still have the ability to go back up to the main selector to style it.

**Comment by diggeddy** [comment]
Shape Block and Shape selector in container now throws an error:
<img width="1426" alt="Screenshot 2024-09-20 at 17 10 22" src="https://github.com/user-attachments/assets/a5fb77bb-7c9d-4e80-b42b-59bb0c15e292">
