### ISSUE TITLE
GB 2.0 pre-alpha testing Query Loop 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1310]
### Blank Template - improve UI/UX for adding pagination and no results block
Common support topic with current blocks is how to add pagination. This is less intuitive and less obvious.
The appender needs to be more obvious and that it has dependent blocks. 
Or we add options in toolbar and block settings to add these blocks.

### Pagination buttons throw error when Force page reload is disabled

<img width="1354" alt="Screenshot 2024-09-18 at 00 05 35" src="https://github.com/user-attachments/assets/9c68c90d-46bb-432c-9ac9-0b8826c709cb">

### Force page reload

Is this the right label and the right way around?
Alternative would be the option to: `Enable "AJAX" loading"

### Dynamic loading doesn't work correctly in a GP Block Element Loop Template

The Next / Previous buttons work.
But the Pagination buttons do not work until a Next or Previous has occurred 

https://github.com/user-attachments/assets/dc388440-1720-4ce5-af30-d2ee17a57b80

### Block selection only in first post

Coming from previous version, this UX is a little jarring. Particularly as there is no indicator or feedback on the blocks being unselectable. Is it possible to revert to current method of selecting blocks in any post?

**Comment by diggeddy** [comment]
Block Icons:

Page Numbers
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" context="list-view" class="gblocks-block-icon" aria-hidden="true" focusable="false">
    <path d="M4.376,14.313L5.851,14.313L5.851,10.101L4.578,11.075L4,10.304L6.198,8.627L7.046,8.627L7.046,14.313L8.492,14.313L8.492,15.373L4.376,15.373L4.376,14.313Z" style="fill-rule:nonzero;"/>
    <path d="M14.178,15.373L9.88,15.373L9.88,14.439C9.957,14.374 10.053,14.289 10.169,14.183C10.284,14.077 10.414,13.957 10.559,13.822C10.704,13.687 10.856,13.539 11.017,13.378C11.178,13.218 11.335,13.051 11.489,12.877C11.708,12.633 11.899,12.411 12.063,12.212C12.227,12.013 12.361,11.825 12.467,11.648C12.573,11.471 12.652,11.298 12.704,11.128C12.755,10.957 12.781,10.782 12.781,10.602C12.781,10.474 12.752,10.349 12.694,10.227C12.636,10.104 12.556,9.997 12.453,9.904C12.35,9.81 12.227,9.737 12.082,9.682C11.937,9.627 11.778,9.6 11.605,9.6C11.373,9.6 11.163,9.635 10.973,9.706C10.784,9.777 10.586,9.896 10.381,10.063L9.88,9.176C10.149,8.983 10.45,8.821 10.781,8.689C11.112,8.557 11.492,8.492 11.923,8.492C12.199,8.492 12.464,8.53 12.718,8.607C12.972,8.684 13.197,8.798 13.393,8.949C13.589,9.1 13.745,9.288 13.86,9.513C13.976,9.738 14.034,9.998 14.034,10.294C14.034,10.5 14.016,10.691 13.981,10.867C13.945,11.044 13.891,11.221 13.817,11.398C13.743,11.574 13.647,11.756 13.528,11.942C13.409,12.129 13.266,12.331 13.099,12.549C12.97,12.716 12.831,12.885 12.68,13.055C12.529,13.226 12.379,13.388 12.231,13.542C12.084,13.696 11.937,13.841 11.793,13.976C11.648,14.111 11.518,14.223 11.402,14.313L14.178,14.313L14.178,15.373Z" style="fill-rule:nonzero;"/>
    <path d="M17.311,14.448C17.523,14.448 17.717,14.421 17.894,14.366C18.071,14.312 18.222,14.235 18.347,14.135C18.472,14.035 18.57,13.92 18.641,13.788C18.712,13.656 18.747,13.513 18.747,13.359C18.747,13.166 18.707,13.004 18.627,12.872C18.546,12.741 18.435,12.636 18.294,12.559C18.153,12.482 17.982,12.427 17.783,12.395C17.584,12.363 17.369,12.347 17.137,12.347L16.598,12.347L16.598,11.663L18.217,9.687L15.778,9.687L15.778,8.627L19.711,8.627L19.711,9.504L18.014,11.441L18.236,11.441C18.461,11.441 18.68,11.48 18.892,11.557C19.104,11.634 19.292,11.749 19.455,11.904C19.619,12.058 19.751,12.251 19.851,12.482C19.95,12.713 20,12.98 20,13.282C20,13.648 19.924,13.969 19.773,14.246C19.622,14.522 19.423,14.755 19.176,14.945C18.929,15.134 18.644,15.276 18.323,15.369C18.002,15.462 17.671,15.508 17.33,15.508C17.041,15.508 16.752,15.483 16.463,15.431C16.173,15.38 15.894,15.3 15.624,15.19L15.961,14.149C16.019,14.182 16.098,14.214 16.198,14.246C16.297,14.278 16.41,14.31 16.535,14.342C16.66,14.374 16.789,14.4 16.92,14.419C17.052,14.439 17.182,14.448 17.311,14.448Z" style="fill-rule:nonzero;"/>
</svg>
```

No results

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" context="list-view" class="gblocks-block-icon" aria-hidden="true" focusable="false">
    <path d="M12,4C16.415,4 20,7.585 20,12C20,16.415 16.415,20 12,20C7.585,20 4,16.415 4,12C4,7.585 7.585,4 12,4ZM17.181,7.676L7.676,17.181C8.847,18.16 10.355,18.75 12,18.75C15.725,18.75 18.75,15.725 18.75,12C18.75,10.355 18.16,8.847 17.181,7.676ZM16.324,6.819C15.153,5.84 13.645,5.25 12,5.25C8.275,5.25 5.25,8.275 5.25,12C5.25,13.645 5.84,15.153 6.819,16.324L16.324,6.819Z"/>
</svg>
```

**Comment by tomusborne** [comment]
@diggeddy Been working on this.

> Blank Template - improve UI/UX for adding pagination and no results block

These blocks all use our standard block appended found in the Container block, so it should be more obvious.

> Pagination buttons throw error when Force page reload is disabled

This is fixed.

> Force page reload

This is fixed.

> Dynamic loading doesn't work correctly in a GP Block Element Loop Template

I'm not able to replicate it. Maybe one of the above fixed it. Can you still get this to happen?

> Block selection only in first post

This is surprisingly difficult if we want to maintain the HTML structure of query in the editor, which is necessary if we want our frontend CSS to work in the editor. Will continue to think on it.

**Comment by diggeddy** [comment]
All good to me.

Block selection on only first post is ok but it would be nice if there was some feedback when clicking on the other posts... not sure what but something to think about
