### ISSUE TITLE
GB Dynamic Data tags

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1342]
## Description
A list of the current dynamic data tags available in GB Free

#### Data Sources: 

- [x] Current Post
- [x] Post Type

#### Content Sources

- [x] Title
    - [x] single post
    - [x] archive titles ( GP Elements )
- [x] Excerpt
    - [x] Excerpt Length
    - [x] Default Read More
- [x] Post Date
    - [x] Date Type option: Published | Updated
    - [x] Replace with updated option
- [x] Post Meta
    - [x]  Post Meta Field
- [x] Comments Number
    - [x] No Comments Text
    - [x] Single Comment text
    - [x] Multiple Comments text
- [x] List of Terms
    - [x] Taxonomy
    - [x] Term Separator
- [x] Author Meta Field
    - [x] Meta Field
- [x] Author Email
- [x] Author Name
- [x] Author Nickname
- [x] Author Last Name

#### Link Sources

- [x] Single Post
- [x] Comments Area
- [x] Post Meta
- [x] Author Archives
- [x] Author Meta
- [x] Author Email

___

#### Content Sources
- [x] Archive Pagination
- [x] Single post pagination

___

#### Data Sources: 

- [x] Current Post
- [x] Post Type

#### Content Sources

- [x] Featured Image
- [x] Post Meta
    - [x] Meta field
- [x] Author Avatar

#### Link Sources: 
Single Image, Single Post, Comments Area, Post Meta, Author Archives, Author Meta, Author Email

___

#### Data Sources: 

- [x] Current Post
- [x] Post Type

#### (Content) Background Image Sources

- [x] Featured Image
- [x] Post Meta
     - [x] Meta Field
- [x] Author Avatar

#### Link Sources: 
None in Free

**Comment by iansvo** [comment]
@diggeddy Excerpt length can be handled using the trunc filter.
