### ISSUE TITLE
GB 2.0 Pre-alpha List view improvements

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1361]
### Description
Improve list view

- [x] Add support for core block Labels for list view.
- [x] Text and Headline blocks should show an excerpt of the block content
- [x] Container blocks default label should express their HTML tag. eg. `figure` `list` etc. 
- [ ] Container block show background image as thumbnail icon in list view ( similar to core Image block ).

**Comment by iansvo** [comment]
@diggeddy Some bad news here, the only way we can do the thumbnail is to make a PR for Gutenberg itself, which I have some code prepared for (very simple) but it won't be something we can do in 2.0.

**Comment by iansvo** [comment]
For now im going to close this since the other items are addressed.
