### ISSUE TITLE
GB 2.0 Pre-alpha Flex Column doesn't swap the align / justify icons.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1381]
### Description
In GB 1.0 blocks , the flex column layout would swap the alignment and justification icons. So they are representative of the visual layout:
 
<img width="277" alt="Screenshot 2024-10-18 at 00 21 29 1" src="https://github.com/user-attachments/assets/24895d25-cae3-4dc8-8dc7-a5128589fd51">

This is not the case in GB 2.0 which makes the icons confusing:

<img width="277" alt="Screenshot 2024-10-18 at 00 23 14" src="https://github.com/user-attachments/assets/99de5556-d33c-4cb4-a566-bbf55d56a41d">

Are we able to swap them based on the current blocks computed style for Local Block settings?
And what to do about Global Styles ?

**Comment by iansvo** [comment]
@diggeddy I think we can probably do this. I'll do a bit of exploration.

**Comment by diggeddy** [comment]
The alternative would be to drop the icons and just add the property values

**Comment by tomusborne** [comment]
Replaced these with just text.
