### ISSUE TITLE
GB 2.0 Pre-alpha Query Loop template selector is not responsive 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1385]
The query loop template selector doesn't work inside a narrow container

<img width="1435" alt="Screenshot 2024-10-21 at 15 45 33" src="https://github.com/user-attachments/assets/58849dc6-23a0-4bc7-bc06-9bfc25d2f43c">

**Comment by iansvo** [comment]
This appears to be a problem in the current production version also:

<img width="815" alt="image" src="https://github.com/user-attachments/assets/1d670a79-384c-4ec5-ae3e-33206f959a1d">

Here's an equivalent UX using only core blocks:

https://we.tl/t-ykuFClRnK6

So here, they open a modal and show a series of patterns. I think this is what we should do, but in a less janky manner than they do. We absolutely could do this and we could use it as a simple pattern we could reproduce for anything else either, as I imagine some other blocks might benefit from such a pattern.

**Comment by diggeddy** [comment]
I agree, using Patterns was on the cards before. 
I should have query patterns done tomorrow and ill do the free patterns at the same time,
