### ISSUE TITLE
GB 2.0 Pre-alpha Dynamic Data tag: Author Meta broken ?

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1386]
### Description
Selecting a DYNAMIC TAG of `Author Meta`
the `META KEY` select box returns no options. Should it not return a list of default meta fields ?

If I manually add a field eg. `display_name`
Which returns a tag of: `{author_meta key:display_name}`

This returns no Preview of the tag. So I assume it has not found the key.
And on post save the editor  throws an `Updating Failed` error.

**Comment by iansvo** [comment]
Simple fix here, just missing a few params for the filter

**Comment by iansvo** [comment]
Resolved in #1387
