### ISSUE TITLE
[GB 2.0 pre alpha] AT-RULES created in GBP are still available when GBP is deactivated

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#1421]
### Description
When AT-RULES are created in GBP, they seem to still be available when GBP is deactivated. In addition, the previously created AT-RULES cannot be deleted when GBP is not activated.

**Comment by tomusborne** [comment]
This is intended. Once an at-rule is created (or a nested rule), it now exists in the styles object, and therefore the system will read and parse it.

Deleting at-rules/nested rules is a pro-only feature, but simply removing any styles added to those selectors would in essence remove them.
