### ISSUE TITLE
GB 2.0 Shape Block Color does not apply

### ISSUE THREAD

**Issue by ifrountas** [tomusborne/generateblocks#1439]
### Description
In the shape block the color does not apply to the SVG. I think we should apply fill css property instead of color to make it work

### Steps to reproduce
1.  Just add an SVG like this which has no color by default

`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1600" viewBox="0 0 1200 1200"><path d="M808.08 190.8a42.6 42.6 0 0 0-62.836-2.839 42.575 42.575 0 0 0-12.434 32.047 42.6 42.6 0 0 0 15.27 30.793l306.12 306.48H42.4a42.709 42.709 0 0 0-35.105 21.957 42.735 42.735 0 0 0 0 41.406A42.726 42.726 0 0 0 42.4 642.601h1011.8l-306.6 306.12a43.437 43.437 0 0 0 0 60 42.358 42.358 0 0 0 30 12.457 42.365 42.365 0 0 0 30-12.457l379.2-379.2a41.645 41.645 0 0 0 0-60z"/></svg>`

2. Apply any color

#### Expected behavior
The SVG should take the given color

#### Actual behavior
The SVG will not take the given color

Also see this image https://capture.dropbox.com/DQuHCvK5nPQvugCL

#### References: 
...

-----

**Comment by iansvo** [comment]
@tomusborne I have a PR in progress for this, should be available tomorrow. We're going to need to add in a few extra controls in addition to `fill`. I'm thinking we need a new SVG panel that can go below media to hold these, as all of these properties only apply to SVG elements. 

@diggeddy That said, we're going to need a new icon for this panel. Do you want to try and whip one up so I can include it in my PR? I am just using the Media Icon for now.

**Comment by diggeddy** [comment]
We recommend that the SVG HTML Contains a: `fill="currentColor"` attribute, which is the well established method of most popular icon libraries and what we use in the GP Icons and Shapes.

An example:

```
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1600" viewBox="0 0 1200 1200" fill="currentColor" ><path d="M808.08 190.8a42.6 42.6 0 0 0-62.836-2.839 42.575 42.575 0 0 0-12.434 32.047 42.6 42.6 0 0 0 15.27 30.793l306.12 306.48H42.4a42.709 42.709 0 0 0-35.105 21.957 42.735 42.735 0 0 0 0 41.406A42.726 42.726 0 0 0 42.4 642.601h1011.8l-306.6 306.12a43.437 43.437 0 0 0 0 60 42.358 42.358 0 0 0 30 12.457 42.365 42.365 0 0 0 30-12.457l379.2-379.2a41.645 41.645 0 0 0 0-60z"></path></svg>
```

With the new modal option for adding custom SVGs, the process of adding that attribute is quite easy.

Note: SVGS may can contain code such as style, classes, id, def attributes that will override any GB or CSS styles. So the end user needs to have some knowledge of SVGs when it comes to adding Custom code.

Moving forward we can add the `fill` and `stroke` properties to the GB Styles object.
Closing this in preference of the mentioned feature request.
