### ISSUE TITLE
Add dynamic tag options for Image ALT Tag Field property

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1442]
### Description
Dynamic tag options for Image ALT Tags is necessary to support Dynamic Images.
Give users a choice of the available media attachment meta including. ALT Tag, Caption, Title and Description.

It would be nice to add the ALT Tag option by default when selecting a Dynamic Image.

This dynamic tag could ,presumably, be used in other Attribute Fields in GB Pro.

**Comment by tomusborne** [comment]
Right now you can do this for any kind of post meta, depending on how you've set up the return (to include these fields or not).

So it seems like the only thing we're missing is the ability to get more fields from a featured image, correct?

For this particular tag, perhaps it makes sense to ditch the current tags:

```
{{featured_image_url}}
{{featured_image_id}}
```

And go with something like: `{{featured_image key:url}}`

This would allow us to get other fields from the featured image without adding too many featured image related tags to the list.
