### ISSUE TITLE
Looper and Loop Item blocks can be deleted but not added back

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1444]
### Description
The Looper and Loop item blocks should be locked by default to reduce the risk of accidental deletion.
We should also consider a toolbar option to add the blocks back if they have been deleted.

**Comment by iansvo** [comment]
@diggeddy Looks like the looper should be able to support allowedBlocks but something about the preview setup is making it not work. Def something we should fix for 2.0.
