### ISSUE TITLE
Styles do no apply to multiple selected blocks and only the last one gets styled

### ISSUE THREAD

**Issue by Kovas** [tomusborne/generateblocks#1446]
### Description
When I select multiple blocks and change their styles, they do not appear correctly on the frontend.

### Steps to reproduce
1.  Select multiple containers.
2.  Change the background color.

#### Expected behavior
All containers have the same background color.

#### Actual behavior
Containers change color in the editor, but only the last one gets styles applied on the frontend.

**Comment by tomusborne** [comment]
Thanks for reporting this! Should be fixed in the next release.
