### ISSUE TITLE
GB 2.0 Transform causes error

### ISSUE THREAD

**Issue by njwgh** [tomusborne/generateblocks#1457]
### Description
Tying to transform version 1 block to version 2 block causes error
I have GP premium 2.5.0 and GB 2.0 alpha.1 free version

### Steps to reproduce
1.  With a version 1 block (I have tried headline and container) click as shown
![transform](https://github.com/user-attachments/assets/1712e8c4-e128-4f4f-a74b-518163ff2f13)

2. as you move your cursor down the list when your cursor **hovers** over a GB block then you get this error

![transform-error](https://github.com/user-attachments/assets/3aa6dc7d-51b0-4681-8806-ca43b9f3afc2)

3. If you choose any non-GB block then it works OK

#### Expected behavior
Should be able to choose a GB block

#### Actual behavior
Get an error

#### References: 
...

-----

**Comment by tomusborne** [comment]
Thanks for the report! What versions of the following are you using?:

- WordPress
- GenerateBlocks Pro (if any)
- GeneratePress Theme

**Comment by njwgh** [comment]
WordPress 6.6.2
No GenerateBlocks Pro
GeneratePress Theme 3.5.1

**Comment by njwgh** [comment]
I checked the console and can see this error:

![transform-error](https://github.com/user-attachments/assets/d2e4ce4c-68d4-41b3-b9d2-852399db800f)
