### ISSUE TITLE
Dynamic Tag - Key field submit button should be contextual Add / Update

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1458]
### Description
When editing an existing Dynamic Tag Meta Key, the submit button should read update.
The button should also be enabled for any edits. Currently it only updates if there is an addition made but not a deletion.

https://github.com/user-attachments/assets/dcdf969c-f203-4dfc-9e65-760acace248c

**Comment by iansvo** [comment]
@diggeddy I'm unable to replicate this in the latest version. I believe I fixed this as part of the alpha 2 stuff as part of another PR.

**Comment by diggeddy** [comment]
@iansvo  What about the button label ? 
It always reads `add` even when you're making an edit
