### ISSUE TITLE
Add Fill and Stroke properties to the More styles option.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1459]
### Description
Users how need more control over their SVGs colors would benefit from the `fill` and `stroke` color properties.
For now we can add them to the More styles panel.
We  can add a dedicated SVG panel when more properties are added.

This will help with #1439

**Comment by ifrountas** [comment]
@diggeddy That sounds good. A lower level approach is just add automatically the attribute `fill="currentColor"` in case the SVG dont have it already. This would fix the most issues for now.
