### ISSUE TITLE
Errors when adding blocks.

### ISSUE THREAD

**Issue by spin80** [tomusborne/generateblocks#1461]
### Description
When I try to add text blocks, I encounter this error. I’ve tested it on several different WordPress installations, and sometimes I was able to add a text block, but the error would appear when I tried to add dynamic data. You can see what happens in the video. It’s the latest and clean version of WordPress. The only plugin installed is GenerateBlocks 2.0 (free version).

### Steps to reproduce
https://komododecks.com/recordings/JdLz4lIDeeaEG0kQiwmD?uploadId=published

-----

**Comment by tomusborne** [comment]
Thanks for the report, @spin80!

This is due to using `http` over `https`. We've fixed this in alpha.2, which is scheduled for tomorrow.
