### ISSUE TITLE
Full Width and Wide Width Alignment options. 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1463]
### Description
GB 2.0 does not, currently, have the core Full and Wide Width options.
This needs to be addressed as they are a must for Block Based themes.

Could we:

a) display them if Theme is a Block Theme
b) provide GenerateBlocks > Settings option to enable / disable them

**Comment by iansvo** [comment]
I 100% agree. I think we can't just pretend those things don't exist, they're a core aspect of the way the editor works, etc. Making it simple to have them fuck off __if desired_ is definitely a great idea. 

Besides, all it does to the actual block is add a class. Seems pretty safe and smart.

**Comment by tomusborne** [comment]
Couple of things to consider here.

1. Do we simply add support for it, and allow core to insert the UI into the block toolbar?
2. Do we add an option for it, or simply a filter? For example, GeneratePress could use the filter to turn off this functionality when its in use, as there as much better ways to achieve these layouts.

**Comment by diggeddy** [comment]
Gut feeling after mulling it over today... 
Put them in the sidebar settings like in 1.0 had them
They should go under Settings as they just add the class... but is that exposing them too much ?

Add a bigger notice re: its Theme requirements. If GP is installed we can link to your docs for full width pages.
Add a filter to get rid of them if users want to.
