### ISSUE TITLE
GB 2.0 Query Block - Post Query item missing `post_class` 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1477]
### Description
GB 1.0 Query Loop Post Template would return the core `post_class` in the block classes attribute.
This is not the case in GB 2.0 which is a regression.

This should be available in 2.0.
It would be good to make this filterable, perhaps in the future it could be a Dynamic Tag.

**Comment by tomusborne** [comment]
This is a weird one.

@iansvo The code is there to do this in the Loop Item render method, but it's like the Loop Item is being rendered without using its render method?
