### ISSUE TITLE
2.0 Query Block - nesting bug

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1486]
### Description

It is possible to insert a block inside the Looper Block. But doing so breaks the looper and not Query Items are output.

<img width="352" alt="Screenshot 2024-11-14 at 21 29 29" src="https://github.com/user-attachments/assets/f1728b72-62e6-493f-8516-732e9a869cdb">

It is however NOT possible to insert a block directly inside the Query block. And this poses a separate UX issue regarding a conditional display of elements based on the query results. Separate issue to be raised.

**Comment by tomusborne** [comment]
How are you inserting a block inside the Looper? Drag and drop? If so, we can "lock" it, but users can easily unlock it.

It should be possible to add multiple blocks inside of the Looper if you really want to without it removing the loop item. So that's a bug that needs fixing for sure.
