### ISSUE TITLE
GB 2.0 Dynamic Tag Modified date -  Required to render does not work

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1505]
### Description
GB 1.0 Dynamic data has option to display Modified Date or fallback to the Published Date so only the latest date can be displayed.

**Comment by tomusborne** [comment]
The `Modified Date` should fallback to the published date if it hasn't been modified. So if someone wants to output the modified date ever, they should go with that tag. Otherwise, the published date will only ever show the date it was published.

Is that not what's happening on your end?

**Comment by diggeddy** [comment]
It is working as you describe. Bit of a misunderstanding on my part. I expected there to be an option to fallback as per 1.0.
However, the `Required to render` should provide the option when a user want to remove the date. But this option doesn't work for this tag.
This looks like a bug and updated issue to reflect that.

**Comment by tomusborne** [comment]
I think to do that we would need to short-circuit the function if the modified date equals the published date and not return anything.

**Comment by tomusborne** [comment]
@rsm0128 Yea, although I think it should be possible for the user to output only the modified date (and not the published date if it exists. For example:

`Date published: xx / Date modified: xx`

Working on a potential solution for this right now.

**Comment by rsm0128** [comment]
I think `{{modified_date}}` should be replaced with `{{published_date}}` in `/src/blocks/query/templates.js` file.
https://github.com/tomusborne/generateblocks/blob/release/2.0.0/src/blocks/query/templates.js#L124
https://github.com/tomusborne/generateblocks/blob/release/2.0.0/src/blocks/query/templates.js#L172
https://github.com/tomusborne/generateblocks/blob/release/2.0.0/src/blocks/query/templates.js#L222
https://github.com/tomusborne/generateblocks/blob/release/2.0.0/src/blocks/query/templates.js#L286
