### ISSUE TITLE
When looking up global style to clone, the editor crashes

### ISSUE THREAD

**Issue by taricco** [tomusborne/generateblocks#1506]
### Description
When looking up global style to clone, I get this error: "The editor has encountered an unexpected error." Along with the error, there are two buttons: "Copy Post Text" and "Copy Error." The error is pasted below.

### Steps to reproduce
1. Clone an existing button
2. Delete the global style for the cloned button
3. Add a new global style name and choose to clone an existing global style
4. When typing in the name of the global style to clone, the editor crashes
5. The same issue happens to various blocks, so it's a consistent issue
6. The new global style gets created, although it is blank (no styles configured)

#### Expected behavior
...

#### Actual behavior
...

#### References: 
Error
itemFilter@https://screendragon.bwb2b.com/wp-content/plugins/generateblocks-pro/dist/blocks.js?ver=edaa6ee3cfcd6e56b266:9:26461
onInputValueChange@https://screendragon.bwb2b.com/wp-content/plugins/generateblocks-pro/dist/components.js?ver=1.1.37:1:39851
7367/t/z/</</<@https://screendragon.bwb2b.com/wp-content/plugins/generateblocks-pro/dist/components.js?ver=1.1.37:1:8375
7367/t/z/</<@https://screendragon.bwb2b.com/wp-content/plugins/generateblocks-pro/dist/components.js?ver=1.1.37:1:8391
7367/t/z/</<@https://screendragon.bwb2b.com/wp-content/plugins/generateblocks-pro/dist/components.js?ver=1.1.37:1:8253
7367/t/z/<@https://screendragon.bwb2b.com/wp-content/plugins/generateblocks-pro/dist/components.js?ver=1.1.37:1:8500
ri@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:93198
Ss@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:113322
551/ws/<@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:112062
ws@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:112127
is@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:105883
Hl@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:46663
cs@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:106185
Le@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:15898
Qr@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:38533
qn@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:22950
$n@https://screendragon.bwb2b.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:22732

-----

**Comment by tomusborne** [comment]
@taricco Thanks for the report! This is fixed in the next release :)
