### ISSUE TITLE
GB 2.0.0 Beta.2 can't type space in Text block with button tag

### ISSUE THREAD

**Issue by njwgh** [tomusborne/generateblocks#1524]
### Description
GB 2.0,0 Beta.2 (free version)
can't type a space character in a text block with 'button' tag.
workarounds
If you type the text with space before selecting the 'button' tag then that works
If you add an icon to the button then after that you can type a space 

### Steps to reproduce
1. add a text block
2. select the 'button' tag
3. type some text in button. Hit space bar.

#### Expected behavior
Should add space

#### Actual behavior
no space is added

**Comment by tomusborne** [comment]
Thanks for reporting this!

I believe it's a core WordPress bug. We may need to get creative in our solution.
