### ISSUE TITLE
GB 2.0.0 Beta.2 no option to add link to text block with button tag

### ISSUE THREAD

**Issue by njwgh** [tomusborne/generateblocks#1525]
### Description
GB 2.0.0 Beta.2  (free version)
There is no option to add a link to a text block with a 'button' tag

### Steps to reproduce
1.  add a text block
2. choose 'button' tag

this is what it looks like

![gb-new-button-link](https://github.com/user-attachments/assets/ae18e922-bec4-4984-a0a7-71f7b2d749f0)

There is no 'link' icon

**Comment by tomusborne** [comment]
The `<button>` HTML element doesn't support an `href` like an `<a>` element does.

The `<button>` element is more for things like javascript interactions etc...
