### ISSUE TITLE
Unable to Enter Taxonomies in Query Block Taxonomies Parameter

### ISSUE THREAD

**Issue by alvindcaesar** [tomusborne/generateblocks#1528]
### Description:
The Taxonomies parameter field is not responding when attempting to pull the list of taxonomies. The dropdown selector is not appearing in the interface, and manual input of "categories" or "tags" yields no response.

### Environment:
WordPress 6.7
GenerateBlocks: v2.0.0-beta.2
GenerateBlocks Pro: v2.0.0-beta.2

**Comment by diggeddy** [comment]
I can replicate this bug

**Comment by iansvo** [comment]
Resolved in the above PR, super simple fix.
