### ISSUE TITLE
Spacing - Padding/Margin - mixed unit and auto support 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#153]
Add a MIXed units option that will allow the user to directly enter the value/unit into the field eg. `15%`.
For padding this will allow for mixing `PX/EM/%`
For margins this could also allow for the `auto` value to be added for Container ( not grid item container ), Headline and Buttons.

<img width="889" alt="Screenshot 2021-10-29 at 01 44 09" src="https://user-images.githubusercontent.com/30641942/139355038-d54b0e61-24aa-43e6-851f-57731f762538.png">

Auto Margins Left / Right on Contained Container Block will allow users to align containers:

<img width="779" alt="Screenshot 2021-10-29 at 01 53 29" src="https://user-images.githubusercontent.com/30641942/139355813-58b2708d-3746-4559-8db6-5552c5ac4747.png">

For Grid Item Containers auto margins would need to be applied to the `gb-grid-column` so would require a separate interface.  Which could be something as simple as an Horizontal Alignment option on the Grid Container.... will require some testing.

**Comment by eastriverstudio** [comment]
@diggeddy nice to see this improvement requested. I was only thinking the other day this is needed so nice to see you've done it already and I like the way you've proposed handling it and should give us even more control in the way things are aligned. A common example is I've quite often found myself wanting to align buttons to the bottom of grid container whilst everything else is flex-start, so being able to add auto margins should help there :)

**Comment by echase** [comment]
This is brilliant! I propose: 

1. Pencil icon UI (More compact than "mix"; represents "custom") 
2. Pass user input ~verbatim as CSS attribute -> allows var() and calc() functions as well as novel units

**Comment by diggeddy** [comment]
Completed in GenerateBlocks 1.8
