### ISSUE TITLE
GB2.0.0 Beta.2  google fonts not showing in block font choice

### ISSUE THREAD

**Issue by njwgh** [tomusborne/generateblocks#1530]
### Description
GB2.0.0 Beta.2  (free version)

If I try to choose a font family for any GB block then google fonts aren't in the list. This is what I see:

![ec-font-family-choise](https://github.com/user-attachments/assets/b8861668-df15-483b-a349-ff9446aaf43f)

This is for the new v2 blocks. Font choice is OK in existing v1 blocks

Prior to upgrading to GB2.0.0, I had the option 'disable google fonts' checked and was using the code from this page :
[https://docs.generateblocks.com/article/add-custom-fonts-to-font-family-dropdown-list/](https://docs.generateblocks.com/article/add-custom-fonts-to-font-family-dropdown-list/)
to show the Google fonts in the block font choice (based on the Google fonts I had chosen in typography font manager). But that is no longer working

This is what I have in Typography manager:

![ec-typography](https://github.com/user-attachments/assets/b182cf00-013b-49b6-ad0c-5175910a92fe)

I suspect there is some setting I'm missing, but would expect the functionality prior to GB2.0.0 upgrade to continue working

This is what the font-choice list looked like prior to upgrade:
![ec-font-family-choice](https://github.com/user-attachments/assets/6fc82054-d914-4764-bc63-784c61b1e46d)

OK I see after more Googling that there is a three-dot menu with the option to enter a custom value and that works if I type in 'Roboto' but not an ideal experience for a client. And you have to remember the exact names of the chosen fonts

**Comment by tomusborne** [comment]
This is intended. Calling the Google Fonts API on a per-block basis like this typically isn't a good idea, and one we don't want to support going forward.

Instead, these calls should be made by the theme, and then the blocks can simply call that `font-family` value that the theme enqueues.
