### ISSUE TITLE
Dynamic Tag - Author Meta add Display Name.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1538]
### Description
The dynamic tag accepts: `display_name` as a key but it's not listed in the Dynamic Tag meta options. Can we add it please.

**Comment by iansvo** [comment]
![image](https://github.com/user-attachments/assets/6fa7ed33-e521-4a99-9106-2f58fcc450e7)

**Comment by iansvo** [comment]
@diggeddy LOL I'm the worst. I'll look into it for you.

**Comment by iansvo** [comment]
@diggeddy Ok so in an interesting turn of events, TIL that the display name is actually in the wp_users table, yet calling get_author_meta('display_name') works. So yeah that's a weird edge case but I can see why it works. We'll just need to do some different handling there to make it work, I have an idea for that. Should be a simple enough PR.

**Comment by iansvo** [comment]
@diggeddy This is now resolved in the latest version of 2.0
