### ISSUE TITLE
Retain the preselected block field unit when value is removed

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#1548]
### Description
When selecting units and adding values in an input box, then remove the value, the unit switches to px.

### Steps for testing
1. Insert any block
2. Add some value somewhere, for example, 1em of top margin
3. Remove the value of `1`
4. When removing the value, the unit switches to px.

When testing different values, this can create extra clicks. GB should respect the unit already in place.

**Comment by Kovas** [comment]
Additionally, some fields remove the unit entirely if the value ends with a period, and these fields lack a popover to select a unit. For example, when setting a transition duration or delay to 0.5s, typing '0.' removes the unit. The unit only resets to 's' once the field is empty or the unit is manually typed back in.

**Comment by iansvo** [comment]
> When testing different values, this can create extra clicks. GB should respect the unit already in place.

We'll consider this for the future, but the current behavior is intentional and how the v1 UnitControl implementation(s) currently work, so we're not looking to change that in this release at this time. 

> Additionally, some fields remove the unit entirely if the value ends with a period, and these fields lack a popover to select a unit. For example, when setting a transition duration or delay to 0.5s, typing '0.' removes the unit. The unit only resets to 's' once the field is empty or the unit is manually typed back in.

This behavior has been addressed in beta 3 (released today).
