### ISSUE TITLE
2.0 The 'Current Post' option in the Post Meta query is not functioning as intended

### ISSUE THREAD

**Issue by Kovas** [tomusborne/generateblocks#1551]
Post Meta queries with 'Current Post' selected as the Select Post option fail to output results. Leaving the field blank achieves the expected behavior, but this creates unnecessary duplication.

![image](https://github.com/user-attachments/assets/b71c5f16-5d10-40e9-bd11-bb8de8fb70d9)

**Comment by iansvo** [comment]
I can confirm this is resolved in the latest version (beta 3).
