### ISSUE TITLE
2.0b3, Query Block, excluding current post is not working

### ISSUE THREAD

**Issue by vburdyko** [tomusborne/generateblocks#1567]
### Description
GenerateBlocks 2.0 beta 3, GenerateBlocks 2.0 Pro beta 3.

When using a Query block to display related posts, the "Exclude Posts/Current Post" option is not working as expected. The current post still displays in the loop.

![image](https://github.com/user-attachments/assets/ef617741-f19b-42e9-8fe2-b47e950eff91)

**Comment by iansvo** [comment]
Thanks for the report. This has been addressed and will be resolved in the next version.
