### ISSUE TITLE
Contained Container does not work correctly on TwentyTwentyOne ( block based themes ) 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#157]
TwentyTwentyOne uses a Full Width Parent Container and then spams every parent node with a max-width property using boss level specificity  CSS selectors.

https://user-images.githubusercontent.com/30641942/139909051-0fdc46ad-b9ca-49ce-8148-66912156f91e.mov

Other themes such as Blocksy ( same issue there ) are also adopting this approach for laying out pages. So we can expect this to be something we see on more themes.

Is adding `!important` to the `gb-container` an acceptable solution ?

```
.gb-container-56c9d397 {
    max-width: 300px !important;
    ...
    ...
}
```

**Comment by diggeddy** [comment]
Some pitfalls of the `!important` - aside from users with Custom CSS is that the Global Styles will be overwritten as this has a low specificity selector:

```
.gb-container-400 {
    max-width: 400px;
}
```

That too would need treatment ( urgh )

**Comment by tomusborne** [comment]
`!important` seems like the only real solution here, which is a shame.

The only other thing I can think of is making the selector more specific depending on what theme is active.

**Comment by diggeddy** [comment]
Looking at the options
1. !important
2. increased specificity eg. `#page .entry-content .gb-container-xxxx ` - this works with TwentyTwentyOne but not Blocksy ( they don't use underscore )
3. Overwrite themes CSS width variable at local scope eg. for TwentyTwentyOne:

```
.gb-container-56c9d397 {
    max-width: 300px;
    margin-left: auto;
    margin-right: auto;
    background-color: #cd2653;
    --responsive--aligndefault-width: 300px;
}

```
But again this is going to be different for every theme.

So - completely turning this on its head... i am not sure we should bother:
1. TwentyTwentyOne has 1million+ installs and could therefore warrant it - however by default it has a 610px wide content container - so very minimal chance that users of that theme will be working with GB to create custom layouts
2. Blocksy and other similar themes have too small an install base to be a concern today. 
3. TwentyTwentyTwo is a 100% block based theme - so a full width blank page is possible so no cause for alarm there ( that i can currently see )

**Comment by sergiu-radu** [comment]
Hi guys,
As an idea, you can add a filter so each theme could implement it.

This filter would output a CSS custom property when the [Container Width](https://tppr.me/34IU5) option is changed, something like this:
```
.gb-container-36981f34 {
    max-width: 200px;
    margin-left: auto;
    margin-right: auto;
    background-color: var(--paletteColor5, #e1e8ed);

    --block-max-width: 200px;
}
```
One important moment is that this custom property name (--block-max-width) should be controlled from the filter so each theme author could change it because every theme may have a different property name for controlling the container width.

What do you think about this?

**Comment by tomusborne** [comment]
@sergiu-radu That's an interesting idea - thanks!

Going to push this to 1.6.0 for now as we get 1.5.0 ready for public alpha.

My gut here says that most future themes will have a full-width setting/be full-width by default, but will continue thinking on it.

**Comment by JeanPaiva** [comment]
@tomusborne we should tackle this on 1.6 or push it to the next version?

**Comment by tomusborne** [comment]
I'm not super comfortable with a solution here yet. Let's push to 1.7.

**Comment by tomusborne** [comment]
We're deprecating these full/contained width options in 1.7 so this should no longer be an issue.

**Comment by cristianraiber** [comment]
@tomusborne - this is still a problem. Happening with Blocksy and GenerateBlocks 1.7.3 + GenerateBlocks 1.5.2 (pro). 

Can you please address this?
