### ISSUE TITLE
Sorting bug for Global Styles is back in Beta 3

### ISSUE THREAD

**Issue by taricco** [tomusborne/generateblocks#1574]
### Description
In beta 3, I am unable to sort more than one style without saving.

### Steps to reproduce
1. After dragging one global style to a new sort order, I am unable to drag another global style without saving first.

#### Expected behavior
I should be able to sort multiple global styles before having to save.

#### Actual behavior
...

#### References: 
...

-----

**Comment by iansvo** [comment]
@taricco Thanks for the report. I have a fix in for this in the latest release version so once that update is available this will be resolved.
