### ISSUE TITLE
GB 2.0b3 Query in block element parameters issues

### ISSUE THREAD

**Issue by Shibumi-Agency** [tomusborne/generateblocks#1588]
### Description
I'm trying to create a "related post" block element to show at the and of every single post. I'm not able to order the post in random order nor to exclude the current post.

### Steps to reproduce
1. I create a block type element in elements
2. I add the new query block and start adding the content through the tags (featured image, title, date, excerpt...)
3. In the query parameters I add the "Exclude posts" -> "Current post"
4. I try to add the paramenter "Order by" -> "Random" but it's not there

#### Expected behavior
As for the current post exclusion I expect to see it excuded in the very same post, while for the random ordering I expect to see the option in the parameters.

#### Actual behavior
It show the same post I'm in in the related posts in the front-end. In the backend I can't seem to find a way to random order the posts.

#### References: 
<img width="2238" alt="Screenshot 2024-12-11 at 16 19 25" src="https://github.com/user-attachments/assets/35581005-71c5-4c96-a018-34426507f7a8" />

**Comment by tomusborne** [comment]
This should be fixed in beta.4 (just released).

Thanks!
