### ISSUE TITLE
GB 2.0b4 Asset library missing button to open media library to get uploaded svg icon

### ISSUE THREAD

**Issue by Shibumi-Agency** [tomusborne/generateblocks#1590]
As in the title, I'm trying to add an svg icon in the asset library but I can't open the media library to select it.
<img width="764" alt="Screenshot 2024-12-12 at 12 09 24" src="https://github.com/user-attachments/assets/cb84b056-e5d2-4ca4-b343-3fa71fc62ce0" />

-----

**Comment by tomusborne** [comment]
Do you have the "Safe SVG" plugin installed? GB will only give you the option to upload an SVG if it's possible. Without Safe SVG, WordPress won't allow you to upload SVG files.

**Comment by Shibumi-Agency** [comment]
Hi,
yes, it is installed. his bug appeared when I switched to GB 2.0


Lorenzo Fassina
***@***.*** ***@***.***>


￼




Via Bronzino, 11
20133 Milano
www.shibumi.agency <https://www.shibumi.agency/?utm_source=email_signature&utm_medium=email>

**Comment by Shibumi-Agency** [comment]
Hi Tom,
thank you for adding the button.
It seems now it has a new issue, at least for me.
Whenever I choose an icon uploaded to my library it won't save it correctly.

This is the process:
- I go to the asset library section
- I create a new icon group
- I add a new icon
- I hit the "Browse" button to open the media library
- I select the icon and hit the "Insert SVG" to confirm

The result would be to have the icon correctly inserted with the name filled and the ssh html filled, but it only fills the name leaving the "SVG HTML" text area input empty.

The icon was downloaded from the google font material design library and was not modified.

Im using GP theme 3.5.1 + GP Premium 2.5.1 + GB 2.0.1 + GB Pro 2.0.0
