### ISSUE TITLE
V2 Block can not pull SVG code from ACF text area field.

### ISSUE THREAD

**Issue by ScarlettYing** [tomusborne/generateblocks#1626]
### Description
V2 Blocks can not pull SVG code from ACF text area field, while V1 blocks can.

### Steps to reproduce
1. create an ACF text area field for pages.
2. edit a page, and add SVG code to the text area field.
3. in the page editor, pull the value via a text block.

#### Expected behavior
Expect the SVG image to be displayed.

#### Actual behavior
The text block outputs nothing.

#### References: 
https://secure.helpscout.net/conversation/2799610972/477545?viewId=1509015

-----

**Comment by tomusborne** [comment]
This is intended. We escape custom fields to prevent vulnerabilities.

Users can bypass this by using a filter. For example: 

```
add_filter( 'generateblocks_dynamic_tags_allowed_html', function( $tags ) {
    $tags['svg'] = array(
        'viewbox' => true,
        'filter' => true,
        'xmlns' => true,
        'class' => true,
        'preserveaspectratio' => true,
        'aria-hidden' => true,
        'data-*' => true,
        'role' => true,
        'height' => true,
        'width' => true,
    );

    $tags['path'] = array(
        'class' => true,
        'fill' => true,
        'd' => true,
    );

    $tags['filter'] = array(
        'id' => true,
    );

    return $tags;
} );
```
