### ISSUE TITLE
Bug: undefined option

### ISSUE THREAD

**Issue by oobi** [tomusborne/generateblocks#181]
When switching between embedded and exteral css, the process throws up a warning (in debug mode) about an undefined variable in generateblocks/includes/class-rest.php:134

This only happens if the settings have never previously been saved.

This is the HTTP call that generates the error:
https://mydomain.com/wp-json/generateblocks/v1/settings?_locale=user

My theme uses the "whoops" library, which causes this warning to freak it out. 

Adding a check for the existence of the current setting key fixes it.

```
line 134:
if ( isset($current_settings[ $name ]) && $current_settings[ $name ] === $new_settings[ $name ] ) {
      ....
}
```

Hope that helps. It's a great plugin - it'd be lovely to not have to patch that each time it updates!

cheers,
Chris

**Comment by JeanPaiva** [comment]
Thanks @oobi, I tagged this issue for the next patch we have scheduled.
