### ISSUE TITLE
Improve control over the icon

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#201]
It would be nice if we had more control over the button and headline icon. For example, the ability to set a different color for the button icon and the ability to set background color with border-radius values for both button and headline icon.

**Comment by JeanPaiva** [comment]
With the addition of Flexbox options, is not simpler to handle this with two blocks? One is only the icon and the other is only the text.

**Comment by quantumleap33** [comment]
Flexbox changes everything, lol.
