### ISSUE TITLE
Container full witdh / contained width preview bug in Gutengerg editor

### ISSUE THREAD

**Issue by simkoG** [tomusborne/generateblocks#204]
### Description
The Container block has an incorrect preview in the external editor while editing the block/page. The "Full width" is shown as "Contained width" and vice versa. 
 
### Steps to reproduce
1. Install a new WordPress instance (latest version).
2. Install and activate GeneratePress and GenerateBlocks. 
3. Create a new page.
4. Add a "Container" block. 
5. The default setting for the section under Layout > Container is "Full width". 
6. The preview will render the block with "Contained width". 
7. Change the Layout > Container to "Contained width", the preview of the block will be full width within the editor. 

#### Expected behavior
"Full width" preview as full width, 
"Contained width" preview as contained. :)

#### Actual behavior
Opposite of the expected behavior. 
Video: [https://i.imgur.com/kx2YTwg.mp4](https://i.imgur.com/kx2YTwg.mp4)

**Comment by JeanPaiva** [comment]
Hey, @simkoG thanks for your input. I added this to the backlog for our next release.

**Comment by tomusborne** [comment]
Hi @simkoG - I believe this has been fixed in our 1.5.0 branch: https://github.com/tomusborne/generateblocks/tree/release/1.5.0

Let me know if you're able to take a look or not.

Thanks!
