### ISSUE TITLE
REM unit for sizes

### ISSUE THREAD

**Issue by simkoG** [tomusborne/generateblocks#205]
Could you add REM size after px, em and %?

**Comment by JeanPaiva** [comment]
@simkoG added this to the backlog of our next version, we will review and evaluate if it can be added without any issues.

**Comment by ejcabquina** [comment]
+1

**Comment by eastriverstudio** [comment]
+1 for this in the next main release. Doesn't make a whole lot of sense to me that you can set all base typography in GP with REM units but then don't have them available in GB. Thanks

**Comment by ericbrissette** [comment]
+1

I know you probably can't support all of the units for every property in the interface.  It would be nice if an advanced switch/field were available for people to enter their own units.  REM for containers would be a great start, but I also like CH for margin and padding especially, although that's probably not a super popular unit among GB users.

**Comment by JeanPaiva** [comment]
Closing as this will be tracked internally.
