### ISSUE TITLE
GB button links in responsive previews are being followed in WP 5.9

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#210]
There is an issue with GB and WP 5.9 due to the new iframe preview that 5.9 introduced. When previewing on tablet and mobile and you click a button that has a link, that link is being followed, loading up the actual page on the preview window! The page reverts to the normal editing page when exiting out of the responsive preview modes.

https://www.loom.com/share/0b6d1e9e1d284f77b5fc7266db6df879

**Comment by JeanPaiva** [comment]
@quantumleap33 it's a bug indeed we will be fixing this for the next patch. Thanks

**Comment by JeanPaiva** [comment]
@tomusborne do we have plans for 1.4.3 or next the next release will be 1.5?

**Comment by tomusborne** [comment]
Looks like this has been fixed in [the 1.5.0 branch.](https://github.com/tomusborne/generateblocks/tree/release/1.5.0)
