### ISSUE TITLE
Shapes overlay container border radius

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#219]
When setting a shape to a container element with a border radius, the shape overlays the container and covers the border radius.

Steps to reproduce:
1. Create a container element, set min-height to 400px, and set a background color. Finally set a border radius of 8px on all corners.
2. Add any shape to this container.
3. The shape overlays on top of the container's border radius.

**Comment by JeanPaiva** [comment]
Confirmed in version 1.7 / 1.5
