### ISSUE TITLE
Remove Query loop and dynamic content attribute defaults

### ISSUE THREAD

**Issue by JeanPaiva** [tomusborne/generateblocks#221]
We need to remove attribute defaults.
 
### Reference
[dynamic content attributes](https://github.com/tomusborne/generateblocks/blob/query-loop-block/src/blocks/headline/components/dynamic-content/attributes.js#L9)

"yea, defaults are evil." Usborne, Tom

**Comment by tomusborne** [comment]
The only default left is `current-post`. Not sure if we want to remove that one or not.
