### ISSUE TITLE
Button Block - Right aligned icon shows as left aligned on front end

### ISSUE THREAD

**Issue by zephyrmike** [tomusborne/generateblocks#303]
### Description
When setting a button icon to align on the right, it shows it correctly in the editor, but is left aligned on the front end.

**Comment by tomusborne** [comment]
Not able to reproduce this on my end. Tried adding a button on `master` branch with icon to the right. Then switched to `query-loop-block` branch and the icon was still there in the editor and on the frontend.

Leaving this open for now for more testing.
