### ISSUE TITLE
Query block - Grid not working as expected

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#305]
There is an issue with the query loop grid when setting container widths for tablet. Setting 50%-50% on desktop doesn't transfer the value for tablet. Also, mobile 100% is not set by default like the normal grid. Works fine on the front end, though.

https://www.loom.com/share/20cda72d17c64fbe85ae5547934a411f

**Comment by zephyrmike** [comment]
Also noticed setting any device width changes all three. i.e. setting tablet to 75% width makes desktop and mobile 75% width as well.

**Comment by JeanPaiva** [comment]
@quantumleap33 @zephyrmike this should be fixed now. The device issue will be handled by #312
