### ISSUE TITLE
Query loop pagination does not have button active state

### ISSUE THREAD

**Issue by JeanPaiva** [tomusborne/generateblocks#313]
### Description
When using the pagination for query loop, we need to differentiate the active page.

I think we can add a new color option for "current page" styles of the button.

### Steps for testing
1. Add a query loop block
2. Add navigation to it.
3. Goes to the front-end and click on page two for example.

**Comment by tomusborne** [comment]
Couple of options I can think of here.

1. We add a `focus` state, and use that state whenever we need a `current` color (pagination, tabs, accordions).
2. We add a `current` state but only when needed. This color option would show up only if the button is pagination, tabs or accordions.

**Comment by JeanPaiva** [comment]
Option is better on my opinion

**Comment by diggeddy** [comment]
i like #2 as well
