### ISSUE TITLE
Support for custom CSS class

### ISSUE THREAD

**Issue by mar1asm** [tomusborne/generateblocks#32]
The blocks don't support custom CSS classes, therefore the users can’t use block extending plugins or use a custom class to customize them. 
L.E. I see you're using your own field, it’s a good practice to support core’s CSS class.

**Comment by diggeddy** [comment]
@mar1asm  Additional CSS class field is found under Block > Settings > Advanced.

**Comment by tomusborne** [comment]
We're using the core custom classes field in 1.2.0-alpha.1 now: https://generateblocks.com/generateblocks-1-2-0/

Thanks!
