### ISSUE TITLE
Query Loop - Dynamic Data > Author Meta --> Author meta field returns no options

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#329]
### Description

<img width="270" alt="Screenshot 2022-04-21 at 18 14 41" src="https://user-images.githubusercontent.com/30641942/164515013-790f2353-262a-41de-94f7-902d467d58aa.png">

No Author Meta Fields are available and the field does not save manual input.

**Comment by tomusborne** [comment]
In order for items to be available in any of the meta fields, they need to be enabled in the REST API. I tried adding some user meta using ACF and enabled REST API and it appeared in the list.

We need to add this to docs.
