### ISSUE TITLE
Dynamic Data before/after text

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#335]
### Description
In the GP Header Element we have templates tags using this `{{template_tag}}`. 
In GP Block Elements we have the Before and After Label options for dynamic data.

Both these method allow for the mixing of static and dynamic content. And this is noticeably lacking in GB.

Lets consider the GP Site Volume and its Post Meta design in a Block Element Content Template using the GP Dynamic Data options:

<img width="644" alt="Screenshot 2022-04-22 at 12 17 03" src="https://user-images.githubusercontent.com/30641942/164704561-693ca604-890c-47c0-99a3-b45f50eee837.png">

Here we have a Container Block, and 2 x stacked Headline Blocks. 

Whereas to replicate the same layout in GB we have require this at the very minimum:

<img width="644" alt="Screenshot 2022-04-22 at 12 20 31" src="https://user-images.githubusercontent.com/30641942/164704972-f3f28504-5c64-48f9-a182-e6032626f14c.png">

Aside from the additional HTML ( and related CSS ) it makes for a less friendly UX and a process best suited to the more advanced user.

We should consider some of the existing GP Elements features as an option.

**Comment by tomusborne** [comment]
I was thinking about this. The only way to do it really is to add a "Before" and "After" text field in the dynamic options when a data type is set. Not sure if anyone else has a better idea?

**Comment by diggeddy** [comment]
Is it not possible to 'replace' a different parts of the Markup ? For want of an example the `<mark>` tag that is added by the data Highlight.

**Comment by tomusborne** [comment]
Replacing different parts of the markup is tricky, not exactly sure what the UI would look like there? Do you mean applying the dynamic data to a specific part of the text vs the entire string?

We use before/after text in Block Elements. It's added before the dynamic link but within the headline markup so it's all styled the same. It doesn't help if the user wants the before/after text to be linked as well, but it works for the examples @diggeddy screenshotted above.

**Comment by diggeddy** [comment]
I feel if the user wanted different styling for the before/after text then they need to use many inline headline blocks as above Or we wrap the before/after content with a CSS class so at least it could be styled with CSS.

The nicer option would be:

`<h2 class="gb-headline gb-headline-2fedd951 gb-headline-text">
Atque <mark class="gb-data-highlight">data goes here</mark> rerum fuga eos sunt nihil. 
</h2>`

The UI would be something akin to the current GB Highlighter option. Could be called: 'Data Highlighter' which provides the `<mark class="gb-data-highlight">...</span>`.
And it should have some in editor styles to make it clear what it is.

The logic  - if the `gb-data-highlight` exists then apply dynamic data to just the `<mark>` element.

**Comment by swissky** [comment]
Will give a push here ;) was looking for the "before text" option inside the "Dynamic Data" for a "Written by...."

**Comment by diggeddy** [comment]
This is covered here:
https://github.com/tomusborne/generateblocks/issues/1094

Closing.
NOTE: template tag version to be handled in future GB pro.
