### ISSUE TITLE
Headline - Dynamic Excerpt - Editor trims length to GP Blog Settings.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#339]
### Description

The Headline Dynamic excerpt is trimmed to GP Blog Excerpt length in the editor.
If you set the GP Excerpt to 55 - then GB excerpt will never display greater length.

It is correct on the front end.

**Comment by tomusborne** [comment]
There isn't really an elegant way to solve this at the moment. We can re-visit in the future if we implement our own REST API options.
