### ISSUE TITLE
Container "edit as HTML" causes error

### ISSUE THREAD

**Issue by Tropicalista** [tomusborne/generateblocks#34]
I have tried to edit as html a container, I haven't touched the code and I have then clicked on "edit visually".

This generate an error: "this block contains unexpected or invalid content"

**Comment by tomusborne** [comment]
I'm not overly sure why Gutenberg has this option, as it usually causes errors like this due to block validation. I think it would be best that we simply disable "Edit as HTML" for the Container.

**Comment by Tropicalista** [comment]
The option is there because for some strange reason Gutenberg team thinks that add a simple `rel=nofollow` option should be done editing html. In GenerateBlocks we have all options well designed, so I think disabling it is the way to go.
