### ISSUE TITLE
Image Block - Dynamic Image missing align classes on front end.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#340]
### Description
Editor alignment options applies an `align*` class to the element.
This applies in the editor but not on the frontend IF the image is set to Dynamic Data Type eg. Featured image.

### Steps to reproduce
1.  Add an Image Block, set it to Dynamic > Post Type > Post --> some post --> Featured Image.2. 
2. Put some content below just to see the floating applied.
3. Set the image block to Align left3. 
4. Check the front end

This probably needs to part of a wider discussion regarding the core Toolbar options.

**Comment by tomusborne** [comment]
Nice find. I think we should ditch the core alignment options and do the following for desktop, tablet and mobile:

Align:

Left
Center
Right
Float Left
Float Right

**Comment by diggeddy** [comment]
Yep, thats my thoughts exactly
