### ISSUE TITLE
Headings are not changed in Astra Theme

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generateblocks#35]
If I take Astra as my theme (which I unfortunately have to take because the customer wants it that way), then the heading colors of GB are not taken over. At least not on the live page.

Very easy to reproduce:

1) Install Astra
2) Put the heading of GB into an Astra container.
3) Change the color of the headline
4) Update
5) See Error

**Comment by tomusborne** [comment]
This has to do with how specific their selectors are vs how specific ours can be.

We have added the tag name to the selector in 1.2.0, might be worth testing: https://generateblocks.com/generateblocks-1-2-0/

**Comment by SchneiderSam** [comment]
@tomusborne nope. I am testing with alpha-5

In Gutenberg i have this:

![image](https://user-images.githubusercontent.com/9355398/99358444-d866c880-28ad-11eb-912e-8536538691ea.png)

In the Frontend:

![image](https://user-images.githubusercontent.com/9355398/99358480-e1f03080-28ad-11eb-8194-1713c23d0a3d.png)

If you want, i can provide a password to the Website i am testing. How can i send you the credentials?

**Comment by tomusborne** [comment]
You can send the URL through our contact form if you'd like: https://generateblocks.com/contact

We are limited when it comes to stuff like this, unfortunately. If themes are using a more specific selector than what GB can provide, there isn't much we can do.
