### ISSUE TITLE
Query loop - Headline Excerpt issue for certain post types

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#353]
Seems like the dynamic headline excerpt from the query loop seems to be failing for certain custom post types?
https://www.loom.com/share/7da48b41ad5243959f654ab038efe336

**Comment by JeanPaiva** [comment]
@quantumleap33 the post type `Events` is from a plugin or you manually created?

**Comment by tomusborne** [comment]
@JeanPaiva likely the same one he created here: https://github.com/tomusborne/generateblocks/issues/352

**Comment by quantumleap33** [comment]
@JeanPaiva It's from the Custom Post Type UI plugin.
