### ISSUE TITLE
Query block: Dynamic headline ACF Wysiwyg custom field invalidates on refresh

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#354]
Just noticed an issue with an ACF Wysiwyg custom field. When you refresh the page, it creates an error on the element. Using a custom post type for this.
https://www.loom.com/share/ecdfc1c08a614fb7aab5b97a1390521d

**Comment by tomusborne** [comment]
We're going to handle this in GBP: https://github.com/tomusborne/generateblocks-pro/issues/102
