### ISSUE TITLE
Image block - no obvious way to set a fallback image when using dynamic data

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#359]
Hope I'm not jumping the gun by testing this before an Alpha release but thought it would be useful to feedback something from my own testing with the new image block where there doesn't seem to be an obvious way to set a fallback/placeholder image when using the dynamic data options.

In my case I was using the image block in a GB query loop with a featured image set in the dynamic data settings. Any posts wihtout a featured image are blank in the editor and frontend and there is no obvious way I can see to set a fallback/placeholder for those posts.

In the old dynamic image in Elements we could set a fallback image by spsecifying a static image first and then choosing the dynamic options, but this doesn't seem to be an option with the image block? 

Hope I'm not missing someting!

**Comment by JeanPaiva** [comment]
@eastriverstudio no worries on testing before alpha, it's always good to have more people testing.

About the placeholder, indeed, we still don't have a solution. One of our coworkers mentioned this as well. Me and Tom are gonna discuss the best way to implement it, maybe it will come during alpha phase.

Anyway thank you for the tests, hope you have enjoyed playing with this new features.

**Comment by JeanPaiva** [comment]
@eastriverstudio we added some filters to help you setup fallback images. On the PR #365 you can check some examples.

**Comment by eastriverstudio** [comment]
@JeanPaiva great, thanks for coming up with something so quickly, a filter is definitely a good solution to this.

I think for longer term polish and flexibility it would still be nice if there could be a way to handle this as a setting in the editor like with Element templates and the dynanmic image block. 

This would make it easier for less technical users to manage/update and add a bit more flexibility, say for example if you have a number of different query loops for different post types, you might want different fallback images for each. I think it would be a nice touch if there was a visual way to control/manage a custom fallback option via the editor loop settings in my mind. 

For now though this should absolutely do the trick, so thanks very much!
