### ISSUE TITLE
Use classes for alignments

### ISSUE THREAD

**Issue by loxK** [tomusborne/generateblocks#36]
When aligning an item an inline CSS is generated (eg: `text-align: center;`)

So, with custom CSS, it is not possible to target elements based on the alignment chosen by the users.

WordPress used such classes, for the media-text block it can get "has-media-on-the-right".

**Comment by tomusborne** [comment]
I'm not sure using utility classes for alignment is a great idea, as they don't really work for responsive aligning on tablet/mobile. You'd need separate classes for each device.

Perhaps adding a custom class if you want/need users to target an element based on alignment would be sufficient?

**Comment by loxK** [comment]
A custom class is overcomplicated for some end users.
