### ISSUE TITLE
Image block - units control is fixed to px, should allow for mixed units

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#362]
The image block unit setting is currently fixed to px only. This seems slightly limiting.

I think the unit selection should follow WP core's dynamic featured image block with the option for setting mixed units on width & height values. This works well and allows the user to set say 100% on the width value (so they don't have to guess or work out the correct px value), but have a fixed px value on the height and use the object-fit settings.

This would allow for greater flexibility when using the GB image block as a static image element as well, e.g it would allow stretching an image the full width of a container etc so we can have images inline with object-fit rather than resorting to backgrounds.

**Comment by tomusborne** [comment]
Hey @eastriverstudio - thanks for the feedback! Always appreciated.

I've created a bit of an experimental PR here: https://github.com/tomusborne/generateblocks/pull/375

It achieves the mixed units/different units across devices.

Not sure if it will make it into 1.5.0. If not, we may look at adding more units (like %) using our "traditional" method once https://github.com/tomusborne/generateblocks/pull/374 is merged.

**Comment by tomusborne** [comment]
This was approved and merged. It's now available in the `release/1.5.0` branch.

Thanks!

**Comment by eastriverstudio** [comment]
Hi @tomusborne great news, thanks for considering this request and making it part of the 1.5.0 release! :)
