### ISSUE TITLE
Disabling page elements does not work when GB 1.5 activated

### ISSUE THREAD

**Issue by KubaUrbanowicz** [tomusborne/generateblocks#384]
### Description
Page elements such as content Content Title or Footer cannot be disabled in page options

### Steps to reproduce
1. Enable GB for it to occur.
2. Does not occur when GB not activated.
#### Expected behavior
Page elements should get disabled as normal.

#### Actual behavior
Ticking the boxes has no effect.

#### References: 
Environment: Staging site on Site Ground, caching disabled and double-checked, child theme of Generate Press active with page categories modification.
Edit: GP Pro activated.
Edit 2: WordPress – current stable
-----

**Comment by tomusborne** [comment]
Hey @KubaUrbanowicz - thanks for testing 1.5!

I'm not able to reproduce this issue on my end.

https://user-images.githubusercontent.com/20714883/166488080-f05b3539-8f0f-40d0-ab88-6fdb4dbcc53d.mp4

Did you do something different than my video showed?

Thanks!

**Comment by KubaUrbanowicz** [comment]
Doesn't happen on my side any more either. Feels like a server hiccup after all. Perhaps caching was not disabled fast enough. Given a few hours things are back to normal.
The issue can be closed as far as I am concerned.
