### ISSUE TITLE
Vertical alignment not displaying properly in Wordpress edit view.

### ISSUE THREAD

**Issue by LRYhon** [tomusborne/generateblocks#386]
### Description
Vertical alignment not displaying properly in Wordpress edit view.

### Steps to reproduce
Applying vertical alignment to a container does not show any changes in Wordpress. However, when you click publish or update the change is visible on the published page.

#### References: 
![image](https://user-images.githubusercontent.com/10143967/166639280-4bb29f07-1aee-4fcb-8ac7-cb9023f60c3f.png)
![image](https://user-images.githubusercontent.com/10143967/166639211-3460c4c9-7a4a-407d-ae7e-7ffd2adb0206.png)
![image](https://user-images.githubusercontent.com/10143967/166639393-6a3d9fa1-6328-4161-b339-fcf9ccd1eca5.png)

-----

**Comment by JeanPaiva** [comment]
@LRYhon this should be fixed on next patch of the alpha. Thank you

**Comment by LRYhon** [comment]
Hi Tom. Thanks for your help.

I just tried to replay what you show in the video and now i have this:

![image](https://user-images.githubusercontent.com/10143967/166916621-5f8045d5-91d7-488e-ab02-2ce1979441d1.png)

As you can see vertical aligment is working well, but there is no way to show the dynamic background image properly. Of course i can apply a minimal height (In this case 422px) but now the title an the excerpt are not aligning vertically.

![image](https://user-images.githubusercontent.com/10143967/166917347-0af59a86-f4f3-4e18-9149-33f1a6ec88d9.png)

Curiously, this strange behavior is only visible in the Wordpress editor. On the other hand, the vertical alignment is displayed correctly in published web.

![image](https://user-images.githubusercontent.com/10143967/166917722-70a83dc9-8282-4d77-a8cd-d2102d9e68f0.png)


> Thanks for testing, @LRYhon!
> 
> I took a look and here's what I experienced:
> 
>  vertical-align.mp4 
> Applying the vertical alignment to the Container within the loop doesn't do anything as it's trying to align itself with other items in the same Grid.
> 
> However, applying the vertical alignment to the outer Container within the first Grid does what you're looking for I believe.
> 
> Let me know if you're experiencing the same thing.

**Comment by tomusborne** [comment]
This should be fixed in our alpha.2 branch: https://github.com/tomusborne/generateblocks/tree/release/1.5.0-alpha-2

Thanks for the help!
