### ISSUE TITLE
Background image bug when using two or more columns

### ISSUE THREAD

**Issue by LRYhon** [tomusborne/generateblocks#387]
### Description
Background image bug when using two or more columns

### Steps to reproduce
1: Create a Query Loop with the following structure to display the background image in one column and the post title in another column.
![image](https://user-images.githubusercontent.com/10143967/166640986-74b654bf-d221-4b9d-b07f-a239ccf2cf7b.png)

2: Apply a dynamic background image to the first column.
![image](https://user-images.githubusercontent.com/10143967/166641388-dc48cf7f-2c9c-4ec6-aedc-17cbb3c925f0.png)

#### Expected behavior
Show a different background image for each post

#### Actual behavior
... This...
![image](https://user-images.githubusercontent.com/10143967/166641681-dca39808-a650-49b5-8f95-5ac07ee2e947.png)

-----

**Comment by JeanPaiva** [comment]
@LRYhon we will be fixing this for the next patch, thanks again.

**Comment by JeanPaiva** [comment]
@LRYhon forgot to mention, you can workaround this by using inline styles.

![image](https://user-images.githubusercontent.com/7506830/166700452-74310d44-7fd8-4b3b-a298-1fc433ce9970.png)

**Comment by quantumleap33** [comment]
Using the image block instead of setting a background image for the left column container also works.
