### ISSUE TITLE
Query loop enhancement: Add "use current post's parent" as a parameter option

### ISSUE THREAD

**Issue by Graphnic** [tomusborne/generateblocks#389]
The query block is simply brilliant... so so flexible. Thank you for building it!

It occurred to me that I could build out a page navigation block with it, that would be dynamically updated as additional pages are added to each section of a site.

The small downside is that one has to select the parent page manually in the settings.  While this isn't a great chore, it would be great if we could just have a "use current post's parent" option.  That would mean we could save the block as a template and just add it to other pages without needing to change the parameter manually.

**Comment by eastriverstudio** [comment]
+1 for this. It's easy enough to do this with WP Query so hpoefully it wouldn't be too much work to add to params but how that translates to the editor view is another thing I guess. Definitely have found myself needing this kind of thing though so would be a handy additional enhancement.

**Comment by Graphnic** [comment]
@eastriverstudio Yes it is, I have just launched a site where I built this using ACF blocks and WP Query... but replicating it this morning with GB took literally minutes, rather than hours! This additional option would bring absolute parity with the custom block I built.  Very powerful indeed.

**Comment by JeanPaiva** [comment]
@Graphnic and @eastriverstudio that's a good feature. We have plans to improve the query parameters to accept dynamic values to facilitate use cases similar to what you pointed.

**Comment by danstramer** [comment]
+1 for this, thanks!

**Comment by JeanPaiva** [comment]
Closing this as it is duplicate from tomusborne/generateblocks-pro#106
