### ISSUE TITLE
Dynamic Button discussion

### ISSUE THREAD

**Issue by daveit** [tomusborne/generateblocks#390]
### Description
I placed a button on a query loop block, and selected that it be dynamic, I can choose all the fields available (posts), but I want it to link to the post details page, but I was expecting it to allow me to enter a typical description such as 'read more', 'full details' for example, but could not see any way to add that common description. In case I am missing something, add it here for discussion rather than assuming it is a missing feature.

#### References:
...

-----

**Comment by JeanPaiva** [comment]
@daveit you can achieve this by not selecting any data type and normally typing on the button. You can still select the link type and the correct data source.

![image](https://user-images.githubusercontent.com/7506830/166679426-5ea05f82-b894-43a0-b36c-f71dbadc1191.png)

**Comment by daveit** [comment]
Great thanks for the heads up :)
