### ISSUE TITLE
dynamic background image doesn`t work when an additional grid is inside the query loop block

### ISSUE THREAD

**Issue by htaitl** [tomusborne/generateblocks#391]
### Description
i used a grid inside the query loop block because i want to have the image and content side by side and not underneath.
when i use the image block it is working as expected, but when i try to use the dynamic background image i got the same image in all posts as preview and the images are not rendering (not shown) in the frontend.

### Steps to reproduce
[Bildschirmfoto 2022-05-04 um 14.03.48.pdf](https://github.com/tomusborne/generateblocks/files/8620155/Bildschirmfoto.2022-05-04.um.14.03.48.pdf)

#### Expected behavior
the same as in the first level container inside the quey loop block

#### Actual behavior
...

#### References: 
...

-----

**Comment by JeanPaiva** [comment]
Relates to #387

**Comment by JeanPaiva** [comment]
@htaitl  forgot to mention, you can workaround this by using inline styles.

![image](https://user-images.githubusercontent.com/7506830/166700452-74310d44-7fd8-4b3b-a298-1fc433ce9970.png)
