### ISSUE TITLE
Accessibility enhancement request: Add an option to apply flexbox's 'row-reverse' declaration to the grid block

### ISSUE THREAD

**Issue by Graphnic** [tomusborne/generateblocks#392]
When building layouts with repeating rows (two columns with an image next to a heading and text for example), it's sometimes desirable to alternate which side the image appears, for aesthetic reasons (left, right, left, right etc). The problem with doing this manually is that it's also reflected in the code semantics, making similar structures _appear_ different to assistive technology such as screen readers. This can be confusing depending on the circumstance.

I can overcome this by adding a custom class to the grid that applies the flexbox `flex-direction: row-reverse;` declaration.  This visually flips the layout while maintaining consistent markup between rows, which resolves the inconsistency in the screenreader  announcements.

Could this be considered as a toggle in the block settings?  I believe Kadence blocks does something similar (at least from memory), and is an approach I use for custom blocks.

**Comment by JeanPaiva** [comment]
In version 1.7 we are adding flexbox controls and you will have that option for custom "grids" created with container only. The grid block itself will be updated in the future to have these controls and will inherit from the container.
