### ISSUE TITLE
About post related to Query Loop Block

### ISSUE THREAD

**Issue by JR-Mora** [tomusborne/generateblocks#394]
Hi, I think the new Query Loops block is very good and has a lot of possibilities. but I have a doubt
### Description

Re-create WP Show Post function for related posts with GB

#### References:

I've tried but I can't get the results to be related, I can't find how to shorten the words or characters in the titles either. (In Wp Show Post it is done with CSS)

https://ibb.co/c1y2fML

Is it already possible to recreate WP Show Post results with GB 1.5.0a?

-----

Greetings and congratulations for the work.

**Comment by tomusborne** [comment]
Thanks for the feedback!

In order to truncate the title in GB you will still need some CSS. Feel free to open a support topic and we can help with that.

As for related posts, we don't have this feature in GB as of right now. How were you making the WPSP list related?

**Comment by JR-Mora** [comment]
Thanks Tom, 

For the moment it's not necessary this help because with WPSP I have located the class to truncate the title.

I am now using WPSP to display related posts list by **post_tags**. Will this be possible in future versions of GB?

Thanks for everything

**Comment by tomusborne** [comment]
You can query posts by their post tags/categories currently. However, it's not currently possible to base the tags/categories on the post you're viewing on the frontend. You need to manually enter the categories/tags to query by.

We will be looking at allowing dynamic parameters in GB Pro soon.

Thanks!
