### ISSUE TITLE
Running Flywheel Local - Crashes my local site each time I install Alpha-1

### ISSUE THREAD

**Issue by JHC827** [tomusborne/generateblocks#398]
### Description
...
When I upload GB Alpha-1 on my local server (I'm running Flywheel local), my site crashes and I have to manually delete GB Alpha-1 from my plugins folder, clear my cache, and reboot my localhost in order to get my site working again.

### Steps to reproduce
1. 

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...
I downloaded the following from my local error log and copy/pasted it:

2022/05/04 12:44:19 [error] 9704#17364: *1507 no live upstreams while connecting to upstream, client: 127.0.0.1, server: starter.local, request: "GET /favicon.ico HTTP/2.0", upstream: "http://localhost/favicon.ico", host: "starter.local", referrer: "https://starter.local/wp-admin/update.php?action=upload-plugin&package=15&overwrite=update-plugin&_wpnonce=e833b43c67"

-----

**Comment by tomusborne** [comment]
@JHC827 as per Facebook it looks like you got this sorted. Let us know if you run into it again.

Thanks!
