### ISSUE TITLE
UI glitch / bug, GB image and Custom Fields

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#402]
### Description
When GB image block has a big enough image. big enough that it procuces veritcal scroll in the editor, the metaboxes (coming from, in my case ACF) detach from the bottom and fly over the image block. 

### Steps to reproduce
1. Prepare a post type with some custom fields on the bottom, under the editor.
2. insert GB image block, and pull a bit larger image.
3. scroll.
#### Expected behavior
1. Prepare a post type with some custom fields on the bottom, under the editor.
2. insert GB image block, and pull a bit larger image.
3. the metaboxes stay at the bottom under the content area..

#### Actual behavior
1. Prepare a post type with some custom fields on the bottom, under the editor.
2. insert GB image block, and pull a bit larger image.
3. the metaboxes fly above the image block and scroll with the content.
#### References: 

![ui glitch](https://user-images.githubusercontent.com/53581066/166804043-97c93bfa-dc8d-42ff-a1f0-0cc57f7da825.png)
![smaller image](https://user-images.githubusercontent.com/53581066/166804118-5f9f3511-5c13-4cec-9d26-4586e05c04f8.png)

-----

**Comment by quantumleap33** [comment]
This is a core issue:
https://github.com/WordPress/gutenberg/issues/38062

**Comment by thisbit** [comment]
I know, but taught the team should know anyway.

**Comment by tomusborne** [comment]
I believe this is fixed in WP 6.0.

Thanks for testing!
