### ISSUE TITLE
offer a query loop with featured image as one of the defaults

### ISSUE THREAD

**Issue by danstramer** [tomusborne/generateblocks#406]
### Description
It could be not clear for beginer/intermediate users how to add a featured image into the query loop

### Steps for testing
1. Create a default query loop with featured image

#### References:
...

-----

**Comment by JeanPaiva** [comment]
Hey @danstramer that's a nice featured, just opened a PR. It should be on the next alpha patch.

**Comment by danstramer** [comment]
thanks @JeanPaiva , I don't know if GP are planning on creating patterns with the new Query loop block - but that would be cool to have a gallery of loops to start off from.

**Comment by JeanPaiva** [comment]
@danstramer yes, we have plans to add query loop templates to the Template Library block we have on PRO. In the future we may do something for the free tier as well, but anything decided yet. We are currently focused on creating a very stable Query loop and Dynamic content.

Here's the new template, next patch will be released probably on Friday. 
![image](https://user-images.githubusercontent.com/7506830/166829990-e31d48cc-6c4f-45cb-9f12-5d0818963677.png)
