### ISSUE TITLE
Allow for before/after on dynamic data

### ISSUE THREAD

**Issue by danstramer** [tomusborne/generateblocks#408]
### Description
For buttons for example, I would like to add before the name of the post: 'Read more about: [dynamic content single post title]

### Steps for testing
1.create a button
2. set to dynamic content
3. set to data source: current post
4. set to data type: title

The button will show the current post's title. I would like to add text before or after. Also, please wrap that text with a <span> tag so it can be styled.

Thanks!

#### References:
...

-----

**Comment by JeanPaiva** [comment]
Hey @danstramer its a planned feature. We will be working on adding this after the first release.

Related to https://github.com/tomusborne/generateblocks-pro/issues/101
