### ISSUE TITLE
UX/UI issue: Gutenberg Toolbox goes beyond the viewport when on smaller screens.

### ISSUE THREAD

**Issue by ejcabquina** [tomusborne/generateblocks#41]
a potential bug.  https://pasteboard.co/JI12rsM.jpg
 
 This occurs on smaller screens when there's a significantly large horizontal gap value assigned to a Grid Block.

**Comment by leohsiang** [comment]
Could be related: The horizontal gap is still showing for 100% container width in the editor:
![horizontal gap issue](https://user-images.githubusercontent.com/20894279/104357244-c7a78d00-54c1-11eb-977e-c9543d59a9f6.png)

**Comment by tomusborne** [comment]
Both issues should be fixed in 1.5: https://github.com/tomusborne/generateblocks/pull/170
