### ISSUE TITLE
Metabox custom fields not showing as options when Post meta selected

### ISSUE THREAD

**Issue by rockyviewweb** [tomusborne/generateblocks#413]
I am running into an issue with the dynamic data in connection with Metabox custom fields. With the "old" GP dynamic data system for elements, I can select the dynamic icon on the block toolbar, select Post meta, and then enter a meta field name from one of the Metabox custom fields. But now with this dynamic section in the block settings on the right side, I can select Post meta, but the drop-down selection for the Post meta field is not finding the Metabox custom fields, and I can't paste in a custom meta field name. So basically, it seems that I am unable to access Metabox fields with the new Dynamic Data tool section.

<img width="655" alt="Screen Shot 2022-05-04 at 11 00 32 PM" src="https://user-images.githubusercontent.com/42782577/166867465-a44adb2c-a3db-48ea-93f3-1308fb8ddb68.png">

<img width="322" alt="Screen Shot 2022-05-04 at 11 01 44 PM" src="https://user-images.githubusercontent.com/42782577/166867471-ceab74bd-fc26-465d-892c-c191df3a22e3.png">

**Comment by JeanPaiva** [comment]
@rockyviewweb your meta field must be enabled on the API to show in the select meta field. The meta argument `show_in_rest` must be true.

**Comment by rockyviewweb** [comment]
@JeanPaiva I’m out on a field trip that my daughter’s class is on. But I will check on the Rest API settings for Metabox later and see if I can get those custom fields to show up.

**Comment by JeanPaiva** [comment]
@tomusborne not a complicated feature to add, but it won't have the live preview for meta fields that are not enabled on the API.

**Comment by rockyviewweb** [comment]
Is there a simple clean way to provide both options (API selection with previews as well as manual entry)?

**Comment by JeanPaiva** [comment]
@tomusborne ok, after fixing some bugs I'll add the input field for manual meta keys.

**Comment by JeanPaiva** [comment]
@rockyviewweb that's what I'll try to achieve, both options.

**Comment by rockyviewweb** [comment]
@tomusborne @JeanPaiva While the update to allow manual entry of post meta ids does open up functionality, it feels like a bit of a bandaid. The underlying issue is that custom post types created with Metabox are not showing up in the dropdown options without jumping through some hoops. I have also tried ACF, and those custom fields also do not show up in the drop-down selection menu for post meta. So this isn't just a Metabox issue but seems to also include ACF.

**Comment by tomusborne** [comment]
The issue here is how these plugins register their post meta and how the editor API displays them. They don't display in the core `meta` data of the API. We need to specifically look for each plugin in the API to get their data.

We'll be adding better editor support for these popular plugins in the pro version.

**Comment by madanpraba** [comment]
Thanks for your decision. Pulling Metabox or ACF custom fields will make GP more flexible.
