### ISSUE TITLE
Ability to use query loop to display related posts on a single post content template element

### ISSUE THREAD

**Issue by rockyviewweb** [tomusborne/generateblocks#414]
I want to use the query loop to display related posts on a single post content template element. For example, if I have a custom post type of "Events" and also have a custom post type of "Presenters" with a relationship set up between the two post types. For a single event, I want to display a query loop of the related presenters based on the relationship settings that I have made between those two post types.

Would this be related to the toggle for inheriting from the template? Like if the template element was set for individual events, and I toggled on to inherit from the template, would it be possible to have an option to select a relationship for the query loop?

**Comment by JeanPaiva** [comment]
Its a planned feature for pro version. Reference https://github.com/tomusborne/generateblocks-pro/issues/106
