### ISSUE TITLE
Query Loop Container Dynamic Data Link Applied Improperly

### ISSUE THREAD

**Issue by austinhamilton** [tomusborne/generateblocks#415]
### Description
When adding a link to a container within the query loop, the entire page is clickable as the link, instead of just the container the link is applied to.

### Steps to reproduce
1. Create a page
2. Add a query loop block with some data to loop through.
3. Add a container within the query loop.
4. Add a link to the container

#### Expected behavior
Only the container that the link is applied to will be clickable.

#### Actual behavior
The entire page is clickable for the given link.

#### References: 
https://bigguydigital.com/query-loop-container-links/

-----

**Comment by tomusborne** [comment]
Hey @austinhamilton - thanks for testing!

This bug is fixed in GB Pro 1.2.0 which will be entering public alpha early next week.

**Comment by austinhamilton** [comment]
Great!
