### ISSUE TITLE
Query Loop for Categories

### ISSUE THREAD

**Issue by austinhamilton** [tomusborne/generateblocks#416]
### Description
I think it would be useful to use the Query Loop Block to display categories with meta data such as category or category image.

### Requirements
1. Create query loop block
2. In addition to posts and pages, be able to use taxonomies such as categories.
3. The desire is to be able to have a query loop display a list of category images that link to the category.

**Comment by JeanPaiva** [comment]
@austinhamilton that's a planned featured, but will come in future versions.

**Comment by austinhamilton** [comment]
Thank you.
