### ISSUE TITLE
GB Block Templates?

### ISSUE THREAD

**Issue by davidhund** [tomusborne/generateblocks#42]
I am trying to implement [Block Templates](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/) for my pages with generateblocks.

Specifically I'd like to 'prefill' the editor with a set of `generateblocks/container` blocks containing other (GB) blocks to prevent the editors having to setup the page layout everytime they add a new page.

However: I'd like to configure some settings for these blocks: `generateblocks/container` needs to be `full` width, and have an extra classname.

How do I add these in my PHP Block Template code?

```php
// ...
$args[ 'template' ] = array(
  array(
    'generateblocks/container',
    array( 'some-setting' => 'full', 'classname' => 'bar' ), // <!-- this?!
    array( /* child-blocks here... */ )
  )
);
```

Is this possible? How do I find the settings? Of should I setup these 'templates' a different way?
TIA!

**Comment by tomusborne** [comment]
Hey @davidhund - sorry I didn't respond sooner.

I assume you've moved on, but just in case, you can find all of the attributes here: https://github.com/tomusborne/generateblocks/blob/1.3.3/src/blocks/container/attributes.js

For the `full` width, you'd need to use the `align` attribute.

Let me know if you need more info :)
