### ISSUE TITLE
Query Loop: Conditional Logic

### ISSUE THREAD

**Issue by austinhamilton** [tomusborne/generateblocks#423]
### Description
What about conditional logic within the query loop? For example, show a given block if a custom field matches a given value? Or even apply a given global styling if a condition is met?

The query loop block is very powerful, I'm thinking of ways that could unlock even more potential.

**Comment by JeanPaiva** [comment]
@austinhamilton gonna log this to our backlog, it would be really good to have such conditional logic implemented. Thank you.

**Comment by JeanPaiva** [comment]
Added to our internal task for display rules. Thanks!
