### ISSUE TITLE
Add Delete Parameter option before selecting a parameter

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#425]
### Description
Consider adding the Remove Parameter button in this spot before selecting a parameter:
https://www.screencast.com/t/2Nfa3qxt

### Steps for testing
1.

#### References:
...

-----

**Comment by tomusborne** [comment]
There isn't really anything to delete yet as nothing has been added. For example, doing nothing and refreshing the page will simply remove the dropdown. Will keep an eye on this to see if more people are confused by it.
