### ISSUE TITLE
Query Loop ignores post order value

### ISSUE THREAD

**Issue by austinhamilton** [tomusborne/generateblocks#429]
### Description
Query Post seems to ignore the order field for posts

### Steps to reproduce
1. Create some posts or pages and set the order of each one, say 0, 1, 2, 3, 4, 5.

#### Expected behavior
1. Query Loop displays them in the configured order

#### Actual behavior
The order is not what is put in the order field.

#### References: 
...

-----

**Comment by tomusborne** [comment]
This is due to `menu_order` not being an `orderby` option in the editor API. We're considering a couple of different options to allow this to happen.

Thanks!

**Comment by tomusborne** [comment]
We've added `menu_order` as an `orderby` option in alpha.2.

Thanks!

**Comment by austinhamilton** [comment]
So does this mean I finally contributed something meaningful?
