### ISSUE TITLE
block has encountered an error... and JS error

### ISSUE THREAD

**Issue by mmjaeger** [tomusborne/generateblocks#438]
### Description
I posted this on your website yesterday: 
this isn’t really working for me – eg I put a headline block – as soon as I hit dynamic data I get an error: “this block has encountered an error and cannot be previewed.” – checking the error console I see the following error: “TypeError: undefined is not an object (evaluating ‘e.title.raw’) – react-dom.min.js.

what am I missing

### Steps to reproduce
1. using WP 5.9.3 - trying to add some CPT title as well as a CPT ACF image field - nothing works
maybe the Pro version is needed?? meta fields (act fields) do not show in the drop down either.
#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----
<img width="1710" alt="Screen Shot 2022-05-08 at 4 04 01 PM" src="https://user-images.githubusercontent.com/1554580/167319502-e6f1f8e1-d2b1-488b-b1a3-3ac044bfcaba.png">
<img width="787" alt="Screen Shot 2022-05-08 at 4 04 22 PM" src="https://user-images.githubusercontent.com/1554580/167319504-0cd5ae32-78f2-4d5f-b64b-d795389b9327.png">

**Comment by JeanPaiva** [comment]
@mmjaeger what do you mean by "trying to add some CPT title"? You created a custom post type with title, that's right?

ACF meta fields are not supported for now, but we have planned support for the next versions. The current `alpha-1` you only can select meta fields enabled on the REST API, but for `alpha-2` that will be release this week, we added the option for you to manually add post meta keys.

**Comment by tomusborne** [comment]
Based on the error I'm assuming that the post type you're querying doesn't have "Title" support.

I've just opened a PR that should prevent the error from happening in this case.

Thanks!
