### ISSUE TITLE
Container Block - positioning text over background image

### ISSUE THREAD

**Issue by elliottmart** [tomusborne/generateblocks#44]
Problem: trying to accurately position text (headline or paragraph) over container block with a background image. It is also sometimes desirable/necessary to put a semi-opaque background to the text overlay, so that the background image doesn't make it hard to read the text.

If using just a headline block (without a holding container )I would like to be able to position inner headline block without having to assign a class (eg. inner-text) with css like 
.inner-text {
 width: 400px;
}
[the problem is that without this css, the headline block centers in the parent container, and also the headline text background spans right across the entire parent div - not just on the headline text ]

or

 if trying to nest containers using a class on the inner child container like
.child_container {
  position: absolute;
}
to allow me to position the container which holds my text. [ problem is without the css, the inner nested container block does not use the sidebar margins with respect to the parent container ]

Solution: possibly have a toggle on the container block to allow absolute positioning within another container? Or if it is just a headline block to have a 'WIDTH' available to restrict its width when one needs the background just behind the text and not to the full line?

**Comment by elliottmart** [comment]
To clarify,
- need css on nested inner container to make specified sidebar div 'width' work
If we use ‘full width’ on both container and inner container sidebar options of the nested container then  with the Css
.child_container {
position: absolute;
}
the specified width of the nested container is respected and the semi-opaque background ends up just behind any text I have

**Comment by JeanPaiva** [comment]
Closing as this refers to the old container.
