### ISSUE TITLE
Front-End Date Format from ACF Field Does Not Match Return Format Setting

### ISSUE THREAD

**Issue by rockyviewweb** [tomusborne/generateblocks#442]
I set up a date custom field in ACF and selected a return format for that date. But when I manually add that field via GB dynamic data, the front-end display is not in the return format that I had selected. The return format I chose should display as May 11, 2022. But instead, it is showing as 20220511 on the front-end. Is this a GB issue?

![ACF Date Return Format Setting](https://user-images.githubusercontent.com/42782577/167474099-6e243130-021a-478f-9cd4-0dd851d5dfbb.jpg)

![Date Output](https://user-images.githubusercontent.com/42782577/167474112-9fb3a931-1d1c-4d77-b5ab-4fedf20a143c.jpg)

**Comment by JeanPaiva** [comment]
Related to #461
