### ISSUE TITLE
Query Loop - orderby rand

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#446]
### Description
Add orderby rand arg for random ordering of posts

**Comment by tomusborne** [comment]
`rand` isn't a supported value in the REST API for some reason, so it wouldn't work in the editor.

Going to milestone this for 1.6 as we're planning on adding some more items to the REST API that aren't there currently.

**Comment by JeanPaiva** [comment]
@htaitl we don't have a workaround at this given time. But I created another ticket to add a filter for the front-end query, in that case you would have the option to hook the query and add the `rand` order by until we add proper support.

**Comment by JeanPaiva** [comment]
It will be tracked on tomusborne/generateblocks-pro/issues/126

**Comment by htaitl** [comment]
does it mean it will come with the next pro version?

**Comment by JeanPaiva** [comment]
Not necessarily in pro, we are just grouping similar feature requests to stream line better what we will be doing next.
