### ISSUE TITLE
[GB Query loop] Ability to have AJAX pagination

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#450]
It would be nice to be able to have AJAX pagination as well as Load More / Infinite Scroll pagination.

**Comment by tomusborne** [comment]
This is planned for GB Pro: https://github.com/tomusborne/generateblocks-pro/issues/79

**Comment by quantumleap33** [comment]
Ah, I had it opened in the Pro repo, sorry about that!

**Comment by masteradhoc** [comment]
@tomusborne any news on this? Just came up on the facebook group also.

https://www.facebook.com/groups/generatepress/permalink/5573010676087797/
