### ISSUE TITLE
[GB query loop] Dynamic headline term separator color

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#451]
When adjusting the dynamic headline color that displays taxonomies, the term separator is not being affected and instead is assigned a default color.

**Comment by tomusborne** [comment]
The separator is regular text so it's controlled by the text color option in the Headline colors.

Just gave it a test and seemed all good. Let me know if I'm missing something and we can re-open.

**Comment by quantumleap33** [comment]
Apologies, it works fine!
