### ISSUE TITLE
Enqueue styles for blocks added in FSE

### ISSUE THREAD

**Issue by onetrev** [tomusborne/generateblocks#454]
### Description
If you are doing some Full Site Editing (FSE) and add GenerateBlocks blocks to your templates (i.e. header, footer, page templates) everything looks perfect in the backend when editing, but, on the frontend there are no styles applied because the styles for these are not enqueued (I believe that's the problem anyway).

### Steps to reproduce
1. Enable TwentyTwentyTwo theme
2. Appearance -> Editor
3. Edit Template Parts (Footer) or a Page Template
4. Save and view page (in another browser)

#### Expected behaviour
Styles for GenerateBlocks should show up on the front end in your footer or page templates

#### Actual behavior
The styles only show up in the backend. :(

NOTE: I mentioned this to @tomusborne previously and just thought I should add it here so that it's not forgotten. :)

**Comment by tomusborne** [comment]
Thanks for posting the issue here! Really appreciate it.

Will try to come up with a system for this in 1.6.0.
