### ISSUE TITLE
[Query loop] Group by taxonomy

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#455]
A great feature would be the ability to group query loop results by taxonomies.

For example, let's say posts belong to certain categories. It would be able to display results like the following:
Category 1
Post 1
Post 2
.....

Category 2
Post 3
Post 4
....

Category 3
Post 4
Post 5
....

Also the ability to include/exclude posts that belong to multiple categories.

**Comment by quantumleap33** [comment]
@JeanPaiva Sounds awesome, man, looking forward to it!

**Comment by JeanPaiva** [comment]
Will be tracked on https://github.com/tomusborne/generateblocks-pro/issues/125
