### ISSUE TITLE
Filter dynamic content output

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#461]
We need filters for the dynamic content output.

This will come up a lot as people have edge-cases they need to address with the data that returns.

Related: #457

**Comment by rockyviewweb** [comment]
@tomusborne Has this been implemented yet? If so, is there a build that I can download that would have it so I can start using it?

**Comment by JeanPaiva** [comment]
@rockyviewweb this will be release tomorrow with beta 2.

**Comment by tomusborne** [comment]
An example of using this with a meta field:

```
add_filter( 'generateblocks_dynamic_content_output', function( $content, $attributes ) {
    if ( 'post-meta' === $attributes['dynamicContentType'] && isset( $attributes['metaFieldName'] ) ) {
        // Change start_date to your meta field name.
        if ( 'start_date' === $attributes['metaFieldName'] ) {
            return 'Your function to return.';
        }
    }

    return $content;
}, 10, 2 );
```

**Comment by rockyviewweb** [comment]
@tomusborne So, to use this filter, do I need to enter something similar to the code snippet above into the child theme? Or will the functionality include a new field in the block editor options?

**Comment by rockyviewweb** [comment]
@tomusborne Okay, I got it working by adding the code to the child theme and adjusting it a bit. But I do have a question - I am using a date/time custom field. I am wanting to display the date from that field in one place, and the time from that field in another place. Is there any way to filter and display data differently in two different places from the same custom field? For example, in the screenshot below, both the right and left blocks are pulling from the same custom field. But obviously I want to display the date on the left and the time on the right. Any way to do this?

<img width="308" alt="Screen Shot 2022-05-25 at 7 06 42 PM" src="https://user-images.githubusercontent.com/42782577/170394153-ccc99517-3495-4110-9d24-1a377a1f830a.png">
