### ISSUE TITLE
Front-end dynamic filter for users

### ISSUE THREAD

**Issue by MoryCorp** [tomusborne/generateblocks#464]
### Description

I searched the other issues to avoid duplication but I'm not sure if it was requested.

The idea would be to have an AJAX or other filter above the returned pages/posts so that the user can dynamically filter the content according to categories for example.

[Gridbuilder does this](https://demos.wpgridbuilder.com/portfolio/) for example:

![image](https://user-images.githubusercontent.com/26336203/169290855-41c13610-a990-49f7-9edc-8bdd8946c485.png)

**Comment by rockyviewweb** [comment]
This is a nice feature when needed. But not everyone needs this type of facet filtering. Might be better left to plugins like FacetWP or WP Gridbuilder?
