### ISSUE TITLE
Pagination: "Previous" Button is visible even there is no previous post

### ISSUE THREAD

**Issue by swissky** [tomusborne/generateblocks#466]
### Description
When I add the Pagination, I've got the right buttons, but the previous button is also showed when there are no more posts on other sites to show- 

#### References: 

[ignore the design ;)](https://duplom-16977.ove-ams.servebolt.cloud/)

**Comment by quantumleap33** [comment]
I believe this has been resolved in the beta.1 version.

**Comment by swissky** [comment]
saw https://github.com/tomusborne/generateblocks/issues/449

**Comment by swissky** [comment]
@quantumleap33 i use Beta 1 but its still there.
