### ISSUE TITLE
GB/GBP 1.5 beta 1: Query Loop and Learndash cpt crashes the (nested) blocks

### ISSUE THREAD

**Issue by inorbita** [tomusborne/generateblocks#470]
### Description
Selecting a Learndash cpt in the Query Loop block crashes the (nested) blocks. I've tested with a cpt from another 3rd party plugin Events Calendar and it doesn't crash, so the issue appears isolated to Learndash.

### Steps to reproduce
1. With Learndash and GB/GBP beta 1 installed. Add a Query Loop.
2. Select a Learndash cpt, for instance course or lesson.
3. Try to select or edit a nested block within the Query Loop. For instance container or post title block.
4. The blocks] immediately crashes with the message: This block has encountered an error and cannot be previewed.

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----

**Comment by tomusborne** [comment]
Hey @inorbita - I've tried reproducing this but I'm not seeing the issue.

What have you added inside your Query Loop? Does the issue happen if you use one of the default templates when you first add the Query Loop? I've tried a couple of those with no issues.

Thanks!

**Comment by tomusborne** [comment]
Thanks!

@JeanPaiva here's the error:

<img width="440" alt="error" src="https://user-images.githubusercontent.com/20714883/170316626-d3346cef-aa9f-4e40-9bc2-f158a96bf116.png">

This line: https://github.com/tomusborne/generateblocks/blob/release/1.5.0-beta.2/src/extend/dynamic-content/inspector-controls/AuthorMetaControl.js#L21

Should we check for `record.meta` above, or should this line be `record.author.meta` as checked above?

**Comment by JeanPaiva** [comment]
@tomusborne the correct is `record.author.meta` my mistake :sweat_smile:

**Comment by JeanPaiva** [comment]
@inorbita should be fixed for the beta 2 patch that will be released tomorrow. Thanks for testing
