### ISSUE TITLE
[Query loop] Remove Vertical Gap and other customization exclusions

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#474]
I've come across a situation while working with the Query loop where I want to exclude certain customizations from the last element but obviously, it's not possible. In the video, I want to exclude the bottom border from the last item. Would it make sense to have a working solution for this?
https://www.loom.com/share/7699c76739924e2582b0919c81f21856

This also ties with the `Remove Vertical Gap` option inside the query loop. When activated, it has no effect since all grid containers are tied into the same loop but the last item will always have a gap. 

A better solution would be that option to be renamed to `Remove Last Vertical Gap` and only affect the last item.

**Comment by tomusborne** [comment]
As of right now it's not possible to design individual items in the loop differently. It's something on our radar for the future.

Remove Vertical Gap is a bit of an annoying option - I think we can remove it completely by using `row-gap` instead of margins for the vertical gap.

Thanks!

**Comment by quantumleap33** [comment]
@tomusborne I think there is still an issue if I am not mistaken. When the loop block grid has a vertical gap, the last grid item needs to lose it, otherwise you always end up with a vertical gap on the last item.

**Comment by tomusborne** [comment]
As of right now it's not possible. We'll be changing how vertical gap works in 1.6 to improve it.
