### ISSUE TITLE
Dynamic Date- Pagination Translation not working properly.

### ISSUE THREAD

**Issue by cricmania** [tomusborne/generateblocks#475]
Hi
I have just noticed that if we are changing the text of the Pagination button(Previous Page/ Next Page) from English to some other language say Hindi then the text is not displaying properly.

**Comment by tomusborne** [comment]
Hey @cricmania - how are you changing the text? The text itself should be saved to the buttons as regular content, so translations shouldn't have any issues.

**Comment by cricmania** [comment]
@tomusborne on the backend, Text is displaying on the button, but on the frontend instead of the Text it is displaying [??????] This is happening only when the Dynamic Data option is enabled.  Please check the attached screenshot.
<img width="745" alt="Screenshot 2022-05-24 at 09 24 35" src="https://user-images.githubusercontent.com/7187577/169945588-72596674-7191-4bc0-b76e-2355bc9dae5d.png">

**Comment by tomusborne** [comment]
Can you show me a screenshot of the button in the editor?

How is the text being translated on the frontend?

**Comment by cricmania** [comment]
<img width="720" alt="Screenshot 2022-05-25 at 08 38 49" src="https://user-images.githubusercontent.com/7187577/170171648-78022ff0-adc2-4616-bd8d-81d9ce25fc2a.png">
<img width="580" alt="Screenshot 2022-05-25 at 08 39 50" src="https://user-images.githubusercontent.com/7187577/170171769-717cb692-472e-4d57-9493-4ee72698025f.png">

I have attached a screenshot of both the backend and frontend. You can see in the screenshot that for the Previous page I wrote पिछला पेज in the GB Button but on the frontend, instead of the पिछला पेज it's showing [????? ???]

Also Tom, not related to this post, but I have noticed that the ?query path for all the pages is being indexed on Google? How can we exclude/noindex it so that it does not show up on Google? We have already enabled noindex for all the categories,Archives and tags, so I don't know why it's coming up on google searches.

**Comment by tomusborne** [comment]
Thanks for that, very helpful! I believe we have this fixed here: https://github.com/tomusborne/generateblocks/pull/496
