### ISSUE TITLE
display a Custom Field (created with ACF) which has several terms (like a multiselect or a checkbox)

### ISSUE THREAD

**Issue by ghwarrior** [tomusborne/generateblocks#479]
Creating dynamic content blocks…  
...display a Custom Field (created with ACF) which has several terms (like a multiselect or a checkbox)

**Comment by JeanPaiva** [comment]
@ghwarrior its a planned feature for the pro version. Thanks

Related https://github.com/tomusborne/generateblocks-pro/issues/102
