### ISSUE TITLE
decide if you want to display the “value” or the “label” of a custom field (ACF)

### ISSUE THREAD

**Issue by ghwarrior** [tomusborne/generateblocks#480]
Creating dynamic content blocks…  
...decide if you want to display the “value” or the “label” of a custom field (ACF)

**Comment by JeanPaiva** [comment]
Thanks @ghwarrior , will add this to the list of features for the planned ACF integration.

Related https://github.com/tomusborne/generateblocks-pro/issues/102

**Comment by JeanPaiva** [comment]
This was introduced in GenerateBlocks Pro 1.4
