### ISSUE TITLE
Dynamic images need include alt and title data to comply with accessibility regulations

### ISSUE THREAD

**Issue by tomtolkien** [tomusborne/generateblocks#483]
### Description
Dynamic images need to pull the alt/title data from the media gallery to ensure images comply with accessibility regulations such as [WCAG 2.1]. Currently there's no way to use dynamic image data in GP in a way that is compliant with [WCAG 2.1]
### Steps for testing
1.

#### References:
...

-----

**Comment by tomusborne** [comment]
Dynamic images (if pulling from the Media Library) should automatically use the `alt` tag that's associated with the image it's pulling.

I just tried this using a featured image and the `alt` tag for that particular image is coming through in the HTML.

Let us know if there are specific steps to reproduce the issue you're seeing.

Thanks!

**Comment by tomtolkien** [comment]
They don't include alt tags when pulled through the query-loop, for example, when creating a blog section using query-loop, hence the issue raised.

**Comment by eastriverstudio** [comment]
@tomusborne @tomtolkien I've also tested this out and can confirm I get the same as Tom. If I create a page with a query loop with featured images, on the front-end those with alts look to come through OK.

What I have noticed with the GB image block when using it statically though is if I add the block and it has an alt it gets pulled in correctly. However if I later update the alt in the media library it doesn't update on the image block. Is this behaviour expected? 

I would have thought updating it in the media library would have updated it on the image block, particularly if I've not updated the alt locally at the block level.

**Comment by tomusborne** [comment]
Static images are saved and served as static HTML, so they won't update dynamically if you change their data. Only dynamic images can do that.

Thanks for testing this @eastriverstudio - appreciate it!

**Comment by eastriverstudio** [comment]
@tomusborne No problem and thanks for clarifying about the static vs dyanmic alts. I must have been thinking back to the way images & alts worked in the old wysiwyg editor not blocks!

**Comment by tomusborne** [comment]
I'm going to go ahead and close this as we're seeing the `alt` attribute come through on dynamic images (inside and outside of the Query Loop).

@tomtolkien Please feel free to report back if you don't believe this is fixed.

Thanks!
