### ISSUE TITLE
Image Block: Lighthouse flags img elements that don't have alt attributes

### ISSUE THREAD

**Issue by Thornbrand** [tomusborne/generateblocks#484]
[Lighthouse expects](https://web.dev/image-alt/) all `<img>` elements to include an `alt` attribute, even for decorative images wihtout `alt` text.

`<img src="..." alt="">`

The default WordPress image block produces `<img src="..." alt>`, which is evidently also acceptable. 

The GB Image Block is not currently generating the `alt` attribute for images with no alt text. Lighthouse flags this as a failing element for Accessiblity/SEO. 

`<img src="..." >`

**Comment by tomusborne** [comment]
Thanks for reporting this! Should be fixed in #485
