### ISSUE TITLE
[GB beta] Strange button alignment in backend responsive views

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#489]
Button alignment does not preview properly on responsive views. Looks fine on the backend.
https://www.loom.com/share/7378e9a52cfb4bc0bc310dfc2c554ab4

Here is another one. The button seems to be center-aligned in responsive previews.
https://www.loom.com/share/8d120ee3fa484bfaa77f29ce49cf494f

**Comment by tomusborne** [comment]
Strange, can't get this to happen. Can you share the code for the button so I can see it happen on my end?

**Comment by quantumleap33** [comment]
Here you are.

`<!-- wp:generateblocks/container {"uniqueId":"0b9a4095","paddingTop":"120","paddingRight":"40","paddingBottom":"120","paddingLeft":"40","paddingTopTablet":"100","paddingBottomTablet":"100","paddingTopMobile":"80","paddingRightMobile":"30","paddingBottomMobile":"80","paddingLeftMobile":"30","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/headline {"uniqueId":"ae368e73","alignment":"center","textTransform":"uppercase"} -->
<h2 class="gb-headline gb-headline-ae368e73 gb-headline-text">Meet our team</h2>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/headline {"uniqueId":"2d5231ba","element":"p","alignment":"center","textColor":"var(\u002d\u002dcontrast-3)","marginBottom":"60","paddingRight":"120","paddingLeft":"120","paddingRightTablet":"40","paddingLeftTablet":"40","paddingRightMobile":"0","paddingLeftMobile":"0"} -->
<p class="gb-headline gb-headline-2d5231ba gb-headline-text">Etiam nec velit eu elit condimentum elementum quis non sem. Etiam non tortor sed nisl fermentum tempor id id arcu. Praesent sodales laoreet enim non aliquam. Nunc commodo tellus sapien, eget tincidunt sem semper eu.</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/grid {"uniqueId":"592eeefe","columns":4,"horizontalGap":30,"verticalGapTablet":80,"horizontalAlignmentMobile":"inherit","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/container {"uniqueId":"5ed5f8fb","isGrid":true,"gridId":"592eeefe","width":25,"widthTablet":50,"widthMobile":100,"alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/image {"uniqueId":"e9a07f50","mediaId":1671,"sizeSlug":"large","marginBottom":"15"} -->
<figure class="gb-block-image gb-block-image-e9a07f50"><img class="gb-image gb-image-e9a07f50" src="https://library.generateblocks.com/wp-content/uploads/2020/07/test-6.jpg"/></figure>
<!-- /wp:generateblocks/image -->

<!-- wp:generateblocks/headline {"uniqueId":"14fa0942","element":"p","borderColor":"var(\u002d\u002dbase)","fontWeight":"700","marginBottom":"5","paddingBottom":"15","borderSizeBottom":"2"} -->
<p class="gb-headline gb-headline-14fa0942 gb-headline-text">Sharon Lane</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/headline {"uniqueId":"b0683f6d","element":"p","textColor":"var(\u002d\u002dcontrast-3)","fontWeight":"500","fontSize":14,"textTransform":"uppercase","marginBottom":"30"} -->
<p class="gb-headline gb-headline-b0683f6d gb-headline-text">Marketing director</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/button-container {"uniqueId":"b7bda231","alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/button {"uniqueId":"8aaf1589","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-8aaf1589" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 320 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"8a89d83e","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","marginRightTablet":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-8a89d83e" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"fed4933c","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-fed4933c" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->
<!-- /wp:generateblocks/button-container -->
<!-- /wp:generateblocks/container -->

<!-- wp:generateblocks/container {"uniqueId":"6285de0c","isGrid":true,"gridId":"592eeefe","width":25,"widthTablet":50,"widthMobile":100,"alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/image {"uniqueId":"f0c09b22","sizeSlug":"large","marginBottom":"15"} -->
<figure class="gb-block-image gb-block-image-f0c09b22"><img class="gb-image gb-image-f0c09b22" src="https://library.generateblocks.com/wp-content/uploads/2020/07/test-2.jpg"/></figure>
<!-- /wp:generateblocks/image -->

<!-- wp:generateblocks/headline {"uniqueId":"afdf6ba5","element":"p","borderColor":"var(\u002d\u002dbase)","fontWeight":"700","marginBottom":"5","paddingBottom":"15","borderSizeBottom":"2","opacities":[],"transitions":[],"boxShadows":[],"transforms":[],"textShadows":[],"filters":[]} -->
<p class="gb-headline gb-headline-afdf6ba5 gb-headline-text">Sheila Johnson</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/headline {"uniqueId":"870dc09a","element":"p","textColor":"var(\u002d\u002dcontrast-3)","fontWeight":"500","fontSize":14,"textTransform":"uppercase","marginBottom":"30"} -->
<p class="gb-headline gb-headline-870dc09a gb-headline-text">UI deisgner</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/button-container {"uniqueId":"97e2f79c","alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/button {"uniqueId":"528107c2","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-528107c2" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 320 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"95b6c902","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-95b6c902" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"de3e908f","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-de3e908f" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->
<!-- /wp:generateblocks/button-container -->
<!-- /wp:generateblocks/container -->

<!-- wp:generateblocks/container {"uniqueId":"be86403b","isGrid":true,"gridId":"592eeefe","width":25,"widthTablet":50,"widthMobile":100,"removeVerticalGapTablet":true,"alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/image {"uniqueId":"529a098b","sizeSlug":"large","marginBottom":"15"} -->
<figure class="gb-block-image gb-block-image-529a098b"><img class="gb-image gb-image-529a098b" src="https://library.generateblocks.com/wp-content/uploads/2020/07/test-7.jpg"/></figure>
<!-- /wp:generateblocks/image -->

<!-- wp:generateblocks/headline {"uniqueId":"ff658830","element":"p","borderColor":"var(\u002d\u002dbase)","fontWeight":"700","marginBottom":"5","paddingBottom":"15","borderSizeBottom":"2","opacities":[],"transitions":[],"boxShadows":[],"transforms":[],"textShadows":[],"filters":[]} -->
<p class="gb-headline gb-headline-ff658830 gb-headline-text">Kim Wild</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/headline {"uniqueId":"cdfe9ca1","element":"p","textColor":"var(\u002d\u002dcontrast-3)","fontWeight":"500","fontSize":14,"textTransform":"uppercase","marginBottom":"30"} -->
<p class="gb-headline gb-headline-cdfe9ca1 gb-headline-text">SEO expert</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/button-container {"uniqueId":"bbeb055c","alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/button {"uniqueId":"7cc68e90","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-7cc68e90" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 320 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"74669534","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-74669534" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"b487b334","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-b487b334" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->
<!-- /wp:generateblocks/button-container -->
<!-- /wp:generateblocks/container -->

<!-- wp:generateblocks/container {"uniqueId":"11c1205e","isGrid":true,"gridId":"592eeefe","width":25,"widthTablet":50,"widthMobile":100,"removeVerticalGapTablet":true,"removeVerticalGapMobile":true,"alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/image {"uniqueId":"bbc9d570","sizeSlug":"large","marginBottom":"15"} -->
<figure class="gb-block-image gb-block-image-bbc9d570"><img class="gb-image gb-image-bbc9d570" src="https://library.generateblocks.com/wp-content/uploads/2020/07/test-3.jpg"/></figure>
<!-- /wp:generateblocks/image -->

<!-- wp:generateblocks/headline {"uniqueId":"0742c2f5","element":"p","borderColor":"var(\u002d\u002dbase)","fontWeight":"700","marginBottom":"5","paddingBottom":"15","borderSizeBottom":"2","opacities":[],"transitions":[],"boxShadows":[],"transforms":[],"textShadows":[],"filters":[]} -->
<p class="gb-headline gb-headline-0742c2f5 gb-headline-text">George Andrews</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/headline {"uniqueId":"8a0e48a0","element":"p","textColor":"var(\u002d\u002dcontrast-3)","fontWeight":"500","fontSize":14,"textTransform":"uppercase","marginBottom":"30"} -->
<p class="gb-headline gb-headline-8a0e48a0 gb-headline-text">SEO analysts</p>
<!-- /wp:generateblocks/headline -->

<!-- wp:generateblocks/button-container {"uniqueId":"654954e6","alignmentMobile":"center","isDynamic":true,"blockVersion":2} -->
<!-- wp:generateblocks/button {"uniqueId":"172ea91e","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-172ea91e" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 320 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"0b1b8296","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","marginRight":"10","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-0b1b8296" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->

<!-- wp:generateblocks/button {"uniqueId":"4e316bc7","hasUrl":true,"hasIcon":true,"removeText":true,"backgroundColor":"var(\u002d\u002daccent)","backgroundColorHover":"var(\u002d\u002daccent-2)","textColor":"var(\u002d\u002dbase-2)","textColorHover":"","paddingTop":"10","paddingRight":"10","paddingBottom":"10","paddingLeft":"10","borderRadiusUnit":"em","blockVersion":2} -->
<a class="gb-button gb-button-4e316bc7" href="#"><span class="gb-icon"><svg aria-hidden="true" role="img" height="1em" width="1em" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"></path></svg></span></a>
<!-- /wp:generateblocks/button -->
<!-- /wp:generateblocks/button-container -->
<!-- /wp:generateblocks/container -->
<!-- /wp:generateblocks/grid -->
<!-- /wp:generateblocks/container -->`

**Comment by quantumleap33** [comment]
Here you are:
https://we.tl/t-65ZKivJH5n

**Comment by tomusborne** [comment]
Hmm, not seeing it.

<img width="860" alt="buttons" src="https://user-images.githubusercontent.com/20714883/170137506-4cab13ff-3781-443b-974f-3e7ffddb4ad8.png">

Anything I need to do to replicate?

**Comment by quantumleap33** [comment]
What WP and GP/GPP GB/GBPro versions are you testing?

**Comment by tomusborne** [comment]
WP: 6.0
GP: 3.2.0 branch
GPP: 2.2.0 branch
GB: 1.5.0-beta.2 branch
GBP: 1.2.0-beta.1 branch

**Comment by quantumleap33** [comment]
@tomusborne I don't understand, I have the same stack. I tried in an Incognito window, no addons, also in Firefox. When I set a right margin on the last button, it works but not when I remove it.
https://www.loom.com/share/1d70ed6b6a67472cbfc818e570ad4cb6
