### ISSUE TITLE
Menu Items are not updated - on Block Elements created with GB

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generateblocks#490]
If you have a menu with different pages and you insert that to elements block. if you go and delete/update one menu item will not be displayed in the front end.

**Comment by tomusborne** [comment]
Just tested this and I don't believe it's GB/GPP related. The same things seems to happen if you add the Navigation block to a static page and then update the menu later. Perhaps it's being saved as static HTML?

Going to close this for now, but feel free to re-open if you think it's something we need to look at more.

Thanks!
