### ISSUE TITLE
Button with dynamic link displays as text link on front-end

### ISSUE THREAD

**Issue by rockyviewweb** [tomusborne/generateblocks#500]
### Description
If I set a dynamic link for a button using the new dynamic data panel in the block settings, that button displays as a text link on the front end.

The weird thing is that in a GP element, I can set the dynamic link using the GP dynamic link option in the block toolbar (not the new GB dynamic data panel), and it displays correctly as a button on the front end. But if I switch to trying to set the dynamic data via the new dynamic data panel, it causes the button to display on the front-end as a text link.

In the query loop, the GP dynamic data option is not available in the toolbar, so using that is not a workaround to get the button to display properly.

### Steps to reproduce
1. Add a button to the query loop or an element.
2. Select a global style for the button.
3. Add static text for the button text.
4. Set button link type in the dynamic data panel to single post.
5. Publish/update.
6. View front end - "button" displays as a text link.

#### Expected behavior
The button should display on the front end as a button using the selected global style.

#### Actual behavior
Button displays on the front end as a text link.

#### References: 
See screenshots below.

-----
<img width="985" alt="Screen Shot 2022-05-25 at 10 46 32 PM" src="https://user-images.githubusercontent.com/42782577/170418681-5b02046a-1d3a-4f8f-a609-b4db211ab0a4.png">

<img width="346" alt="Screen Shot 2022-05-25 at 10 54 39 PM" src="https://user-images.githubusercontent.com/42782577/170418768-01685247-f912-40fe-bf46-ece5c1b95650.png">

**Comment by tomusborne** [comment]
Thanks for reporting this! Will be fixed in GB Pro 1.2.0-beta.2.

**Comment by rockyviewweb** [comment]
I'm not sure if this is related or not - but I have run into an issue where I have social media icons created with the GB buttons block. I have a color and hover color set and the colors appear correct in edit mode. But on the front-end, the icons are showing as white, but then show the correct color on hover. So somehow it is as if the normal state color didn't display correctly. These buttons are in a footer element. I did correct the behavior with some CSS by using Microthemer. But I would like to get them to display correctly without having to add additional CSS.

**Comment by tomusborne** [comment]
I don't believe that's related to this particular issue. Any chance you can open a new issue for it?

Thanks!
