### ISSUE TITLE
Wordpress 6.0 and Grid Options

### ISSUE THREAD

**Issue by kaktux** [tomusborne/generateblocks#501]
Grid selection overview broken in Wordpress 6.0
...

### Steps to reproduce
Update to Wordpress 6.0

#### Expected behavior
normal overview for grid selection

#### Actual behavior
broken overview

I tested on 3 installations on 2 servers. First was unsure - but then i reproduced with a test installation.

Fastest explanation is to show pictures:

Theme: Generatepress
Plugins active: Generatepress premium , Generateblocks

Before (wordpress 5.9).
![beforeupdate](https://user-images.githubusercontent.com/6649301/170471247-4adf3ff6-2c6a-4a4a-90ef-e932b8891889.png)

After update to Wordpress 6.0 same installation, browser, everthing (just 1 min later), creating empty page and adding grid block looks like this:
![afterupdate](https://user-images.githubusercontent.com/6649301/170471354-d25804a8-626e-4b2d-bedd-50d85b71d110.png)

The block works like normal - but the selection view is - as shown - broken
can anyone else confirm this behaviour?

Tested on Linux with current chromium + firefox.

**Comment by quantumleap33** [comment]
@kaktux A fix is on the way, meanwhile see [here](https://community.generateblocks.com/t/raster-preview-messy-after-update-to-wordpress-6-0/690/4?u=tom).

**Comment by JeanPaiva** [comment]
@kaktux This was already fixed on https://github.com/tomusborne/generateblocks/pull/497, it will be release on the next patch scheduled for Tuesday. Thank you for taking the time to open the ticket.

**Comment by rockyviewweb** [comment]
I noticed this issue as well the other day. Glad to hear it has already been fixed! Thank you team for your work on this great plugin!
