### ISSUE TITLE
Dynamic data - allow classes, IDs and attributes to be populated dynamically

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#505]
I’d like to suggest an enhancement to the dynamic data features to allow classes, IDs and custom attributes to be populated dynamically.

This would open up a lot of extra possibilities for various use cases in content templates and query loops where it would be handy to set additional classes etc to blocks based on some dynamic values.

To make this completely flexible, I think before and after fields would be required to prepend or append a static string if needed, but I think this has already been suggested for the dynamic data feature in general. 

Thanks

**Comment by JeanPaiva** [comment]
Will be handled by https://github.com/tomusborne/generateblocks-pro/issues/127
