### ISSUE TITLE
Ability To Display Items In Query Loop from Multiple Post Types

### ISSUE THREAD

**Issue by rockyviewweb** [tomusborne/generateblocks#507]
Currently, the query loop forces me to choose a post type. But what if I want to display items from multiple post types in one query loop? For example, display a query loop on a homepage with the latest or featured blog posts, events, products, etc. I think this would work well if I could set the query loop to show a taxonomy term instead of a post type. I know I can add additional parameters to only display a certain taxonomy, but those are within the constraint of the post type selected above. So it would be nice if I could add a taxonomy term (or maybe a tag) for "Latest" and display anything with that term/tag from any post type in a query loop.

**Comment by JeanPaiva** [comment]
@rockyviewweb we have already logged such request for multiple post types on a single query loop. For sure is something we want to enable for the future. Thanks
