### ISSUE TITLE
Image block - duplicating an image block and using replace image doesn't seem to work

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#516]
### Description
Adding an image block, adding settings and then duplicating it and using the replace image option in toolbar doesn't seem to update the image in the editor, so it is not clear if it has updated or not.

### Steps to reproduce
1. Add an image block, give it some style settings
2. Duplicate the image block and try to use the replace image option on toolbar
3. Choose an image from the media library popup 
4. See if image updates in the editor

#### Expected behavior
Image should update in the editor when replaced with a new image from media library.

**Comment by tomusborne** [comment]
Hey @eastriverstudio - here's what I'm experiencing:

https://user-images.githubusercontent.com/20714883/171027524-1d8603fc-0e95-43d5-a83a-e2b18284e628.mp4

Am I missing a step?

Thanks!

**Comment by eastriverstudio** [comment]
@tomusborne sorry actually I experienced this issue in an Elements block element, does that make a difference for you?

**Comment by eastriverstudio** [comment]
@tomusborne video link here to demonstrate in the block element if that helps: https://share.cleanshot.com/PJqIPn

**Comment by eastriverstudio** [comment]
@tomusborne playing around with this some more the problem appears to be related to when there's dyanmic data on the image block, in my case a dyanmic link from post meta. If I remove the dynamic link option I can duplicate the image and update it as expected.
