### ISSUE TITLE
Dynamic content error when title is not supported

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#519]
Received the following from a user in our support:

![Screen-Shot-2022-05-26-at-9-05-39-PM](https://user-images.githubusercontent.com/20714883/171084028-65710ed6-4339-49d2-ae99-7f80be90e170.png)

We check for `title`, but not `title.raw`. I wasn't able to reproduce, but we should look at hardening the check.

**Comment by JeanPaiva** [comment]
I believe you fixed this https://github.com/tomusborne/generateblocks/blob/release/1.5.0-beta.2/src/extend/dynamic-content/utils/getContent.js#L72

**Comment by tomusborne** [comment]
That's what I thought as well but the user is experiencing this is beta.1 and that check exists in beta.1: https://github.com/tomusborne/generateblocks/blob/release/1.5.0/src/extend/dynamic-content/utils/getContent.js#L73

**Comment by JeanPaiva** [comment]
@tomusborne we can go like this:
```js
const title = isObject( record.title ) ? ( record.title.raw || record.title.rendered ) : record.title;
return title || __( 'No post title.', 'generateblocks' );
```

**Comment by tomusborne** [comment]
Seems pretty safe. It's tough because I can't reproduce the reported error. It was a CPT with no title support, but if I set that up our current check works fine.
