### ISSUE TITLE
Add uniqueId control to allow custom class names

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generateblocks#521]
### Description

It would be solid if there is a feature that you can name if you want the generated div elements that are created from Generateblocks. 

So instead of something like this which is not clean - > gb-container-cc53fb6a

To something like this - > gb-container-custom-name

**Comment by JeanPaiva** [comment]
Will be tracked by https://github.com/tomusborne/generateblocks-pro/issues/214
