### ISSUE TITLE
Jetengine CPT and CCT

### ISSUE THREAD

**Issue by eliquame** [tomusborne/generateblocks#529]
### Description
Jetengine CPT nothing work with Generatepress Query builder
### Steps to reproduce
1. 
Cant select any CPT's meta field
And the query builder sometimes nothing show, only blank page. Sometimes show the list, BUT, repeat one post (because i have to select a source post, to see in editor the datas.

Sometimes i add an background color to the container, not working the query builder in public side. If i delet the bkgd color, working again.

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----

**Comment by JeanPaiva** [comment]
The meta fields may not appearing cause they are not enabled in the rest API, but still you should be able to manually type their names, you won't have live preview tho, cause they need to be on the REST API response. But should work in the front-end. For the next version we will have better support for custom fields.

The other issues I can't really test as I don't have a license for the plugin. I'll close this ticket, but feel free to open again if still experiencing those issues.
