### ISSUE TITLE
Query Loop - Posts per Page limit 100

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#535]
### Description
The WordPress REST API `per_page` is capped at 100 posts:

https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/#pagination-parameters

We should set this as the limit in the Query Loop Posts per Page field to stop `400` bad request errors in the console and reduce the risk of `no results found` being returned in the editor.

### Steps to reproduce

1.  Add a Query Loop
2. Open dev tools.
3. Increase Post per Page to a 101 or greater
4. Check for Console error

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----

**Comment by diggeddy** [comment]
Question is whether we should limit the field or just display a warning, or just keep a note in the docs.
For reference this is where issue came from  - user wanted 500+ posts:

https://generatepress.com/forums/topic/query-loop/#post-2244803

See my reply for the filter that provides an increase to the max posts

**Comment by tomusborne** [comment]
I think we should limit the API in the editor to something like `50` to prevent performance issues. This limit would only apply in the editor of course, and would only apply to each individual Query Loop block.
