### ISSUE TITLE
Headline when is paragraph does not work with font system of Generatepress

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generateblocks#548]
BETA2 

Trying to make the Paragraphs on mobile as 15pixels and it does not update my staging site which is created with Generateblocks..

Recreate this with - 

Add a new container and inside a choose a GB headline and make it as paragraph - go to customizer choose mobile devices and change its font size.

***This is happening on mobile devices.

**Comment by FunkyCss** [comment]
I am using Generatepress typography system and GBP and GB beta - no other plugins.

The selector is body and it works perfectly fine for PC but on mobile I cant see the changes on anything is made with GB..

The other parts of the website are effected with the change

**Comment by tomusborne** [comment]
Can you link me to a page where I can see the issue?

**Comment by FunkyCss** [comment]
https://www.thelocalscocktails.com/

**Comment by FunkyCss** [comment]
Sorry I forgot to mention that, I did this to make my mobile device paragraph 15px but still this didnt work.. 

I removed that line of CSS for now - can you check again ?

P.S. the font changes on mobile does not work on customizer preview also (mobile)

**Comment by tomusborne** [comment]
I'm seeing more custom CSS here:

<img width="1338" alt="font-size-2" src="https://user-images.githubusercontent.com/20714883/172683179-1203eb4e-6ec6-49e3-90b6-1eb54482ec60.png">

**Comment by FunkyCss** [comment]
If i go inside the GB editor it has 17px in both devices PC and Mobile..
