### ISSUE TITLE
Dynamic data - allow post meta to return rich/pre formatted text as well as simple strings

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#552]
At the moment using the dynamic data feature and post meta option is limited to unformatted text strings.

I ran into a scenario where I needed to have a custom field contain rich / formatted text with line breaks etc to populate a block element template. However this doesn’t work with the post meta option currently, even though the field was set to return formatted text. 

I did also consider if might be able to solve it with GP’s dynamic content block, but unfortunately that doesn’t have post meta as an option either.

Therefore I’d like to suggest an enhancement to GB’s dynamic post meta option to toggle or allow pre formatted text if we need it. 

I believe this would allow more flexibility for creating dynamically populated block elements with more than just simple text and short paragraphs. 

Thanks

**Comment by madanpraba** [comment]
In addition, it would be more functional to convert the date field from Timestamp to a date format or other date format.

**Comment by JeanPaiva** [comment]
@eastriverstudio we still have lot to do regarding post meta and formatting is one of them. For the next versions we will be improving post meta so you could have more control over the data returned. Closing this one as we already have an issue for advance post meta features.

Reference https://github.com/tomusborne/generateblocks-pro/issues/102
