### ISSUE TITLE
Elementor Active - Query builder not working!

### ISSUE THREAD

**Issue by eliquame** [tomusborne/generateblocks#563]
### Description
If the Elementor plugin is active (Pro or Free version) The Generateblocks Query Builder not working with Gutenberg.
If turn off Elementor, The query builder is wokring perfectly in Gutenberg editor!

("No Result Found" error message)

### Steps to reproduce
1. 

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----

**Comment by diggeddy** [comment]
Hi @eliquame i am unable to replicate the issue with the Free version of Elementor installed.
Do you have any other plugins installed ? And what are the steps we need to follow to reproduce ?

**Comment by eliquame** [comment]
Hi!
Sorry, it was my foult. Not the elementor the problem, another third party extension.
