### ISSUE TITLE
Spacing - negative left/right margins now not displayed in editor correctly

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#578]
In the latest GB rc2 using left/right negative margins on GB blocks like headline or container are not displaying correctly in the editor. They look as they should on the frontend so it appears blocks with negative margin spacing styles set are not being rendered correctly in the editor view. Looking at the editor css it appears to be this line which is causing the problem:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/37620756/173968539-f5a612c2-a48e-4871-bfe3-68f0cede0bb6.png">
...

### Steps to reproduce
1. Add a container with a headline/container block nested inside
2. Add some left or right negative margin to the nested headline/container block
3. The nested blocks don't fill the available space correctly anymore due to above style rule.

#### Expected behavior
Applying the left/right negative margins should correctly allow the element to fill the outer container and spill out of it to create desired negative margin offset effects. 

Thanks

**Comment by tomusborne** [comment]
Hey @eastriverstudio - not sure I'm experiencing this. Can you share the code from your editor so I can paste it into mine and check?

Thanks!

**Comment by eastriverstudio** [comment]
@tomusborne hopefully this is what you need? In the below I have a two grid containers. On the left there's a nested headline block with some negative right margin and in the right column container with an image that has left and right negative margins applied. On the frontend they fill the available space and spill out of containers as expected but in the editor they do not because of the max-width style rule that is being applied by the .wp-block class.





<h1 class="gb-headline gb-headline-9abef96f gb-headline-text">We provide premium, performant website design and marketing services for businesses to grow</h1>



<h2 class="gb-headline gb-headline-5b6e5131 gb-headline-text">The work we do is inspired by where we live and the vibrant coastal communities around us. We are passionate about helping other businesses succeed and we specialise in creating clean and purpose driven solutions that are focused on delivering results.</h2>




<a class="gb-button gb-button-bd07cb34 gb-button-text gb-button-primary" href="https://eastriver.studio/contact/">Enquire about a project</a>



<a class="gb-button gb-button-bfafa480 gb-button-ghost" href="https://eastriver.studio/website-plans/"><span class="gb-button-text">See our website plans</span><span class="gb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M4 8v0c0-.28.22-.5.5-.5h5.79L8.14 5.35v0c-.2-.2-.2-.52 0-.71 .19-.2.51-.2.7 0l3 3v0c.19.19.19.51 0 .7 -.01 0-.01 0-.01 0l-3 3v0c-.2.19-.52.19-.71 0 -.2-.2-.2-.52-.001-.71l2.14-2.15h-5.8v0c-.28 0-.5-.23-.5-.5Z" fill-rule="evenodd"></path></svg></span></a>






<figure class="gb-block-image gb-block-image-24851c01"><img class="gb-image gb-image-24851c01" src="https://eastriver.studio/wp-content/uploads/2022/05/coastal-landscape-hero-scene-1024x638.png" alt="Website design and marketing Exeter, Devon" title="coastal-landscape-hero-scene"/></figure>

**Comment by tomusborne** [comment]
@eastriverstudio Thanks for that! Which theme/version are you seeing this with? If I add this to GP (stable), it works. However, if I add it to GP 3.2 (dev), I see the issues.

**Comment by eastriverstudio** [comment]
@tomusborne strange as I'm running the latest stable version GP 3.1.3

**Comment by tomusborne** [comment]
Can you show me a screenshot of what you're seeing?

**Comment by eastriverstudio** [comment]
@tomusborne sure, first shot is the editor view:

https://share.cleanshot.com/wAmygZ

Second is the frontend where the negative margin is correctly applied and elements spilling out of container as desired:

https://share.cleanshot.com/XJJgvi

Hope these help?

**Comment by tomusborne** [comment]
Strange, here's what I'm seeing:

<img width="1920" alt="negative-margins" src="https://user-images.githubusercontent.com/20714883/174133570-b4cf9e2f-a205-4375-bbf5-5ecbacb99326.png">

Using:

GP 3.1.3
GPP 2.1.2
GB 1.5.0-rc.2
GBP 1.2.0-rc.1

Same for you?

**Comment by eastriverstudio** [comment]
@tomusborne hmm that’s weird then as I’m definitely using the same versions as you. 

It is a standard page using the full-width editor layout setting. I’ll revisit the other plugins and see if there’s anything else which could be adding the max- width setting to .wp-block class which seems like the cause. I assume as it is displaying ok for you you are not seeing this rule applied?

**Comment by tomusborne** [comment]
Aha, are you using a Layout Element in GPP? That should be the issue here. Checking it out.

**Comment by eastriverstudio** [comment]
@eastriverstudio Yes I am. Using a full width layout element.

Also not sure if this is GP or GB related but noticed also having another issue when using a layout element. If I use the exclude option to exculde certain pages from the full width layout element (I'm using categories) the editor view width is still full-width, might not be exactly related to this issue but thought it was worth mentioning.

**Comment by tomusborne** [comment]
This issue should be fixed in rc.3 which we're about to release.

The second issue sounds more like a GP bug - an issue over there would be awesome if possible.

Thanks!

**Comment by tomusborne** [comment]
Latest version is now available here: https://generateblocks.com/generateblocks-1-5-dynamic-data-query-loops-image-blocks/

Thanks again!

**Comment by eastriverstudio** [comment]
@tomusborne awesome thanks for looking in to this. I'll install the latest release and let you know if it resolves it this end.

As for the other layout element problem, no problem I'll get one added.

**Comment by eastriverstudio** [comment]
@tomusborne just to confirm installed latest rc3 and the editor view elements with negative margins now match the frontend as expected. Thanks again

**Comment by tomusborne** [comment]
Thanks for letting me know!
