### ISSUE TITLE
Feature Request: Add "inline element" style to CSS print method. 

### ISSUE THREAD

**Issue by ejcabquina** [tomusborne/generateblocks#58]
Context:
https://wordpress.org/support/topic/inline-background-image/

To be able to lazyload background images. 
https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket

**Comment by Mahmoud-AbdEllFttah** [comment]
Is there anything new here?
**I hope it's updated from the gentlemen here.**

**Comment by Mahmoud-AbdEllFttah** [comment]
Has the problem been resolved ?
**That's really cool.**
