### ISSUE TITLE
custom key and custom value in the query parameters

### ISSUE THREAD

**Issue by madanpraba** [tomusborne/generateblocks#580]
Description
For query parameters, the option to add custom keys and values would be more helpful for developers.
For example, when we use facet filters from plugins, we need to add custom key attributes to filter the query content. In wp-gridbuilder plugin, the facet filter function on custom pages, we need to add '''wp_grid_builder''' = > 'wpgb-content-1''' in the query parameters to filter the query content. 

References:
https://docs.wpgridbuilder.com/resources/guide-filter-custom-queries/

**Comment by JeanPaiva** [comment]
Hey @madanpraba can you check the filter `generateblocks_query_loop_args` which will filter the WP_Query arguments before rendering the front-end.

https://github.com/tomusborne/generateblocks/blob/release/1.5.0/includes/class-render-blocks.php#L416

Closing this issue feel free to open it again if still not what you are looking for.
