### ISSUE TITLE
Auto Label on Headline pulling data from ACF field

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#582]
### Description
Currently when headlne dynamic data pulls from custom field (ACF in my case) the label we see in editor says "Post Meta". This is not super usefull as it gives no indication of what field the data is coming from. If I remember correctly, version 1.4 of GB at least allowed one to type manually the label that is going to be in the editor.

### Steps for testing
1. Make a custom field. Fill in the data for the field, save the post.
2. Make a headline block, enable dynamic data, select post meta, type name of field, save post

#### References:
1. If yould be best if the label would produce the same string it will produce on the front end.
2. Alternatively, it yould at least show the custom field name value, slug value.
3. At least bring back the ability to type what is going to be in the editor so it is not always "Post meta"

-----

**Comment by JeanPaiva** [comment]
@thisbit we have plans to improve custom fields, including ACF, in the next versions.

For the time being, we have a filter in which you can add the ACF fields to your list of meta fields. Below there are the steps to do it:

- Enable your ACF field on the API in the fields settings (**Show in REST API**)
- Create a JS file and add the following code:

```js
function enableAdvancedCustomFields( record ) {
	if (
		_.isObject( record ) &&
		( _.has( record, 'acf' ) && _.isObject( record?.acf ) ) &&
		( _.has( record, 'meta' ) && _.isObject( record?.meta ) )
	) {
		const meta = Object.assign( {}, record?.meta, record?.acf );
		return Object.assign( {}, record, { meta } );
	}
	return record;
}

wp.hooks.addFilter(
	'generateblocks.editor.postRecord',
	'generateblocks-pro/dynamic-content/post-record',
	enableAdvancedCustomFields
);
```

- Add the current PHP snippet to your child theme `functions.php`

```php
function generateblocks_enable_acf() {
    wp_enqueue_script( 'gb-enable-acf', get_template_directory_uri() . '/assets/js/acf.js', array(), '1.0.0', true );
}
add_action( 'admin_init', 'generateblocks_enable_acf' );
```

This should display your post meta fields in the editor
![image](https://user-images.githubusercontent.com/7506830/174692017-763e3bf0-fcae-4de2-8aea-d9b5da4e74ef.png)

**NOTE** The meta field formats are not supported yet, but for simple text and number values should work just fine. In future version we will add more support.

**Comment by thisbit** [comment]
Thanks @JeanPaiva but this seems to work only if the fields are linked to Current Post. However I have a CPT "Global Data", where I store globaly relevant fields, and then pull them from arround the site, using Headline (these are all text fields, email fields, url fields ... so they all work with headline, just do not display in editor).

**Comment by thisbit** [comment]
Also, if I keep using this snippet (at least for current post fields) should I remove it later when update comes that resolves this? Or it will have no influence?

**Comment by JeanPaiva** [comment]
Currently we only support fields related to the post, but it totally make sense to enable a way for the user to use global meta fields for shared information.

This snippet is a temporary solution for you to be able to use ACF fields in version 1.5 until we work on a proper integration and better support for meta fields. Once we release this updates would be better for you to remove it, since we are planning to add field formation and other goodies.
