### ISSUE TITLE
 Query loop and infinite scrolling are confused

### ISSUE THREAD

**Issue by dxhei** [tomusborne/generateblocks#583]
### Description
...In the marketing topic, query loop and infinite monitoring are confused. I found this problem. I rebuilt the new website test. The paged navigation scrolled infinitely. I created a container including query loop on the home page and put it on the top without setting any parameters. I cycled two posts for testing. When I click infinite scroll, it loads in the container, not under the page.

### Steps to reproduce
1. 

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----

**Comment by JeanPaiva** [comment]
Hey @dxhei I'm not quite understand your problem, can you provide me a link to your site or maybe some images and videos?
