### ISSUE TITLE
custom taxonomy query

### ISSUE THREAD

**Issue by lumpyka** [tomusborne/generateblocks#584]
I'd like to create CPT-category archive pages, but not able to list taxonomies, only posts with the query loop modul. And I try to make listing item template for that loop, but also not able to query taxonomy custom fields using dynamic element blocks. It would be nice to have the option to choose custom taxonomy as data source.
...

**Comment by JeanPaiva** [comment]
@lumpyka if I understand correctly your custom meta fields are not displaying in the editor, correct?

If that's the case you have two options for now:

1 - Manually add the meta slug to the select field. The downside of this is that will not have live preview in the editor.
![image](https://user-images.githubusercontent.com/7506830/174692828-064fcdd6-96e1-4f35-a3e1-4957b17f270e.png)

2 - Enable your custom field to show in the REST API. This will give you live preview in the editor. [Check documentation for more information](https://developer.wordpress.org/reference/functions/register_meta/#parameters)

**Comment by lumpyka** [comment]
Thanks for the reply! I attach what I really mean. I don't know whether your suggestion solve this. 
![generate-blocks-query-loop](https://user-images.githubusercontent.com/107814910/175393937-28d9d4b2-f85a-4068-b40b-31b8c2215fdb.jpg)
I checked the meta key registration but I'm not a coder, so it seemed quite frightening to me at first sight. I would do it, but not clear where and how to put those strings.

**Comment by JeanPaiva** [comment]
Now I understand what you mean @lumpyka, you want to loop taxonomies. Unfortanatly we don't support this functionality, yet. But it's a planned feature for sure.

For this initial release we decided to focus first on stability for the post types. We have big plans for the plugin, but we have to go in a slower pace to make sure we are delivery good and performant code.

I'm closing this issue as we are already tracking this feature, but feel free to open again if you feel it.
