### ISSUE TITLE
Responsive Border Radius not removed from Pseudo background

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#59]
To test:
1. Create Container with pseduo background and set container spacing border-radius to 10px.
2. `0` out the border-radius on Mobile.

The border-radius gets removed from the Container but not the pseudo background.

**Comment by tomusborne** [comment]
Should be fixed here: https://github.com/tomusborne/generateblocks/commit/6595fb2d7e1996b102fc5ae4767d9ace40b3126e
