### ISSUE TITLE
Add the "before" field to the Headline block, the one available in the old Dynamic data toggle

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#593]
### Description
Old Headline Block Dynamic data option, has had, and still has the field "before" where one can write stuff that appear before the dynamic text that is generate from whatever source someone is using. This is really usefull and I use it or want to use it a lot. New dynamic data is much better allows more sources to pull data from, can be used anywhere ... but does not have the before field.

Would be great to have that. Even better would be great if one couls also have a dynamic "before" field, though a static one is also great.

### Steps for testing
1. Add a headline that pulls user email data.
2. Try adding the word "Email:" before the actual email.
3. Gets easily complicated without the before field.

**Comment by JeanPaiva** [comment]
Duplicate. https://github.com/tomusborne/generateblocks/issues/467
