### ISSUE TITLE
If I paste 3 paragraphs to a Headline with <p> markup, block turns into 3 core Paragraph blocks

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#594]
### Description
If I paste 3 paragraphs to a Headline with <p> markup, block turns into 3 core Paragraph blocks. Which is undesireable. In some cases I prefer to have the several paragraphs all be Headline P paragraphs, but this way I have to do it one by one.
### Steps to reproduce
1. Insert Headline block, choose p tag
2. Copy three paragraphs of text from whatever source
3. Paste it in Headline (p tag) block

#### Expected behavior
1. Insert Headline block, choose p tag
2. Copy three paragraphs of text from whatever source
3. Paste it in Headline (p tag) block
4. I get 3 Headline blocks with p tag

#### Actual behavior
1. Insert Headline block, choose p tag
2. Copy three paragraphs of text from whatever source
3. Paste it in Headline (p tag) block
4. I get 3 core Paragraph blocks instead

**Comment by JeanPaiva** [comment]
@thisbit indeed a bug from Headline. Since the fix will not be so simple and will require a lot of testing we will not be releasing in the next patch. Gonna add this to the backlog. Thank you

Reference: Requires to implement the callback `onReplace`.

**Comment by eastriverstudio** [comment]
@JeanPaiva @thisbit also to add to this, I've noticed when pasting in text which contains a soft return <br> tag this same issue happens and the headline switches to the core paragraph which is also underisable as I should be able to past the text with <br> tag and it remain as a headline block. 

Thanks

**Comment by JeanPaiva** [comment]
I believe this is a behavior from the core RichText component.

**Comment by tdrayson** [comment]
Is there any update on this? It's a really frustrating bug when trying to copy and paste content into the editor.
