### ISSUE TITLE
[Query loop] Dynamic GB author avatar image block creates an error for posts belonging to users with elevated permissions

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#604]
### Description
Dynamic image author avatar is not being displayed for posts belonging to users with elevated permissions

### Steps to reproduce
1. Create an extra user in addition to the existing admin.
2. Set the new user as an `Author`.
3. Create posts that belong to the author and a few others that belong to the admin.
4. Log in to the newly create author user through an Incognito/private browser window.
5. Create a new page and insert an empty query loop. Make sure you query posts from both users.
6. Insert a GB image block, enable dynamic data, and set the image source to `Author avatar`.

#### Expected behavior
All post author images should be visible.

#### Actual behavior
Only post author images that belong to the current logged-in author user are visible. Any other author images belonging to the admin create an error. `This block has encountered an error and cannot be previewed.`

**Comment by tomusborne** [comment]
This issue can also be observed when "Show avatars" in "Settings > Discussion" is turned off.
