### ISSUE TITLE
Query loop container does not have equal heights when a grid is inside it

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#618]
### Description
Query loop container grid does not have equal heights when a grid is inside it.

### Steps to reproduce
1. Create a query loop and insert a two-column grid.
2. Make the left column a dynamic background image and insert a dynamic title and post date on the right column.

#### Expected behavior
Loop containers should have equal heights since Vertical Alignment is set to `Default`.

#### Actual behavior
Loop containers have uneven heights dictated by the content on the right column.

#### References: 
Example code [here](https://pastebin.com/JSiiBLyz).

-----

**Comment by diggeddy** [comment]
@quantumleap33  do you mean this space ?

<img width="812" alt="Screenshot 2022-07-11 at 17 23 35" src="https://user-images.githubusercontent.com/30641942/178312442-38cc3b70-0a09-45a0-b40b-61f59d393fdc.png">

**Comment by quantumleap33** [comment]
@diggeddy Yeah.

**Comment by JeanPaiva** [comment]
It seems this is solved by the new flexbox controls.
