### ISSUE TITLE
Button colors ignore new colors

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#619]
### Description
In the customizer I have changed all the colors to my pallete. All elements of the website follow these new color settings. However buttons retain the default blue color. This is easily solvable with CSS. But it is a bug.

### Steps to reproduce
1. Go to Customizer
2. Replace all color with new ones
3. Insert Button

#### Expected behavior
Button has new color defined in customizer

#### Actual behavior
Button has default blue color
...

#### References: 
![bug](https://user-images.githubusercontent.com/53581066/177519934-9a287003-8e99-4f25-89af-13244825a319.png)

**Comment by JeanPaiva** [comment]
@thisbit yes, we have some changes for the next GP update that this will be more in sync.

Relates to: https://github.com/tomusborne/generatepress/pull/411
