### ISSUE TITLE
Block color panel - ability to easily change/apply color values across responsive modes

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#624]
I'd like to suggest an enhancement to the blocks color panel in responsive modes. 

At the moment the color panel disappers for blocks like container when you switch to tablet or mobile. However I think it would be a useful addition to be able to override the colour values of blocks in certain use cases, particularly on containers (standard & grid) but could also be useful on other GB blocks like headline too if it proves sensible to do so. 

This could be achieved in one of two ways, either by exposing the colour panel options which make sense in mobile/tablet views, or add background color as an option to the advanced backgrounds panel in addition to the existing image and gradient options.

### Why would this be useful?
A use case I've come across, which I believe would make this useful is sometimes I'm using background gradients to create color block effects between two columns, however on mobile this often needs adapting and I have to override the gradient just for mobile, often by removing the original gradient. In this scenario it would now be useful if I could override the background color of  grid column containers within the section that had the gradient to create the same colour block effect for mobile, but just contained to the actual stacked column, not the whole section. This is needed particularly if I originally had white text on top of a dark color block for example. 

The only way I've found to get around this currently (without custom css or the color panel available) is to add another gradient to the column using advanced backgrounds targetted to mobile. It certianly works but seems a bit of a hack applying a gradient when all I need is to simply change or apply a background color to the column on mobile.

I hope the above use case makes sense and I'd be interested to hear your thoughts on this request!

Thanks

**Comment by JeanPaiva** [comment]
This is no longer the case, you can define colors in every device type.

**Comment by eastriverstudio** [comment]
@JeanPaiva has something happened here since 1.7 as this no longer seems to work again and applying a background color on a container applies to all devices, and can't for example be overidden on just mobile?

Thanks
