### ISSUE TITLE
Query Blocks related posts, missing a feature to be properly used.

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#626]
### Description
If I create a section with the related posts query in it. And have a headline within the section. If the query returns not posts (because there is no related posts, ... for example if the post is the only one with that term) I get an empty section with a section headline without any posts. In code we solve this with if (  $related_posts ) { hedline, loop } and there suhould be a way to do it in the query block in general and especially here.

### Steps for testing
1. Make a section using a container
2. add headline for section
3. add query and set it up
4. if there are not results (try it with a post that has no related psots) you will have only section headline
5. I tried alternative way too, to add the section headline in the query block above the grid container inside the wuery block ... still doesn't work. Maybe that should be the way ... place section headline in the query block but if it returns no results ... show nothing.

#### References:
Here is a video (at the relevant point in time) showing what I am talking about. https://youtu.be/ec8USdGlphk?t=647
Congrats for the new feature ... its great ...

**Comment by JeanPaiva** [comment]
Hey @thisbit I created a pro version task to track this feature (Blocks display rules) to allow users to hide certain blocks based on some options. Gonna close this one to track only in the main task. Thank you

Reference: https://github.com/tomusborne/generateblocks-pro/issues/144
