### ISSUE TITLE
Add "No Result Found" to the Query loop block

### ISSUE THREAD

**Issue by madanpraba** [tomusborne/generateblocks#628]
In the query loop block, "No result found" is the default text when there are no posts for the query. If possible, please provide the option for a custom text to be displayed when there are no posts in the query.

**Comment by JeanPaiva** [comment]
Hey @madanpraba we have planned for the next version add the fallback message block, similar to what core did it. Gonna keep your PR open for future reference. Thank you for your request. :)

**Comment by linuxd3v** [comment]
Seems like this feature keeps getting kicked down the releases. This forces me to maintain separate layouts for "latest from the blogs" and search results which is somewhat of a pita.

**Comment by angie-happytree** [comment]
I also wanted to ask, if this feature is something to expect in the nearer future? Thank you, Angie.

**Comment by markman77** [comment]
This is a necessary feature IMO. Hopefully this can be updated and added soon?

**Comment by diggeddy** [comment]
Added in 2.0

**Comment by linuxd3v** [comment]
is there a description anywhere on how to use?

**Comment by diggeddy** [comment]
@linuxd3v its in GenerateBlocks 2.0 Query Block
There Query Block toolbar has an option to insert the No Results container.
https://learn.generatepress.com/blocks/block/query/

**Comment by diggeddy** [comment]
Thats correct. If you need any further assistance, feel free to upon a topic in the support forums
