### ISSUE TITLE
Introduce query loop post type select filter

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#631]
### Description
Not sure if this is expected behaviour currently with the query loop block, but when I have a custom post type set to publicly queryable false it is not selectable in the select post type dropdown. 

This sort of makes sense, but I might also want to hide a post type from the front-end so a user can't stumble across pages accidently, but then do something custom with the post type using the query loop. 

So I think the post type should still be selectable as a source so we can decide if want to do something custom with it.

### Steps to reproduce
1. Create a new custom post type
2. Set publicy queryable to false
3. Create a new query loop and select source
4. Post type isn't available

#### Expected behavior
I think if we've set publicy queryable to false to hide from the front-end it should still be selectable in the post type source of the query loop for use cases such as customised listings etc.

**Comment by JeanPaiva** [comment]
@eastriverstudio this is expected behavior, we only display the "viewable" post types. And we can't assume that all not viewable post types are safe to become query loops.

Still I think introducing a filter could help users with similar use cases. I'll implement the filter for the next version. Thanks again mate

**Comment by eastriverstudio** [comment]
@JeanPaiva ok great, and does makes sense it is expected. A filter to override this "default" behaviour would be a very welcome for the sort of use case I described, so that would be a good solution thanks.
