### ISSUE TITLE
Block editor list view not updated. 

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#632]
When using GB elements on a page, the block editor list view is not updated on the left when elements go past a certain number. It seems to work fine with core elements.

Tested on latest Chrome browser with WP 6.0.1

https://www.loom.com/share/66f4b104c919480bb5e569c4c36e231d

**Comment by JeanPaiva** [comment]
Weird bug @quantumleap33 gonna take look. Thanks

**Comment by quantumleap33** [comment]
@JeanPaiva Did you manage to reproduce it?
