### ISSUE TITLE
Remove jQuery from Sticky Header and Back to Top

### ISSUE THREAD

**Issue by atmostfear-entertainment** [tomusborne/generateblocks#638]
We recommend excluding jQuery from both Sticky Header, and Back to Top features, something that we noticed has been requested quite a few times on multiple channels such as your support forums and groups led by your team or third parties related to the WordPress ecosystem.

This would greatly benefit when it comes to the exclusion of jQuery from loading, making GeneratePress more Vanilla-oriented and, of course, keeping the performance in mind.

**Comment by JeanPaiva** [comment]
Hey @atmostfear-entertainment we already have plans to remove jQuery on GeneratePress, but for now we have other features we need to do in order to prepare GP for the future, removing jQuery is one of them too. Thanks

Closing this one as this is GenerateBlocks repository.

**Comment by tomusborne** [comment]
Just wanted to mention that our back to top is vanilla js already. The sticky nav is the only jQuery left - we'll definitely be improving that soon.

**Comment by atmostfear-entertainment** [comment]
Hello @tomusborne,

We appreciate the correction.

Keep up with the good work.
