### ISSUE TITLE
Query loop/grid - ability to control flex alignment of elements inside gb-inside-container

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#639]
### Description
At the moment within a query loop container or standard grid container it is only possible to set the vertical alignment on all items inside the inner gb-inside-container. 

It is quite a common pattern that we'd want to achieve a card style layout inside a loop or grid where we have some variable height content at the flex-start of the container and then a button or some meta data at the flex-end so this is always aligned nicely at the bottom regardless of the content height above it. 

At the moment this is not possible due to the alignment being limited to the whole gb-inside-container element. 

So I'd like to suggest adding improved controls to allow the gb-inside-container to be set as a flex element in its own right (optional if required?) and stretch full height to allow more options for alignment of items inside and more easily recreate the style of pattern mentioned above. If we could also control the order of items responsively inside this would be even more powerful.

To work fully this would need to coincide with another feature already suggested to allow the auto value on margins so a button can be easily pushed to the flex-end for example.

Thanks

**Comment by JeanPaiva** [comment]
Flexbox was introduced in 1.7

https://generateblocks.com/flexbox-sizing-tabs-accordions-more/
