### ISSUE TITLE
Query Blocks Does not See Event Post type While it normally sows in display rules on elements (GP)

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#641]
### Description
I am using this plugin to handle events for website. https://wordpress.org/plugins/events-manager/ Pretty powerful plugin. 
I am able to assign GP elements to the post type event no problem, so GeneratePress can talk to the post type. However If I want to render a grid of events on a page using GenerateBlocks Query Block It does not appear as option in post type dropdown of the block.

### Steps to reproduce
1. Install the https://wordpress.org/plugins/events-manager/ plugin set it up, create some events, and assign some event categories to it.
2. Assign an element to the event template.
3. Works
4. Try to make a query block show some events on the page
5. Post type does not show in the Query Block options

#### Expected behavior
1. Install the https://wordpress.org/plugins/events-manager/ plugin set it up, create some events, and assign some event categories to it.
2. Assign an element to the event template.
3. Works
4. Try to make a query block show some events on the page
5. Post type appears in Query Block options, you select it.
6. List of events appear.

#### Actual behavior
1. Install the https://wordpress.org/plugins/events-manager/ plugin set it up, create some events, and assign some event categories to it.
2. Assign an element to the event template.
3. Works
4. Try to make a query block show some events on the page
5. Post type does not appear in Query Block options, so you cannot select it.

#### References: 
Thanks

-----

**Comment by quantumleap33** [comment]
@thisbit I *think*, that I have come across this issue with the plugin and it had to do with the CPT not being public:
https://developer.wordpress.org/reference/functions/register_post_type/#public

**Comment by thisbit** [comment]
Thanks ill check it out

**Comment by thisbit** [comment]
But how it then be available to the events module displays rules select field?

**Comment by quantumleap33** [comment]
Seems to be happening with the core query loop, as well. Just remembered! The CPT doesn't have REST API Support enabled:
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/#adding-rest-api-support-to-existing-content-types

This code should fix it:
```
add_filter( 'register_post_type_args', 'my_post_type_args', 10, 2 );
 
function my_post_type_args( $args, $post_type ) {
 
    if ( 'event' === $post_type ) {
        $args['show_in_rest'] = true;
    }
 
    return $args;
}
```

**Comment by thisbit** [comment]
@quantumleap33 thanks a lot works like a breeze

**Comment by JeanPaiva** [comment]
Exactly that @quantumleap33 and @thisbit . Since Query loop requires live preview in the editor and we make use of the REST API for that the post type must be enabled in the API otherwise it would always show "No posts found".
