### ISSUE TITLE
PHP Notice:  Undefined index: className 

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#644]
Since when adding a class to a GB column the class is actually added to its child container, I am using the following code to add a class to the actual GB column:

```
add_filter( 'generateblocks_attr_grid-item', function( $attributes, $settings ) {
    if ( 'sticky-right-sidebar' === $settings['className'] ) {
        $attributes['class'] .= ' sticky-right-column';
    }

    return $attributes;
}, 10, 2 );
```

It works fine but I get a PHP notice:
`[29-Jul-2022 18:18:09 UTC] PHP Notice:  Undefined index: className in /siteroot/wp-content/themes/generatepress_child/functions.php on line 128`

Could that be solved in a future GB update?

**Comment by JeanPaiva** [comment]
@quantumleap33 you just need to check for `classname` key before using it.

```php
add_filter( 'generateblocks_attr_grid-item', function( $attributes, $settings ) {
    if ( isset($settings['className']) && 'sticky-right-sidebar' === $settings['className'] ) {
        $attributes['class'] .= ' sticky-right-column';
    }

    return $attributes;
}, 10, 2 );
```

**Comment by quantumleap33** [comment]
Perfect, thanks!
