### ISSUE TITLE
[Query loop] Dynamic taxonomy headline styling

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#646]
When setting a dynamic taxonomy headline, the actual content is wrapped within a span where related classes are added:

`<h2 class="gb-headline gb-headline-50900f11 gb-headline-text"><span class="post-term-item term-community"><a href="http://newsroom-starter.test/category/community/">Community</a></span></h2>`

That creates some problems. For example, if I set the headline to have some padding and border-radius and then want to style each particular term with a certain global color, there is no way to do it. Well not until the `.has` class is implemented in all browsers which is not going to happen anytime soon.

I am not clear as to why there should be an extra `span`, to begin with. Why couldn't the classes be added to the actual headline instead? It would make things so much easier.

**Comment by diggeddy** [comment]
List of Terms Dynamic data relies on each term to be output within its own markup, each with the relevant term classes. Otherwise it is not possible to use custom CSS to target each term.

Closing as not possible to improve using List of Terms
Will be under consideration in future query loops
