### ISSUE TITLE
Global Styles - ability to remove items from adding styles when purely for display

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#649]
I'm enjoying using the global styles feature and find it useful for setting up basic global style rules for main GB elements I'll reuse across a site. The only thing missing is a way to create reusable utility classes that can be used on any element, that would make this feature very powerful indeed!

However I do run into a slightly frustrating quirk with the current implementation when creating a global style for say a container, I may need to put some GB elements inside just to help with the editor previewing of my global style work. However the way global styles does it currently any GB elements added automatically create new global styles which are redundant if I'm just adding them for previewing purposes which can be annoying if these start to show in the global style list. 

Therefore I think it would be a nice workflow enhancement to global styles if I could add elements for previewing purposes but toggle them off if I don't want them to actually generate a new global style.

Would be intereted to hear if you guys agree with me on this?

Thanks

**Comment by JeanPaiva** [comment]
@eastriverstudio we have some plans to improve global colors but currently we are focusing on other more asked features.
