### ISSUE TITLE
[Dynamic headline] Display published date if updated date is not available

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#657]
Currently, a dynamic headline allows either published or updated dates. A post that doesn't have an updated date, though, will render the date blank if set to display updated date. It would be nice to have an option to display the published date if updated date is not available like the GP dynamic text does.

**Comment by tomusborne** [comment]
Hey @quantumleap33 - this is already possible. Set the Date type to "Published date" and then toggle the "Replaced with updated date" option: https://www.screencast.com/t/fgUoAw23K

This will show the published date unless an updated date is available.

**Comment by quantumleap33** [comment]
Sorry, my mistake, I meant dynamic headline inside a query loop!

**Comment by quantumleap33** [comment]
Doh, it's the same thing, sorry, sorted!
