### ISSUE TITLE
CPT: publicly_queryable: false won't show post in Query Loop Post list,

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#658]
### Description
I think the REST API relies on a post type to be `publicly_queryable => true`.
If set to `false` then the post type cannot be selected in the Query Loop.

Use case:

User was using a CPT to store content.
They did not want to generate the single post. 
Which is achieved by setting the `publicly_queryable => false`.

**Comment by system4pc** [comment]
waiting for a fix, i found this workaround, having publicly_queryable => false and adding to functions.php
where XXXXX is the name of CPT
add_filter( 'is_post_type_viewable', function( $is_viewable, $post_type ) {
    if ( 'XXXXX' === $post_type->name ) {
        return true;
    }
    return $is_viewable;
}, 10, 2 );

make visible the cpt on backend select for query loop, but not visible in frontend  ( it goes in 404 if you try the url)

**Comment by eastriverstudio** [comment]
@diggeddy @system4pc Just to let you know I already opened a similar issue about this here:

https://github.com/tomusborne/generateblocks/issues/631

@JeanPaiva mentioned in the comments he'll possibly look at a filter option for this use case.

Hope this helps.

**Comment by diggeddy** [comment]
Thanks @eastriverstudio  - this topic is now closed for duplicity
