### ISSUE TITLE
Query Loop Block - Post Template tag name not working.

### ISSUE THREAD

**Issue by fernandoazarcon2** [tomusborne/generateblocks#665]
### Description
Post Template tag name is not working on a Query Loop Block.
The filter generateblocks_container_tagname isn't working as well.

### Steps to reproduce
1.  Create Query Loop Block
2. Change Post Template tag name or use generateblocks_container_tagname filter

#### Expected behavior
tag name replaced

#### Actual behavior
tag name remains div

#### References: 
https://share.getcloudapp.com/o0uXNd6w

-----

**Comment by diggeddy** [comment]
Although we should include `article` within the HTML element tags for Container Blocks.
In this instance that option would not help as we need to change the tag of `gb-grid-column` element.

**Comment by JeanPaiva** [comment]
@fernandoazarcon2 @diggeddy @tomusborne let's push this to 1.7 so we can discuss more before changing. As Tom said, the idea is to remove the `gp-grid-column` in the future as it's only for the gaps.

**Comment by diggeddy** [comment]
What is stopping us from adding `article` as a HTML tag for the Container in 1.6 ?
It has uses outside of the Query Loop and will be there when we remove the `gb-grid-column`

**Comment by JeanPaiva** [comment]
@diggeddy nothing stopping us I just opened the PR.

**Comment by tomusborne** [comment]
Testing #670 and questioning why we added the post classes to the `gb-grid-column` element as well. Seems like they would be better added to the `gb-container` element. What do you think @diggeddy? I think we added them to the outer element for a reason - maybe visibility?

**Comment by diggeddy** [comment]
Primarily styling for example 

```
.gb-grid-wrapper > .gb-column.category-politics {
    width: 100%;
}
```

And some JS / CSS filters for hiding and showing posts. You have to get the `gb-column` out the way

**Comment by tomusborne** [comment]
Definitely a problem as we want to eventually remove that wrapper and doing so will break solutions like that.

**Comment by diggeddy** [comment]
when that happens we can just move the classes to the `gb-container` right  ?

**Comment by tomusborne** [comment]
Right, but solutions like your CSS (if the user has added them) will break.

**Comment by JeanPaiva** [comment]
@tomusborne @diggeddy should we apply the tag to `.gb-grid-column`? Or could we keep it as is?
