### ISSUE TITLE
Query Loop Parameter Selection Missing Items

### ISSUE THREAD

**Issue by nicolasmesser** [tomusborne/generateblocks#673]
### Description
When adding an additional parameter to the query loop, I can't get to or select all the items. It's either an issue because they're not at all showing up (i.e. authors - see screenshot) or with the "browser window" where the selection list is outside of the frame (not sure if that makes sense).

### Steps to reproduce
1. Insert Query Loop Block
2. Add Parameter (i.e. authors)
3. Select (or search for) items not in the list or available

#### Expected behavior
I would expect all the items to be available - in this case with authors all users with author or contributor level.

#### Actual behavior
Can't get past the letter B (i.e. Dexter is not available). This also happens with other parameters with taxonomies linked to CPT (yes, their are available through the API).

#### References: 
![Screenshot 2022-08-26 at 3 06 56 PM](https://user-images.githubusercontent.com/1015551/186913312-d91afbe5-6228-48d2-a646-b0102f269593.png)

-----

**Comment by JeanPaiva** [comment]
Related to #642

Thanks @nicolasmesser gonna get that fixed for next version that should be on alpha next week.

**Comment by nicolasmesser** [comment]
Thanks for the fix! Works like a charm 👌🏻
