### ISSUE TITLE
[Query loop] Separate Include/Exclude sections

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#677]
Instead of mixing include and exclude query parameters, it would make more UX sense to have an "Include" and "Exclude" section where users would be able to select what would need to be included and excluded from the query.

**Comment by JeanPaiva** [comment]
@quantumleap33 I do not quite understand your request, currently, users can have Include or Exclude or both active at the same time as they see fit in their query loop.

![image](https://user-images.githubusercontent.com/7506830/187454945-4356c2af-4145-4040-8fad-a47cf6e8e00c.png)

**Comment by quantumleap33** [comment]
Hi Jean. What I am saying is instead of having all these pairs `Authors|Exclude Authors`, `Taxonomies|Exclude Taxonomies`, `Parent|Parent Exclude` visible in the dropdown, instead you could have an `Include` and `Exclude` section that could fit all the query parameters for either inclusion or exclusion. Kind of like how the `Include posts` and `Exclude Posts` are but for ALL the parameters. No need for stuffing the dropdown area with the include/exclude pairs.

**Comment by JeanPaiva** [comment]
Do you mean an "Include" option that once added displays all the select boxes for all options? (Authors, Taxonomies, Parent)

But what if you just want to include authors? Your UI will be displaying select boxes for all other types? Even tho they are inactive? How do you see this example?

If you could bring some UI images for the changes so I can understand better your solution

**Comment by quantumleap33** [comment]
After having a closer look, I think my proposal could complicate things. That's because there are various other conditions apart from include/exclude that need to be catered for and would create extra sections that could be confusing. Don't want to give Tom and Jean another headache!
