### ISSUE TITLE
Block list view does not show all GB elements

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#686]
Not all GB elements are shown in the block editor list view. The behavior depended on the number of parent blocks that are toggled open. This behavior doesn't happen with core blocks.

Reference
https://www.loom.com/share/ea074a17869d43abab073fe26bcec7dd

**Comment by JeanPaiva** [comment]
@quantumleap33 can you paste the contents of this page for me? Gonna try to understand why this is happening

**Comment by diggeddy** [comment]
Core issue
For reference:
https://github.com/WordPress/gutenberg/issues/41613#issuecomment-1634876025
Closing.
