### ISSUE TITLE
Dynamic data - Duplicated button text issue if using dynamic link value in elements content template

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#689]
Testing the latest alphas (GB 1.6.0 & GBP 1.4.0, but I believe was an issue before this also), if I use the dynamic data feature to populate the link of a GB button within a GP elements content template the button text gets duplicated when you view a post on the frontend which uses the content template. 

As a workaround up to now, I've used the dynamic feature within GP Elements to add the link to buttons instead. However I should be able to use the new dynamic feature on buttons within a block content template, particularly with the newly added support for ACF fields in the latest alpha versions, which before those I've had to use filters just to get ACF link fields to populate a button properly.

Thanks

**Comment by eastriverstudio** [comment]
Update, this also seems to be happening within query loops used on standard pages too, so assuming this is a bug with the new Alpha versions.

**Comment by eastriverstudio** [comment]
@JeanPaiva @tomusborne just to let you know and provide an update, this bug still persists in the latest  GB and GBP betas and I think it is to do with when a button has a global style and dynamic link data applied. If I remove the global button style the the duplicated button text goes away. hope this helps?

**Comment by tomusborne** [comment]
Hey @eastriverstudio! I'm not able to replicate this on my end.

Any chance you can share some example code I can plug in to make sure our tests match?

**Comment by eastriverstudio** [comment]
Hi @tomusborne, sure here is the code from the query loop code block where I'm getting the duplicate text when viewing frontend. In addition to the dynamic link setting on the button I also have a global style set and an icon. As mentioned previously, if I remove the global style the duplicated text goes away. Hope this helps?








<h3 class="gb-headline gb-headline-c9300a03 gb-headline-text"></h3>



<p class="gb-headline gb-headline-bb03eb6e gb-headline-text"></p>




<span class="gb-button gb-button-252273ff"><span class="gb-button-text">Find out more</span><span class="gb-icon"><svg viewBox="0 0 18.92 18.92" xmlns="http://www.w3.org/2000/svg" id="a"><polygon points="14.67 6.73 14.4 7.15 17.45 9.18 .19 9.18 .19 9.68 17.47 9.68 14.39 11.78 14.67 12.19 18.73 9.43 14.67 6.73"></polygon><rect style="fill:none;" height="18.92" width="18.92"></rect></svg></span></span>

**Comment by tomusborne** [comment]
Hey @eastriverstudio - have you tried turning off the default more tag?: https://www.screencast.com/t/5EJ69h9CjR6

The excerpt function in WP has a more link by default depending on the theme you're using, so that could be what you're seeing.

**Comment by eastriverstudio** [comment]
@tomusborne unfortunately I’m not using the excerpt content or any dynamic content for the button’s label, only the dynamic link option. The button’s label text is static and this is what I’m seeing duplicated in query loops and block content templates when the button has a global style active.

**Comment by tomusborne** [comment]
Is that code complete? I'm not seeing the Query Loop block in the code. I'm not able to replicate any duplicate text.

Just to confirm, are you adding the Query Loop block to a Content Template block element?

**Comment by eastriverstudio** [comment]
@tomusborne ah sorry I thought I had copied the whole query loop block. Can you try this code instead, it is the full page code. This query loop and the duplicate text was created on a standard page, but I have also seen the duplicate button text issue when having a button with global style and dynamic data applied within a content template block. If it helps here's a screen grab of the loop code below on the frontend if I turn on a global style: https://share.cleanshot.com/oU5MIV

Here's the page code:





<h2 class="gb-headline gb-headline-e6e05dc4 gb-headline-text">We ensure that are developments are built with you in mind, improving your well being but also being good for the planet.</h2>



<div class="gb-headline gb-headline-3249b9b2 icon-auto"><span class="gb-icon"><svg viewBox="0 0 64.79 7.2" xmlns="http://www.w3.org/2000/svg" id="a"><g><path style="fill:#50af47;" d="M16.94,5.76c-.07-.06-.15-.11-.24-.16,0,0-.94-.43-1.25-.58-.03-.02-.07-.03-.09-.05-.09-.06-.25-.2-.33-.27-.11-.11-.18-.25-.23-.39l-.04-.11-.58,.13s-.02,0-.02,0c-.05,0-.1-.04-.11-.09-.01-.06,.02-.12,.09-.14l.55-.13-.11-.31-.56,.14s-.02,0-.03,0c-.05,0-.1-.03-.11-.09-.02-.06,.02-.12,.08-.14l.54-.13-.11-.31-.5,.12s-.02,0-.03,0c-.05,0-.1-.04-.11-.09-.01-.06,.02-.12,.08-.14l.48-.11-.12-.34-.58,.16s-.02,0-.03,0c-.05,0-.09-.03-.11-.08-.02-.06,.02-.12,.08-.14l.56-.16-.12-.33c-.17,.03-.33,.04-.46,.04-.55,0-.82-.2-.88-.24-.71-.46-.81-1.03-.78-1.39,.01-.11-.05-.2-.14-.23-.34-.1-.7,.03-1.02,.24l-.19,.13c-.47,.36-.84,.84-.92,.96,0,.32,.39,.79,.75,1.13l.17,.16c.1,.09,.18,.16,.24,.21,.06,.05,1.43,1.14,1.85,1.87,.06,.1,.18,.29,.25,.39,.23,.33,.6,.61,.88,.79,.2,.12,.41,.2,.64,.22,.45,.05,1.33,.11,2.18-.05,.47-.09,.54-.22,.55-.26,.02-.06-.04-.16-.16-.27Z"></path><path style="fill:#50af47;" d="M15.35,6.74c-.41,0-.76-.03-1-.06-.26-.03-.51-.11-.73-.25-.42-.26-.97-.77-1.19-1.24-.34-.7-1.79-1.81-1.8-1.82-.12-.1-1.08-.88-1.23-1.52-.19,.06-.57,.23-.65,.6-.1,.48,.66,1.31,1.55,1.71,.35,.16,.69,.38,1.02,.67,.25,.22,.44,.46,.58,.74,.25,.51,.9,1.39,2.44,1.6,1.29,.17,2.03-.24,2.4-.57-.04,.01-.09,.02-.14,.03-.43,.08-.86,.11-1.25,.11Z"></path></g><path style="fill:#d7490c;" d="M34.04,.51c.34,.34,.51,.75,.51,1.24s-.17,.9-.51,1.24c-.34,.34-.76,.51-1.24,.51s-.89-.17-1.24-.51c-.34-.34-.51-.75-.51-1.24s.17-.89,.51-1.24c.34-.34,.76-.51,1.24-.51s.9,.17,1.24,.51m1.68,5.27c0,.33-.09,.62-.29,.85-.19,.24-.42,.36-.68,.36h-3.89c-.27,0-.5-.12-.69-.36-.19-.24-.28-.52-.28-.85,0-.26,.01-.5,.04-.73,.02-.23,.07-.46,.14-.69,.07-.23,.16-.43,.26-.6,.11-.16,.25-.3,.43-.4,.18-.11,.38-.16,.61-.16,.4,.39,.87,.58,1.42,.58s1.03-.2,1.43-.58c.23,0,.43,.05,.61,.16,.18,.1,.32,.24,.43,.4,.11,.17,.2,.36,.27,.6,.07,.23,.12,.46,.15,.69,.02,.23,.04,.47,.04,.73"></path><path style="fill:#50af47;" d="M44.64,3.39c0-.35-.19-.66-.47-.84,.01-.04,.02-.08,.02-.13,0-.27-.2-.49-.47-.53-.04-.16-.12-.3-.23-.41,.13-.1,.21-.25,.21-.42,0-.3-.24-.53-.53-.53-.2,0-.38,.11-.47,.28-.17-.2-.41-.33-.69-.35-.19-.01-.38,.03-.53,.12,0-.01,0-.03,0-.04C41.48,.24,41.24,0,40.95,0s-.53,.24-.53,.53h0c-.12-.04-.26-.08-.41-.08-.54,0-.97,.43-.99,.97-.07-.04-.15-.06-.24-.06-.3,0-.53,.24-.53,.53,0,.09,.03,.18,.07,.26-.15,.19-.26,.41-.31,.65-.17,.09-.29,.27-.29,.47,0,.23,.15,.43,.36,.5-.02,.08-.04,.17-.04,.26,0,.54,.44,.99,.99,.99,.26,0,.5-.1,.67-.27,.08,0,.15-.02,.23-.04,.08,.19,.27,.33,.49,.33,.01,0,.02,0,.03,0l-.16,1.51-.71,.55s.8-.25,1.4-.25c.68,0,1.4,.21,1.4,.21l-.65-.51-.12-1.52c.1-.02,.19-.07,.26-.14,.14,.08,.3,.12,.47,.12,.22,0,.41-.07,.57-.19,.08,.05,.18,.08,.28,.08,.3,0,.53-.24,.53-.53h0c.51-.04,.92-.47,.92-.99"></path><path style="fill:#751632;" d="M26.63,4.03v2.62c0,.1-.03,.18-.1,.24-.07,.07-.15,.1-.25,.1h-2.09v-2.09h-1.4v2.09h-2.09c-.09,0-.18-.03-.25-.1-.07-.07-.1-.15-.1-.24v-2.62s0,0,0-.02v-.02l3.14-2.59,3.14,2.59s0,.02,0,.03m1.22-.38l-.34,.4s-.07,.05-.11,.06h-.02s-.09-.01-.11-.04l-3.78-3.15-3.77,3.15s-.09,.04-.13,.04c-.05,0-.09-.03-.12-.06l-.34-.4s-.04-.08-.04-.13c0-.05,.02-.09,.06-.12L23.08,.14c.12-.09,.25-.14,.41-.14s.3,.05,.42,.14l1.33,1.11V.19c0-.05,.01-.09,.05-.12,.03-.03,.07-.05,.12-.05h1.05c.05,0,.09,.02,.13,.05,.03,.03,.05,.07,.05,.12V2.41l1.2,.99s.06,.07,.06,.12c0,.05,0,.09-.04,.13"></path><path style="fill:#446b91;" d="M51.47,1.38c.34,0,.62-.28,.62-.62s-.28-.62-.62-.62-.62,.28-.62,.62,.28,.62,.62,.62"></path><g><path style="fill:#446b91;" d="M53.06,3.73c-.92,0-1.67,.75-1.67,1.67s.75,1.67,1.67,1.67,1.67-.75,1.67-1.67-.75-1.67-1.67-1.67Zm0,2.54c-.48,0-.87-.39-.87-.87s.39-.87,.87-.87,.87,.39,.87,.87-.39,.87-.87,.87Z"></path><path style="fill:#446b91;" d="M48.35,3.73c-.92,0-1.67,.75-1.67,1.67s.75,1.67,1.67,1.67,1.67-.75,1.67-1.67-.75-1.67-1.67-1.67Zm0,2.54c-.48,0-.87-.39-.87-.87s.39-.87,.87-.87,.87,.39,.87,.87-.39,.87-.87,.87Z"></path><path style="fill:#446b91;" d="M52.74,2.88c.12,0,.23-.1,.23-.23v-.04c0-.12-.1-.23-.23-.23h-1.06l-.62-.98s-.04-.07-.07-.1l-.13-.13c-.17-.17-.44-.17-.61,0l-1.43,1.43c-.17,.17-.17,.44,0,.61l.13,.13s.07,.06,.1,.08l1.26,.67v1.41c0,.19,.16,.35,.35,.35h.08c.19,0,.35-.16,.35-.35v-1.69c0-.05-.01-.11-.04-.16,0,0-.1-.25-.35-.39l-.7-.37,.83-.83c.14,.23,.41,.68,.41,.68,.04,.08,.12,.14,.21,.14h1.28Z"></path></g><path style="fill:#b41412;" d="M60.72,7.11c-.08,0-.15-.03-.2-.08l-2.83-2.73s-.07-.06-.13-.12c-.05-.06-.14-.15-.25-.3-.12-.14-.22-.29-.31-.44-.09-.15-.17-.33-.24-.55-.07-.21-.11-.42-.11-.63,0-.67,.19-1.19,.58-1.56,.38-.37,.92-.56,1.59-.56,.19,0,.38,.03,.57,.1,.2,.06,.38,.15,.54,.26,.17,.11,.31,.21,.43,.31,.12,.1,.24,.2,.35,.31,.11-.11,.22-.21,.34-.31,.12-.1,.27-.2,.43-.31,.17-.11,.35-.2,.54-.26,.19-.06,.39-.1,.58-.1,.68,0,1.21,.19,1.59,.56,.38,.38,.58,.9,.58,1.56s-.35,1.35-1.04,2.04l-2.83,2.72c-.05,.05-.12,.08-.2,.08"></path><g><path style="fill:#f7ae30;" d="M3.57,1.76c-1.04,0-1.89,.85-1.89,1.89s.85,1.89,1.89,1.89,1.89-.85,1.89-1.89-.85-1.89-1.89-1.89Z"></path><path style="fill:#f7ae30;" d="M3.34,1.2L2.6,0V1.39c.08-.05,.2-.11,.35-.15,.16-.04,.29-.05,.39-.05Z"></path><path style="fill:#f7ae30;" d="M5.13,1.76l.29-1.37-.96,1.01c.09,.02,.22,.06,.35,.13,.14,.08,.25,.17,.32,.23Z"></path><path style="fill:#f7ae30;" d="M6,3.34l1.19-.74h-1.39c.05,.08,.11,.2,.15,.35,.04,.16,.05,.29,.05,.39Z"></path><path style="fill:#f7ae30;" d="M5.68,4.85c-.08,.14-.17,.24-.24,.31l1.36,.33-.98-.99c-.02,.09-.06,.22-.14,.35Z"></path><path style="fill:#f7ae30;" d="M3.83,6.01l.74,1.19v-1.39c-.08,.05-.2,.11-.35,.15-.16,.04-.29,.05-.39,.05Z"></path><path style="fill:#f7ae30;" d="M2.05,5.48l-.31,1.37,.98-.99c-.09-.02-.22-.06-.35-.14-.14-.08-.24-.17-.31-.24Z"></path><path style="fill:#f7ae30;" d="M1.19,3.87l-1.19,.74H1.39c-.05-.08-.11-.2-.15-.35-.04-.16-.05-.29-.05-.39Z"></path><path style="fill:#f7ae30;" d="M.37,1.76l.99,.98c.02-.09,.06-.22,.14-.35,.08-.14,.17-.24,.24-.31L.37,1.76Z"></path></g></svg></span></div>




<a class="gb-button gb-button-31ff6a67 gb-button-text-link-primary icon-below smooth-scroll" href="#developments"><span class="gb-button-text">Check out our developments below</span><span class="gb-icon"><svg viewBox="0 0 18.92 18.92" xmlns="http://www.w3.org/2000/svg" id="a"><polygon points="12.19 14.67 11.77 14.4 9.74 17.45 9.74 .19 9.24 .19 9.24 17.47 7.14 14.39 6.73 14.67 9.49 18.73 12.19 14.67"></polygon><rect style="fill:none;" transform="translate(18.92 0) rotate(90)" height="18.92" width="18.92" y="0" x="0"></rect></svg></span></a>






<h2 class="gb-headline gb-headline-bae38d3a gb-headline-text">Our developments are passivhaus certified, building a better future<br>for Exeter.</h2>



<figure class="gb-block-image gb-block-image-d3fa8f8d"><img class="gb-image gb-image-d3fa8f8d" src="https://wordpress-674440-2798142.cloudwaysapps.com/wp-content/uploads/2022/08/clifton-hill-exeter-development-interior-scene-1.jpg" alt="" title="clifton-hill-exeter-development-interior-scene-1"/></figure>














<h3 class="gb-headline gb-headline-c9300a03 gb-headline-text"></h3>



<p class="gb-headline gb-headline-bb03eb6e gb-headline-text"></p>




<span class="gb-button gb-button-252273ff gb-button-text-link-primary"><span class="gb-button-text">Find out more</span><span class="gb-icon"><svg viewBox="0 0 18.92 18.92" xmlns="http://www.w3.org/2000/svg" id="a"><polygon points="14.67 6.73 14.4 7.15 17.45 9.18 .19 9.18 .19 9.68 17.47 9.68 14.39 11.78 14.67 12.19 18.73 9.43 14.67 6.73"></polygon><rect style="fill:none;" height="18.92" width="18.92"></rect></svg></span></span>









Hope this helps to identify the issue. Thanks

**Comment by tomusborne** [comment]
Perfect, that helped!

Fix should be here: https://github.com/tomusborne/generateblocks/pull/699

Thank you!

**Comment by eastriverstudio** [comment]
@tomusborne great news, glad that helped! Thanks for bearing with me on this one and finding a fix!
