### ISSUE TITLE
Dynamic data - missing editor buttons for bold / italic

### ISSUE THREAD

**Issue by onetrev** [tomusborne/generateblocks#697]
### Description
If I enable Dynamic Data on a GenerateBlocks element, then suddenly the buttons for Bold and Italic disappear. A quick bit of CSS can fix overcome this, so not a major issue, but definitely not ideal.

### Steps to reproduce
1. Add a GB block to the WP editor.
2. Enable Dynamic Data

#### Notes: 
- This happens with latest GB Pro and with 1.4.0 Beta 1.

![Screenshot 2022-09-14 153212](https://user-images.githubusercontent.com/597601/190068483-9c009994-bb71-431f-abb6-20e5f6ee146d.jpg)

-----

**Comment by tomusborne** [comment]
The reason for this is the bold/italic options add the necessary static HTML to the selected text as it's a Rich Text component.

Once you enable dynamic data, the block is no longer saved as static HTML. The content is generated dynamically on the frontend, so it's not possible to highlight specific words to bold/italicize them.
