### ISSUE TITLE
GB 1.6.0-rc1 deprecation notice in error log

### ISSUE THREAD

**Issue by lucspe** [tomusborne/generateblocks#702]
### Description
After installing GenerateBlocks 1.6.0-rc1 on a test site running PHP 8.0.22, I am getting the following warning in the php error log:

Deprecated:  Required parameter $new_data follows optional parameter $existing_data in /wp-content/plugins/generateblocks/includes/functions.php on line 959

This seems to be due to the fact that in line 959 the function `generateblocks_group_css_data` declares a mandatory argument after an optional argument, which appears to be deprecated as of PHP 8.0

**Comment by JeanPaiva** [comment]
@lucspe thanks, man. It will be fixed on the next RC version.
