### ISSUE TITLE
Save local patterns directly in Gutenberg

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generateblocks#705]
I would like to have an option in the following field where you can save a block group as Local Patterns:
<img width="969" alt="1" src="https://user-images.githubusercontent.com/9355398/192531274-070dcfcf-8190-4199-ab51-271d9b1c1277.png">

This would simplify the creation of patterns enormously

**Comment by thisbit** [comment]
Please if you add this, limit it to administrators, or to users who have access to Local Patterns CPT. So if I remove access to the CPT they also lose access to the submenu option.

Local Patterns are a powerfull feature I use in complex sites to establich design system like components. And I want other site editors to use them, not create them.

**Comment by JeanPaiva** [comment]
Will be tracked internally.
