### ISSUE TITLE
Image block - add object-position control if object-fit option is used.

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#708]
I'd like to suggest a small and hopefully simple enhancement to the image block's current `object-fit` option. 

Sometimes when using `object-fit` it is also desirable to control the positioning using `object-position`. This is particularly helpful when using the cover option to help with cropping nicely. 

I'd suggest it works similar to the current background position field on containers which has the default value to start off but then we can manually type in a desired custom value e.g "center top" if we prefer to change the position.

Thanks

**Comment by JeanPaiva** [comment]
Will be tracked internally.
