### ISSUE TITLE
Query loop block: by product categories, properties, filtering

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generateblocks#722]
I would like to have a function that allows me to filter one (or more) product category (WooCommerce) with the query loop. Currently I can display all or individual products, but not filter by categories, properties ect. This would be really great if this works.

Practical example: A page with a query loop that gives me 6 products from category XYZ.

**Comment by JeanPaiva** [comment]
Hey, @SchneiderSam the "Taxonomies" query parameter does not work for you?

![image](https://user-images.githubusercontent.com/7506830/195992285-6967bcaf-ab01-473c-911b-d62c010101a7.png)

**Comment by SchneiderSam** [comment]
@JeanPaiva oh. Ok thanks - amazing.
