### ISSUE TITLE
Query Block - Random Order

### ISSUE THREAD

**Issue by nicolasmesser** [tomusborne/generateblocks#723]
### Description
Is it possible to have a random order in the query loop block? The "old" WPShowPosts plugin provided this option and I remember reading about it somewhere in early documentation (or post/comment) for GB.

**Comment by JeanPaiva** [comment]
@nicolasmesser the random order option is available for GenerateBlocks Pro

**Comment by nicolasmesser** [comment]
Thank you - makes sense ... been looking at Pro for a while and ready to take the plunge 😀
