### ISSUE TITLE
query loop of cpt pull 'private' posts

### ISSUE THREAD

**Issue by dasigna** [tomusborne/generateblocks#741]
simple as the headline:
created a (random related posts) query loop which pulls private posts of a cpt. interestingly enough they are shown with the prefix 'Private: ...'. shouldnt be the case at all imho?

bug or feature?

**Comment by JeanPaiva** [comment]
@dasigna we just display the data returned from the REST API. Adding the prefix "Private: " is something that core does, GB does not add or remove any content coming from the post itself.

This might help you remove it: https://wordpress.stackexchange.com/questions/238749/hide-the-private-prefix-on-one-specific-page

**Comment by JeanPaiva** [comment]
You have the parameter "Post status" to select which status should show in your query loop. Select only publish if you don't want private posts to show there.

![image](https://user-images.githubusercontent.com/7506830/198092985-11c9edd0-fdaf-453a-a386-30daebe9eb1d.png)

As per WP_Query docs, "Default value is ‘publish‘, but if the user is logged in, ‘private‘ is added." so GB doesn't apply any rules to your query, we just give you the parameters to control the query.

Just keep in mind that the Query loop might not include posts from multiple statuses on the editor cause of REST API limitations to support only one status.


[WP Query - Status parameter](https://developer.wordpress.org/reference/classes/wp_query/#status-parameters)
[WP REST API - Posts Schema](https://developer.wordpress.org/rest-api/reference/posts/#schema)

**Comment by dasigna** [comment]
aha. 'post status' - barely havent had in mind (having) to set that. :)

i'll figure that out. thx for your patience.

**Comment by JeanPaiva** [comment]
No worries mate, have a nice day.
