### ISSUE TITLE
Add more tag names for container

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#750]
Ability to add more tag names for container, for example `<details>` and `<summary>`.
https://www.w3schools.com/tags/tag_details.asp

**Comment by gabbsmo** [comment]
Good old `<p>` would be nice too.

**Comment by eastriverstudio** [comment]
@quantumleap33 this would be good! I also created a feature request here for creating html lists by adding `<ul>`and `<ol>` as extra tag name options to containers and then `<li>` tag to nested elements: https://github.com/tomusborne/generateblocks/issues/772

**Comment by quantumleap33** [comment]
@eastriverstudio Yeah, I saw your post, sounds like a good feature, I like it!

**Comment by JeanPaiva** [comment]
On version 1.7 we have made big changes to the container and all blocks, they are essential for the flexibility and future of GB. With that in mind, future versions are going to be easier to add more tag names for the container.

**Comment by KratosGemini** [comment]
Being able to use `<nav>` would be nice as well.
