### ISSUE TITLE
Grid block - inclusion of margin spacing options for grid wrapper

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#755]
I understand why the whole spacing panel is not part of the grid block's options, but it seems strange that we can't control margin on the grid's wrapper. For example sometimes I just want to create a bit of spacing between a grid block and other block elements but I have to resort to wrapping the grid in an extra container just to add some margin between. 

Could it be like the button wrapper so we just have the margin spacing controls exposed so we can add spacing from elements and the grid if we need to without using extra containers?

Thanks

**Comment by simkoG** [comment]
+1 for this feature.

**Comment by diggeddy** [comment]
Grid Block adds certain complexities to this requirement, for example the negative margin CSS it requires for its column gap offset would conflict with spacing controls.
Grid Block is also under review for new grid options and this issue has been noted in that review.
