### ISSUE TITLE
Error when editing widget in the customizer when GB is activated.

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#76]
### Description
When GB is activated, this error shows when editing widgets in the customizer and unable to save:
"An error has occurred. Please reload the page and try again."

No issue in Dashboard > Widget.

### Steps to reproduce
1. Activate GB and go to Customizer > Widget and edit any widgets.

#### Expected behavior
Save the widgets properly.

#### Actual behavior
Widgets are not being saved properly.

#### References: 
https://www.screencast.com/t/CVZO4uTJ

**Comment by JeanPaiva** [comment]
It's a confirmed bug. `WP_Customize_Widgets:1477` is returning a WP_Error for the captured options check. The option `generateblocks_dynamic_css_posts` is found in the options at the moment of the error.
