### ISSUE TITLE
get_the_excerpt() deprecated arg warning

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#765]
We get a deprecated arg warning when `$source_id` doesn't return an actual ID in our `get_the_excerpt()` function: https://github.com/tomusborne/generateblocks/blob/8816e5ab471cdb5b6617e1d8ab9927bc0165a689/includes/class-dynamic-content.php#L205

`Function get_the_excerpt was called with an argument that is <strong>deprecated</strong> since version 2.3.0 with no alternative available.`

Reference: https://secure.helpscout.net/conversation/2060989166/360161?folderId=3610635

**Comment by JeanPaiva** [comment]
Possible solution for this:

```php
if ( ! $source_id || ( isset( self::$source_ids[ $unique_id ] ) && $source_id === self::$source_ids[ $unique_id ] ) ) {
    return '';
}
```
