### ISSUE TITLE
WP 6.1.1. has an improved block locking feature that does not work on GenerateBlocks

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#770]
### Description
At this point in video [Demo of the Feature](https://youtu.be/1Pw78VyG5BI?t=581) block locking UI has a new checkbox that enables locking a block and all of its children with one click. Up until now one had to go from block to block and individually lock them.

So this feature is huge!!! (it also came with the new filter that enables one to prevent editors or specific users from locking or unlocking, so amazing).

However, it does not work with GenerateBlock. If I try to apply it i get the old UI.

### Steps for testing
1. Insert core/group
2. Insert core/paragraph inside the group
3. In the structure List View pannel, click on three dots of the group block, click on the lock icon, and modal popes up, click on lock icon there and you will get this modal:

![locking the core blocks](https://user-images.githubusercontent.com/53581066/202223409-8362ad6d-fe25-47c5-956d-5f2f23dfde40.png)

1. Insert generateblocks/container
2. insert generateblocks/headline
3. In the structure List View pannel, click on three dots of the container block, click on the lock icon, and modal popes up, click on lock icon there and you will get this modal:

![locking gb](https://user-images.githubusercontent.com/53581066/202223793-3997d9f0-0c0f-4cd2-a7b2-aeb095864d22.png)

#### References:
Please add this new feature. It is amazing. (PS third party can have it, as Kadence blocks have this)

-----

**Comment by masteradhoc** [comment]
+1 👍🏻

**Comment by JeanPaiva** [comment]
We are going to take a look at this and make sure GB is compatible with this new feature. Although, we will look at this on version 1.8 since the 1.7 version is pretty much ready for public testing in the upcoming weeks.

**Comment by thisbit** [comment]
I downloaded 1.7 today. Amazing... cannot wait
