### ISSUE TITLE
[GB 1.7] Block error when adding background image

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#779]
### Description
There is an error when a container background image is added.

### Steps to reproduce
1. Add a container.
2. Click the Insert Inner Container button.
3. Select the outer container and set a background image.

#### Expected behavior
Background image should appear

#### Actual behavior
The block returns an error. Once you refresh, it shows as normal.

#### References: 
https://www.loom.com/share/2e669a19b496431cb746ad8995a1c2df

-----

**Comment by diggeddy** [comment]
Notes: 
Error in console: TypeError: undefined is not an object (evaluating 'n.length'
When the error first appears the Image URL is empt.y
If you switch to Code Editor and back to Visual Editor the error clears and the image is displayed.
