### ISSUE TITLE
wp-editor should not be enqueued in the new widget editor

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#78]
### Description
In WP 5.8-RC3, we're seeing this notice: https://www.screencast.com/t/pZst8jRoE87

This is due to this change in core: https://github.com/WordPress/wordpress-develop/pull/1484

I'm not 100% sure if this dependency is needed in the editor, but we need to remove the `wp-editor` dependency (https://github.com/tomusborne/generateblocks/blob/1.3.4/includes/general.php#L26) when inside the block widget editor.

### Steps to reproduce
Open the block widget editor in 5.8 when GB is activated.

#### References: 
https://github.com/WordPress/wordpress-develop/pull/1484
https://core.trac.wordpress.org/ticket/53569

**Comment by JeanPaiva** [comment]
Fixed #80
