### ISSUE TITLE
GenerateBlocks Container in 1.7 pre-alpha does not have a conditional display option when used in elements

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#803]
### Description

I am playing with the new upcoming blocks!
I know its not yet alpha, but as I am working on a new site that plans to use the feature "remove container condition" to not display the container and its contents if an ACF field is empty, I am worried that I see new blocks do not have this option anymore.

To find this issue:

create an element, block element, content type. Place a container and something into container.
create an acf field, simple text field is fine.

clck the container and look for "remove container condition" option.

the option does not exist.

Thanks

-----

**Comment by tomusborne** [comment]
This will be fixed in GP Premium 2.3 which will release around the same time as 1.7.

Thanks!

**Comment by thisbit** [comment]
Any dates you have in mind ? 😁

**Comment by spixels** [comment]
I still don't have this option in my container blocks.

GP Premium 2.2.2
GB 1.7.3
GB Pro 1.5.2

Is there an ETA?
