### ISSUE TITLE
Headline - icon above only sits in center on front end, while it changes position with the headline alignment in editor.

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#804]
### Description
Headline - icon above only sits in the center on the front end, while it changes position with the headline alignment in the editor.

### Steps to reproduce
1.  Add a headline block, add an icon.
2.  Set icon location to above, it sits on the left by default in the editor.
3.  Check the front end, It sits in the center.

#### Expected behavior
The same as the editor shows.

#### Actual behavior
...

#### References: 
...

-----

**Comment by tomusborne** [comment]
@leohsiang is this still an issue with the current options?

**Comment by diggeddy** [comment]
No longer an issue with Layout > Display > Flex
