### ISSUE TITLE
Container block (1.7.0-alpha.1) - max-width setting has no effect in the editor

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#813]
Trying the new 1.7.0 container block (with a nested inner container to replicate the legacy contained style) setting the max-width option with either the inherit global width value or using a custom value has no effect the editor. On the frontend it seems to work OK and the setting is respected.

Thanks

**Comment by tomusborne** [comment]
Hey @eastriverstudio, I'm not able to replicate this on my end.


https://user-images.githubusercontent.com/20714883/206746469-db2db0b3-c9b5-4a8f-94fb-5d79c6838a3f.mp4

**Comment by eastriverstudio** [comment]
@tomusborne Hmm that's strange. Here's a screenshot of what I'm getting in the editor using the max width setting:

<img width="1776" alt="CleanShot 2022-12-10 at 16 15 19@2x" src="https://user-images.githubusercontent.com/37620756/206864694-ab562a28-fb36-47d7-a76b-529be93b4fb3.png">

It seems to do this whether the container is nested or not. Looks fine on the frontend though:

<img width="1533" alt="CleanShot 2022-12-10 at 16 21 13@2x" src="https://user-images.githubusercontent.com/37620756/206864764-5150a87b-d586-4054-b41f-a53473d7f68d.png">

Note, I'm using Firefox when I edit but I assume that shouldn't make a difference?

Thanks

**Comment by eastriverstudio** [comment]
@tomusborne OK I think you can safely ignore this one. Having a further look at my specific setup on this test site I realised I was still running an older version of GPP. Updating it to the latest version 2.2.2 of GPP fixes the issue with the max-width now working as expected :)

One other issue I have noticed though is with the image block/grid container in the editor. In a grid pre 1.7.0 you used to be able to add padding to the container and then use negative margin on a image block to allow the image to sit flush but other content retain the padding.  This no longer seems to work in 1.7.0 alpha and you get the below. Seems to be because in the editor a max-width vlaue is being applied by the .wp-block class as demonstrated:

![CleanShot 2022-12-10 at 17 26 49@2x](https://user-images.githubusercontent.com/37620756/206867922-1140e9d1-6ded-4c03-864f-c8080bdacd8e.png)

Thanks

**Comment by tomusborne** [comment]
@eastriverstudio I don't like how that `max-width` applies to everything, but that hasn't really changed recently.

Is the image wide enough to fill the available space?

**Comment by eastriverstudio** [comment]
@tomusborne Yes it seems inconvenient to say the least! The negative margin trick definitely worked in the older grid as it was a style I've repeated a few times when creating similar grids and query loops with images like the screenshot above. The image is also wide enough to fill the space, the examples above are all 1000px wide, so something definitely seems to have changed in the editor using the new style container.

**Comment by eastriverstudio** [comment]
@tomusborne if it helps to investigate the difference here's a screenshot of a pre 1.7.0 grid where I've applied the same negative margin on the image. It looks like there used to be a style set to stop this in GB as highlighted. If I remove it I get the same result as my screens above:

![CleanShot 2022-12-13 at 00 42 46@2x](https://user-images.githubusercontent.com/37620756/207198803-3a0f8e34-39b5-4a80-93b0-2e987355f850.png)

Thanks

**Comment by tomusborne** [comment]
What is your `var(--content-width)` set to? It should show you if you hover over it.

**Comment by eastriverstudio** [comment]
@tomusborne `var(--content-width)` is set to 100%.
