### ISSUE TITLE
Abiltiy to specifiy colors for media prefers-color-scheme

### ISSUE THREAD

**Issue by cbreimhurst** [tomusborne/generateblocks#823]
### Description
Like the ability to specify attributes for media queries for Desktop, Tablet, and Phone - another row underneath that would be for light and dark. So that one could overide the colors (perhaps spacing too) for users that have dark mode set on their device. 

Note: could also be implemented in GeneratePress customization area

#### References:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme 

-----

**Comment by diggeddy** [comment]
This is something best handled by the Theme, where the color variables are defined. And have the variable swap based on `prefers-color-scheme` 
Closing
