### ISSUE TITLE
GenerateBlocks fails with Fatal Error if FS_METHOD is ftpext under PHP 8.0 or later

### ISSUE THREAD

**Issue by hideishi-m** [tomusborne/generateblocks#827]
### Description
GenerateBlocks fails with Fatal Error if FS_METHOD is ftpext under PHP 8.0 or later.
This is because PHP 8.0 changed to send Fatal Error if null is given to ftp_fput() which is called via WP_Filesystem under FS_METHOD is ftpext.

```
2022/12/20 17:04:10 [error] 2596#2596: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: ftp_fput(): Argument #1 ($ftp) must be of type resource, null given in /DocumentRoot/wp-admin/includes/class-wp-filesystem-ftpext.php:212
Stack trace:
#0 /DocumentRoot/wp-admin/includes/class-wp-filesystem-ftpext.php(212): ftp_fput(NULL, '/...', Resource id #35, 2)
#1 /DocumentRoot/wp-content/plugins/generateblocks/includes/class-enqueue-css.php(232): WP_Filesystem_FTPext->put_contents('/...', '.gb-container ....', 420)
#2 /DocumentRoot/wp-content/plugins/generateblocks/includes/class-enqueue-css.php(112): GenerateBlocks_Enqueue_CSS->make_css()
#3 /DocumentRoot/wp-content/plugins/generateblocks/includes/class-enqueue-css.php(140): GenerateBlocks_Enqueue_CSS->mode()
#4 /DocumentRoot/wp-includes/class-wp-hook.php(308): GenerateBlocks" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: example.com, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "example.com"
```

The root issue is here in wp-content/plugins/generateblocks/includes/class-enqueue-css.php.

```
        // Initialize the WordPress filesystem.
        if ( empty( $wp_filesystem ) ) {
            require_once ABSPATH . '/wp-admin/includes/file.php';
            WP_Filesystem();
        }
```

WP_Filesystem() without any args (credentials) always fails unless FS_METHOD is direct. Hence, it returns a $wp_filesystem which has no connection opend to the backend. Therefore, following put_contents() always fails.

Upto PHP 7.4, put_contents() to null (un-opened FTP connection) returned Warning instead of Fatal Error. Therefore this BUG was not visible. However, as PHP 8.0 tunred this to Fatal Error, this will always fail.

Using FS_METHOD with ssh2 also fails. However, because ssh2 returns Warning instead of Fatal Error, you will only see warnings. But, the root cause is the same that you need to supply credentials to WP_Filesystem().

### Steps to reproduce
1. Change FS_METHOD to ftpext in wp-config.php with applicable FTP_HOST, FTP_USER, and FTP_PASS.
2. Access any page on WordPress with generateblocks plugin and theme enabled.

#### Expected behavior
The page should show up.

#### Actual behavior
WordPress shows fatal error.

#### References: 
You can test with the following simple code that you cannot use WP_Filesystem() without any args with FS_METHOD = ftpext.

```
<?php

require_once __DIR__ . '/wp-load.php';

global $wp_filesystem;

if ( empty( $wp_filesystem ) ) {
        require_once ABSPATH . '/wp-admin/includes/file.php';
        $ret = WP_Filesystem();
        var_dump( $ret );
        var_dump( $wp_filesystem );
}
```

-----

**Comment by JeanPaiva** [comment]
@hideishi-m thank you for finding this bug. We are going to fix it in the next version.
