### ISSUE TITLE
there is no "no results" section for generatepress query loop

### ISSUE THREAD

**Issue by linuxd3v** [tomusborne/generateblocks#833]
### Description
When I use generate press query loop - and when there are no results found ->  generate press query loop does not show "no results block".  

In a standard  wordpress query loop this is accomplished like this:   
   
```html
	<!-- wp:query-no-results -->
		<!-- wp:pattern {"slug":"mytheme/hidden-no-results-content"} /-->
	<!-- /wp:query-no-results -->
```

I guess this is probably a feature request.

**Comment by BeholdPL** [comment]
Currently, if I set "order by: menu order" I see "no results found" in Gutenberg Editor (but works fine on front). I think it's a bug :)
