### ISSUE TITLE
Fix/sticky containers

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generateblocks#865]
It would be interesting to be able to fix/sticky containers while scrolling.

Practical examples:

- Sticky table of contents
- Sticky social media icons
- Sticky Ads

Examples: https://de.wordpress.org/plugins/q2w3-fixed-widget/

**Comment by JeanPaiva** [comment]
@SchneiderSam we have plans to add more `position` options in the future, like absolute, sticky and so on. I'll add this issue to our list of improvements for the container block so we can track internally. Thanks once again!

Reference: https://github.com/tomusborne/generateblocks-pro/issues/214

**Comment by SchneiderSam** [comment]
@JeanPaiva https://twitter.com/nickmdiego/status/1616072992122978307?s=20&t=QouQXEe_-jNKJOBBCOLB3Q

related
