### ISSUE TITLE
Align wide/full missing when using theme.json

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#87]
### Description
It's been reported that themes using `theme.json` do not display the align wide/full option in the Container block.

It seems block themes don't use `add_theme_support`, which GB depends on checking to add this option: https://fullsiteediting.com/lessons/global-styles/#h-layout-and-content-width

The reason we check for support and add it instead of using the built-in way of adding it is because we don't want Container blocks inside the Grid to have the option.

### Steps to reproduce
1. Add a block theme
2. Check the Container block for full/wide alignment options.

#### Expected behavior
The option should appear if the block theme supports it.

#### Actual behavior
The option doesn't appear.

#### References: 
- https://wordpress.org/support/topic/container-alignment-option-missing-if-theme-json-exists/#post-14726447

**Comment by tomusborne** [comment]
Might be better to use `getThemeSupports()`: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/editor/src/components/theme-support-check/index.js#L41

**Comment by illycz** [comment]
I'm using Underscores and experimenting within global styles defined throu theme.json.

When I have theme.json in my theme, align wide and align full options missing in all blocks. I have set theme support for align-wide in functions.php. Options missing also when I set layout settings in theme.json and remove support from functions.php.

Any suggestion?

Thanks
