### ISSUE TITLE
Ability to remove a shape from tablet and mobile responsive previews

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#872]
A shape can be added from the other responsive previews other than desktop. It would be nice if we were able to remove those shapes from those previews as well, instead of having to go to the desktop view to remove them.

https://www.loom.com/share/de9ca067e645435c9b48c27f6fa476a7

**Comment by diggeddy** [comment]
Closing this as it will be reviewed under the following:
https://github.com/tomusborne/generateblocks/issues/1110
