### ISSUE TITLE
[GB 1.7 alpha] Slight bug when a flex container is selected in the editor

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#874]
When a flex container is selected from the list view, the justification settings are not taken into account. You would have to click in the container's children in the block editor for the settings to be visually updated. In the example below, the flex container's content is justified as `space-between`.

https://www.loom.com/share/811a4529bb4d4d6f8edc905f162939ba

**Comment by tomusborne** [comment]
Hey @quantumleap33 - the appender (+) is acting as a flex child here and showing you where the next item you add will go.

It's not possible to avoid this without hacky solutions, and we decided that seeing where the next flex item will go if you add it wasn't a bad thing.
