### ISSUE TITLE
Different Heading CSS format in v1.7

### ISSUE THREAD

**Issue by aryadhiratara** [tomusborne/generateblocks#879]
### Description
I'm testing GB1.7, and noticed that the css format for (at least) the headline content has changed. Before version 1.7, there was a heading tag and a class inside the css (like h2.gb-headline-28bb6032). But now it's only the heading tag class (.gb-headline-28bb6032). This makes the custom margin of the headline is not working when I use other themes such as blocksy. They have something like .entry-content h2 in their main css, so the GB headline css cannot override the main css. 
Can this be reverted in the next update? Thank you.

### Steps to reproduce
Add margin in headline blocks (h2, h3, and so on)

#### Expected behavior
Like the old version, there's a heading tag before the class, like h2.gb-headline-28bb6032

#### Actual behavior
Now it's only the heading tag class (.gb-headline-28bb6032)

#### References: 
...

-----

**Comment by tomusborne** [comment]
Hi @aryadhiratara,

This will be fixed in the next update (https://github.com/tomusborne/generateblocks/pull/877).

Thanks!

**Comment by aryadhiratara** [comment]
Thank you! :)

**Comment by BeholdPL** [comment]
Issue still occurs in the global styles. Fixing needed ASAP :)
