### ISSUE TITLE
Headline icon won't go inline on mobile if it's set to above on tablet

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#88]
### Description
Headline icon won't go inline on mobile if it is set to above on tablet. 
Mobile inherits the` flex-direction: column;` from tablet.

### Steps to reproduce
https://pastebin.com/wB6dS3Rf 

#### Expected behavior
Icon should go inline on mobile.

#### Actual behavior
Icon stays above on mobile.

#### References: 
...

-----

**Comment by tomusborne** [comment]
No longer an issue with the new Layout controls.
