### ISSUE TITLE
[GB 1.7 alpha] Container shapes are not visible in the front end

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#891]
When setting container shapes, they are visible in the block editor but hidden in the front end.

**Comment by quantumleap33** [comment]
Ok, seems like container position needs to be set to `relative`. Was obvious enough.

**Comment by tomusborne** [comment]
It should set itself to relative when you add the shape. Did that not happen @quantumleap33?

**Comment by quantumleap33** [comment]
Ah, ok @tomusborne. Yeah, it does. Maybe I was playing around with it earlier.
