### ISSUE TITLE
Bug while editing svg icon code from the block editor html input

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#906]
There is a small issue when trying to edit an icon's SVG code from the icon's ICON SVG HTML input on the right panel of the block editor. When deleting something from the code, the cursor jumps to the end of the line.

**Comment by diggeddy** [comment]
Don't try to edit SVGs in that input field. Use a code editor.
UI will never be great for editing SVG in a single line input field.
Closing, won' t fix
