### ISSUE TITLE
Remove inner container for Query loop - (inline with new 1.7 release)

### ISSUE THREAD

**Issue by tdrayson** [tomusborne/generateblocks#911]
### Description
Remove the inner div for Query loop - (inline with new 1.7 release)

When adding classes to the "post template" div inside the query loop, the class gets added to the inner div inside the `gb-query-loop-item` div.

It seems redundant having this extra div and would make things cleaner and more inline with the introduction of generateblocks 1.7 release where we no longer have the `gb-inside-container` div by default.

#### References:
![](https://p137.p2.n0.cdn.getcloudapp.com/items/4guNw515/af9c5d5a-f2a0-4fb7-9865-7c933bfccf7d.jpg?source=viewer&v=9ee2282a69608b6d639c758840886fd4)

-----

**Comment by diggeddy** [comment]
Currently the Query loop relies on the GB Grid Block to form its columns. 
In a future update we will be changing that so gb-gird-column won't be required. Making the `gb-container` added for the Post Template the top level element.

**Comment by tdrayson** [comment]
Thanks for the update, the end result still achieves the same outcome where theres only 1 child div.

Look forward to update.

**Comment by diggeddy** [comment]
Closing - this will be resolved by detaching grid block from query loop:
https://github.com/tomusborne/generateblocks/issues/967
