### ISSUE TITLE
Ability to set to closed to start

### ISSUE THREAD

**Issue by anphira** [tomusborne/generateblocks#912]
For video accessibility, we need to include transcripts with our videos. But many of these transcripts are LONG so we want them in a collapsible accordion/toggle which is CLOSED to start. Then openable if desired. So, in order for this block to be useful for us (and probably many others), we need to be able to make the accordion CLOSED to start.

Additionally, it needs to behave like a normal accordion. Only first item open to start, and the rest closed. They ALL start open. Then I click to close any one of them and they ALL close. Here's an example, running 2020 theme. Cloudways hosting, only generate free & pro and breeze plugins active. https://wordpress-862275-3291207.cloudwaysapps.com/seo-marketing/build-privacy-policy/

Also, when closed there is no bottom margin, so it's smushed up against the other accordions, making it very hard to distinguish which is which.

**Comment by JeanPaiva** [comment]
Hey @anphira we have two options that you can play with that might help you.

The first options is "Keep multiple items open" you can find this option by selecting the "Accordion" block. In the inspector controls you should see a new section called "Block settings" with that option inside.

![image](https://user-images.githubusercontent.com/7506830/220131879-8d634ae1-0f31-4bdd-b86a-f3338e030839.png)

The second option is "Item open by default" you can find this option by selecting your "Accordion item" blocks, every item has it's own configuration.

![image](https://user-images.githubusercontent.com/7506830/220132847-901e0fab-7375-43c5-a87e-8876b2d3296e.png)

So, for your use case the first option must be disabled, so it keeps only one item open at the time, and all accordion items should have the second option disabled but the first one. Let me know if that helps you. Thanks

**Comment by anphira** [comment]
thanks

**Comment by JeanPaiva** [comment]
You're welcome. Have a great day
