### ISSUE TITLE
New GenerateBlocks 1.7rc has no conditional display

### ISSUE THREAD

**Issue by thisbit** [tomusborne/generateblocks#914]
### Description
I hope we did not lose this feature for good. In current and previous versions we had the ability to not display an element if a meta field is empty. WHen 1.7 alpha was out i noticed it is gone, and asked somewhere, maybe here maybe in the forum. And I got the answer its probably just due to it being an alpha. But checking RC now, I see the feature is GONE.

If this is not intentional please bring it back. If it is intentional, please revise. :(

### Steps to reproduce
1. Create an GP Block Element
2. Add container
3. Add Headline in the container
4. Add dynamic data to headline, meta field, add meta field key
5. Select the parent container element
6. Check not to render if that field is empty

#### Expected behavior
Has the option

#### Actual behavior
Does not have the option

#### References: 
...
![old](https://user-images.githubusercontent.com/53581066/220172354-881559e0-b1de-48ca-ba1e-1f82a60b47da.png)

-----
![new](https://user-images.githubusercontent.com/53581066/220172368-b893dca9-c2f4-4dff-af85-69c1c1409a3b.png)

**Comment by tomusborne** [comment]
This will be fixed in the upcoming GPP update that will enter alpha this week.
