### ISSUE TITLE
 GB1.7 Query Loop Block - Post Excerpt count not working when using latest gutenberg plugin

### ISSUE THREAD

**Issue by linuxd3v** [tomusborne/generateblocks#925]
### Description  
Generate blocks auto-updated to version 1.7 - post excerpts are no longer automatically clamped to a specific length.   
It always just shows 100 words.   
  
Note - it shows a correct number in the backend preview, just not on the actual site.  

After testing disabling all of the plugins I use -> Issue is only reproducible when I use the latest Gutenberg plugin (15.2.1). 

### Steps to reproduce
create a new query loop that looks like this:
![image](https://user-images.githubusercontent.com/3410509/221379637-fc56516a-d612-454c-8104-8533841d7bab.png)
     
Then add the headline block with excerpt length, ex:  
![image](https://user-images.githubusercontent.com/3410509/221379799-c3d80653-3a5b-4413-a1ad-81c764beede1.png)

```
<!-- wp:generateblocks/headline {"uniqueId":"9cc3a8fe","blockVersion":2,"sizing":[],"fontSize":17,"useDynamicData":true,"dynamicContentType":"post-excerpt","excerptLength":30} -->
<h2 class="gb-headline gb-headline-9cc3a8fe gb-headline-text"></h2>
<!-- /wp:generateblocks/headline --> 
```

#### Expected behavior
Expected to see 30 words excerpts

#### Actual behavior
Seeing 100 words excerpts

-----

**Comment by linuxd3v** [comment]
Similarities to https://github.com/tomusborne/generateblocks/issues/532

**Comment by linuxd3v** [comment]
After some testing -> it appears like it could be rather Gutenberg plugin (15.2.1) (or some combination). But disabling of gutenberg plugin solved this issue for me.

**Comment by diggeddy** [comment]
Gutenberg Plugin introduces untested features and bugs.
Closing this as old and no fix.
