### ISSUE TITLE
Add a filter hook to add own font family list

### ISSUE THREAD

**Issue by idrosua** [tomusborne/generateblocks#937]
### Description
As a developer of [Yabe Webfont](https://webfont.yabe.land/) which offers a simple solution to managed custom fonts, I really need the filter hook that can be used for our plugin to register the fonts to a dropdown list of the Generateblocks’ block typography

Reference: https://generatepress.com/forums/topic/feature-request-custom-font-from-generatepress-in-generateblocks/#post-2556290

### Steps for testing
1.

#### References:
...

-----

**Comment by JeanPaiva** [comment]
@idrosua we will be adding a filter on our next version. Thanks
