### ISSUE TITLE
Duplication in widgets does not generate new ID for GB blocks

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#938]
Normal content (correct) behavior when the 2nd and 3rd items are duplicated:
https://www.screencast.com/t/zlE3j0Vy
https://www.screencast.com/t/YOMx2v3vlG

Widget area (incorrect) behavior when the 2nd and 3rd items are duplicated:
https://www.screencast.com/t/YJAeKuiEtE
https://www.screencast.com/t/5meIfrYlfx5c

**Comment by JeanPaiva** [comment]
Related to https://github.com/tomusborne/generateblocks/issues/129
