### ISSUE TITLE
Implement flex in GB post loop

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#949]
With the new flex controls it would be useful to have the option to use flex inside the GB loop post template instead of a grid. That would help with the layout as well in certain scenarios where we want columns to be equally distributed inside a row or a column without having to set grid container widths (eg, for dynamic layouts).

**Comment by eastriverstudio** [comment]
@quantumleap33 I literally just came on here to write a similar request and saw your post!

I agree, a related limitation I've found with the query loop being fixed to use the grid block currently is we can make use of the outer container's flex options and combining with `overflow-x: scroll` to have horizontally scrolling dynamic grids like we can with regular containers without additional custom css as the grid is set to wrap by default. 

Thanks

**Comment by quantumleap33** [comment]
@eastriverstudio Good point.

**Comment by eastriverstudio** [comment]
@JeanPaiva thanks and good to get a little insight for upcoming changes, it was not a complaint on the grid block, even with the new container tools I still use the grid heavily and I think it still has it's place when you just need a simpler grid structure and in most common scenarios it works perfectly. My use case was specific as some designs I'm working on are making use of the new horizontal scrolling options and it therefore it occurred to me it is 100% possible within the editor at moment whith the current query loop & grid block. 

Thanks

**Comment by SchneiderSam** [comment]
@JeanPaiva I think flex is a powerful tool and I also have my problems sometimes. If you continue to expand the library and provide cool paterns, it will help us best anyway.

**Comment by diggeddy** [comment]
This will be achievable when the grid block is detached from the Query Loop.
Closing  - referred here:

 https://github.com/tomusborne/generateblocks/issues/967
