### ISSUE TITLE
Detach Query Loop from Grid block

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#967]
Not all Query Loops need the Grid block.

**Comment by jam1e** [comment]
Would it be possible to have a couple of different options for this, such as a grid block,  a list block, or no parent container?

A project of mine uses MediaVine to serve ads. Ads are automatically placed within the `.entry-content`, between elements. Sadly they are not able to place ads between elements wrapped in a grid block (or any block other than a list). Our current solution is to have multiple query loop blocks, each only showing 1 post.

**Comment by diggeddy** [comment]
Closing as GB 2.0 has detached Grid. And the user now has options to add their own style for grids and markup for lists.
