### ISSUE TITLE
Global Styles Button text color overwritten by GP customizer Content Link color

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#975]
Global Styles: https://www.screencast.com/t/wBXRz8nZI
Editor: https://www.screencast.com/t/YdmNQjOTy
Front end with DecTools: https://www.screencast.com/t/9zL6WNkLy3

Reference topic: https://generate.support/topic/global-sytles-for-button-text-picking-up-customizer-link-color/

**Comment by tomusborne** [comment]
There is no solution here. The Global Style selector can't be more specific than the content link color.

In most cases users don't need the the Content Link color set - they can just use the Body link color.

**Comment by leohsiang** [comment]
That was quick. Will let the user know.
