### ISSUE TITLE
Select Box pop over modal ( downwards ) is janky and unusable on smaller screens

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#976]
### Description

https://user-images.githubusercontent.com/30641942/231423607-7ddc755f-96e2-4632-9488-fcbce9ba22bb.mov

Example shown is GB Query Loop Block - include pages parameter.

Limit the vertical height of the browser viewport to simulate a smaller screen.
When the pop over modal hangs below the viewport edge its impossible to scroll the select box to the end and results in some janky breakdancing :)

**Comment by tomusborne** [comment]
fixed https://github.com/tomusborne/generateblocks/pull/1000
