### ISSUE TITLE
Replacing WP Show Posts with Query Loop not working

### ISSUE THREAD

**Issue by jeiseman** [tomusborne/generateblocks#997]
### Description
I'm using the get_the_excerpt filter so that the behavior of the Query Loop is the same as the old WP Show Posts plugin but after that when saving the page with the Query Loop I get the error "Updating failed. The response is not a valid JSON response". If I use "get_the_content" instead of "the_content" it will work (but doesn't  handle shortcodes). I know we're supposed to use the Query Loop to replace WP Show Posts but this bug it making it difficult to do that.

### Steps to reproduce
1. Create a fresh installation of WordPress
2.  Add the code snippet (attached as codesnippet.txt)
3. Add the Classical Editor plugin and set it to allow the use of the block editor.
4. Add the GenerateBlocks plugin
5. Rename the 2 posts and pages txt file to xml and then import these.
6. Edit the Latest Posts page and change it and try to do a save.

#### Expected behavior
The save should work.

#### Actual behavior
I get the error message: Updating failed. The response is not a valid JSON response.

#### References: 
[codesnippet.txt](https://github.com/tomusborne/generateblocks/files/11416056/codesnippet.txt)

...

-----
[myblog.WordPress.2023-05-07-posts.txt](https://github.com/tomusborne/generateblocks/files/11416075/myblog.WordPress.2023-05-07-posts.txt)
[myblog.WordPress.2023-05-07-pages.txt](https://github.com/tomusborne/generateblocks/files/11416076/myblog.WordPress.2023-05-07-pages.txt)

**Comment by diggeddy** [comment]
This is not a bug with the block. But an issue with appending HTML to blocks content within the editor,
Try this snippet so the filter only affects the front end:

```
add_filter( 'get_the_excerpt', 'mu_the_excerpt_pre', 10, 2 );
function mu_the_excerpt_pre( $excerpt, $post ) {
    if ( is_admin() ) {
        return $excerpt;
    }
    if ( strpos( $post->post_content, '<!--more-->' ) ) {
        return the_content();
    }
    else {
        $excerpt .= ' <nobr><span class="read-more"><em><strong>[<a href="' . get_permalink() . '">continued</a>]</strong></em></span></nobr>';
    }
    return $excerpt;
}
```
